# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from talon_one.models.effect_all_of_props import EffectAllOfProps

class TestEffectAllOfProps(unittest.TestCase):
    """EffectAllOfProps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EffectAllOfProps:
        """Test EffectAllOfProps
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EffectAllOfProps`
        """
        model = EffectAllOfProps()
        if include_optional:
            return EffectAllOfProps(
                value = 1.337,
                id = 56,
                rejection_reason = '',
                condition_index = 56,
                effect_index = 56,
                details = '',
                campaign_exclusion_reason = 'CampaignGaveLowerDiscount',
                profile_id = 150,
                name = '',
                scope = '',
                desired_value = 1.337,
                position = 1.337,
                sub_position = 1.337,
                total_discount = 1.337,
                desired_total_discount = 1.337,
                bundle_index = 1,
                bundle_name = 'my_bundle',
                targeted_item_position = 1.337,
                targeted_item_sub_position = 1.337,
                excluded_from_price_history = True,
                additional_cost_id = 56,
                additional_cost = '',
                webhook_id = 1.337,
                webhook_name = '',
                program_id = 56,
                sub_ledger_id = '',
                recipient_integration_id = 'URNGV8294NV',
                start_date = '2026-04-16T15:25:37Z',
                expiry_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                transaction_uuid = '',
                cart_item_position = 1,
                cart_item_sub_position = 2,
                card_identifier = 'summer-loyalty-card-0543',
                awaits_activation = True,
                validity_duration = '',
                rule_title = '',
                previous_tier_name = '',
                new_tier_name = '',
                sku = 'SKU1241028',
                desired_quantity = 56,
                notification_type = '',
                title = '',
                body = '',
                path = '',
                description = '',
                bundle_attributes = [
                    ''
                    ],
                items_indices = [
                    1.337
                    ],
                pool_id = 2,
                pool_name = 'My pool',
                giveaway_id = 5,
                code = '57638t-67439hty',
                message = '',
                effect_id = 1,
                payload = None,
                coupon_value = '',
                profile_integration_id = 'URNGV8294NV',
                is_new_reservation = True,
                audience_id = 10,
                audience_name = 'My audience',
                achievement_id = 10,
                achievement_name = 'FreeCoffee10Orders',
                progress_tracker_id = 42,
                delta = 1.337,
                target = 10,
                is_just_completed = True,
                decrease_progress_by = 1.337,
                current_progress = 1.337,
                extension_duration = '12h',
                affected_transactions = [
                    talon_one.models.loyalty_ledger_entry_expiry_date_change.LoyaltyLedgerEntryExpiryDateChange(
                        transaction_uuid = '', 
                        previous_expiry_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        new_expiry_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                new_expiry_date = '2024-07-24T14:15:22Z',
                end_date = '2026-04-30T11:24:59Z'
            )
        else:
            return EffectAllOfProps(
                value = 1.337,
                id = 56,
                rejection_reason = '',
                profile_id = 150,
                name = '',
                position = 1.337,
                additional_cost_id = 56,
                additional_cost = '',
                webhook_id = 1.337,
                webhook_name = '',
                program_id = 56,
                sub_ledger_id = '',
                recipient_integration_id = 'URNGV8294NV',
                start_date = '2026-04-16T15:25:37Z',
                transaction_uuid = '',
                rule_title = '',
                new_tier_name = '',
                sku = 'SKU1241028',
                notification_type = '',
                title = '',
                body = '',
                path = '',
                description = '',
                bundle_attributes = [
                    ''
                    ],
                items_indices = [
                    1.337
                    ],
                pool_id = 2,
                pool_name = 'My pool',
                giveaway_id = 5,
                code = '57638t-67439hty',
                message = '',
                effect_id = 1,
                payload = None,
                coupon_value = '',
                profile_integration_id = 'URNGV8294NV',
                is_new_reservation = True,
                achievement_id = 10,
                achievement_name = 'FreeCoffee10Orders',
                progress_tracker_id = 42,
                delta = 1.337,
                target = 10,
                is_just_completed = True,
                decrease_progress_by = 1.337,
                current_progress = 1.337,
                extension_duration = '12h',
                new_expiry_date = '2024-07-24T14:15:22Z',
        )
        """

    def testEffectAllOfProps(self):
        """Test EffectAllOfProps"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
