# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from talon_one.models.new_campaign_template import NewCampaignTemplate

class TestNewCampaignTemplate(unittest.TestCase):
    """NewCampaignTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewCampaignTemplate:
        """Test NewCampaignTemplate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewCampaignTemplate`
        """
        model = NewCampaignTemplate()
        if include_optional:
            return NewCampaignTemplate(
                name = '0',
                description = '',
                instructions = '',
                campaign_attributes = None,
                coupon_attributes = None,
                state = 'draft',
                tags = [
                    '0'
                    ],
                features = [
                    'coupons'
                    ],
                coupon_settings = talon_one.models.code_generator_settings.CodeGeneratorSettings(
                    valid_characters = [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 
                    coupon_pattern = 'SUMMER-####-####', ),
                coupon_reservation_settings = talon_one.models.campaign_template_coupon_reservation_settings.CampaignTemplateCouponReservationSettings(
                    reservation_limit = 45, 
                    is_reservation_mandatory = False, ),
                referral_settings = talon_one.models.code_generator_settings.CodeGeneratorSettings(
                    valid_characters = [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 
                    coupon_pattern = 'SUMMER-####-####', ),
                limits = [
                    null
                    ],
                template_params = [
                    talon_one.models.campaign_template_params.CampaignTemplateParams(
                        name = 'discount_value', 
                        type = 'number', 
                        description = 'This is a template parameter of type `number`.', 
                        attribute_id = 42, )
                    ],
                campaign_collections = [
                    talon_one.models.campaign_template_collection.CampaignTemplateCollection(
                        name = 'My collection', 
                        description = 'My collection of SKUs', )
                    ],
                default_campaign_group_id = 42,
                campaign_type = 'advanced'
            )
        else:
            return NewCampaignTemplate(
                name = '0',
                description = '',
                instructions = '',
                state = 'draft',
                campaign_type = 'advanced',
        )
        """

    def testNewCampaignTemplate(self):
        """Test NewCampaignTemplate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
