# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from talon_one.models.effect_rollback_increased_achievement_progress import EffectRollbackIncreasedAchievementProgress

class TestEffectRollbackIncreasedAchievementProgress(unittest.TestCase):
    """EffectRollbackIncreasedAchievementProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EffectRollbackIncreasedAchievementProgress:
        """Test EffectRollbackIncreasedAchievementProgress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EffectRollbackIncreasedAchievementProgress`
        """
        model = EffectRollbackIncreasedAchievementProgress()
        if include_optional:
            return EffectRollbackIncreasedAchievementProgress(
                experiment_id = 12,
                campaign_id = 244,
                ruleset_id = 73,
                rule_index = 2,
                rule_name = 'Give 20% discount',
                effect_type = 'rollbackIncreasedAchievementProgress',
                triggered_by_coupon = 4928,
                triggered_for_catalog_item = 786,
                condition_index = 786,
                evaluation_group_id = 3,
                evaluation_group_mode = 'stackable',
                campaign_revision_id = 1,
                campaign_revision_version_id = 5,
                selected_price_type = 'member',
                selected_price = 100,
                adjustment_reference_id = '68851723-e6fa-488f-ace9-112581e6c19b',
                reward_id = 7,
                props = {achievementId=10, achievementName=FreeCoffee10Orders, progressTrackerId=42, decreaseProgressBy=1, currentProgress=6, target=10}
            )
        else:
            return EffectRollbackIncreasedAchievementProgress(
                campaign_id = 244,
                ruleset_id = 73,
                rule_index = 2,
                rule_name = 'Give 20% discount',
                effect_type = 'rollbackIncreasedAchievementProgress',
                props = {achievementId=10, achievementName=FreeCoffee10Orders, progressTrackerId=42, decreaseProgressBy=1, currentProgress=6, target=10},
        )
        """

    def testEffectRollbackIncreasedAchievementProgress(self):
        """Test EffectRollbackIncreasedAchievementProgress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
