# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from talon_one.models.tier_upgrade_data import TierUpgradeData

class TestTierUpgradeData(unittest.TestCase):
    """TierUpgradeData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TierUpgradeData:
        """Test TierUpgradeData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TierUpgradeData`
        """
        model = TierUpgradeData()
        if include_optional:
            return TierUpgradeData(
                customer_profile_id = 'URNGV8294NV',
                loyalty_program_id = 5,
                subledger_id = '',
                current_tier = 'Silver',
                current_points = 120.55,
                old_tier = 'Bronze',
                points_required_to_the_next_tier = 23.51,
                next_tier = 'Gold',
                tier_expiration_date = '2023-12-01T12:23:00+02:00',
                timestamp_of_tier_change = '2023-10-26T12:23:00+02:00'
            )
        else:
            return TierUpgradeData(
                customer_profile_id = 'URNGV8294NV',
                loyalty_program_id = 5,
                subledger_id = '',
                current_tier = 'Silver',
                current_points = 120.55,
                tier_expiration_date = '2023-12-01T12:23:00+02:00',
                timestamp_of_tier_change = '2023-10-26T12:23:00+02:00',
        )
        """

    def testTierUpgradeData(self):
        """Test TierUpgradeData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
