# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from talon_one.models.promotion_block import PromotionBlock

class TestPromotionBlock(unittest.TestCase):
    """PromotionBlock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromotionBlock:
        """Test PromotionBlock
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromotionBlock`
        """
        model = PromotionBlock()
        if include_optional:
            return PromotionBlock(
                id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
                type = '',
                tags = [
                    ''
                    ],
                operator = 'setTo',
                blocks = [
                    null
                    ],
                on_failure = [
                    null
                    ],
                on_error = {
                    'key' : [
                        null
                        ]
                    },
                expression = [
                    null
                    ],
                notification_type = 'Info',
                title = 'You earned a reward!',
                body = 'You saved $10 on your order.',
                sku = 'SKU1241028',
                name = 'Free Tote Bag',
                quantity = '1',
                partial = False,
                giveaway_pool = talon_one.models.award_giveaway_block_1_giveaway_pool.AwardGiveawayBlock_1_giveawayPool(
                    id = 42, 
                    name = 'Summer Campaign Pool', ),
                profile = 'Current',
                attribute = talon_one.models.update_attribute_value_block_1_attribute.UpdateAttributeValueBlock_1_attribute(
                    id = 100, 
                    entity = 'profile', 
                    name = 'City', 
                    title = 'City', 
                    type = 'string', ),
                value = None,
                min = None,
                max = None,
                values = None,
                count = None,
                audience = talon_one.models.update_audience_membership_block_1_audience.UpdateAudienceMembershipBlock_1_audience(
                    id = 42, 
                    name = 'Travel audience', 
                    integration = 'mparticle', 
                    integration_id = '382370BKDB946', ),
                redeem = True,
                achievement = talon_one.models.update_achievement_progress_block_1_achievement.UpdateAchievementProgressBlock_1_achievement(
                    id = 42, 
                    name = 'Order50Discount', 
                    title = '50% off on 50th purchase.', 
                    target = 50, ),
                target = talon_one.models.update_attribute_value_block_1_target.UpdateAttributeValueBlock_1_target(
                    type = 'profile', )
            )
        else:
            return PromotionBlock(
                id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
                type = '',
                operator = 'setTo',
                blocks = [
                    null
                    ],
                expression = [
                    null
                    ],
                notification_type = 'Info',
                title = 'You earned a reward!',
                sku = 'SKU1241028',
                name = 'Free Tote Bag',
                quantity = '1',
                giveaway_pool = talon_one.models.award_giveaway_block_1_giveaway_pool.AwardGiveawayBlock_1_giveawayPool(
                    id = 42, 
                    name = 'Summer Campaign Pool', ),
                profile = 'Current',
                attribute = talon_one.models.update_attribute_value_block_1_attribute.UpdateAttributeValueBlock_1_attribute(
                    id = 100, 
                    entity = 'profile', 
                    name = 'City', 
                    title = 'City', 
                    type = 'string', ),
                value = None,
                audience = talon_one.models.update_audience_membership_block_1_audience.UpdateAudienceMembershipBlock_1_audience(
                    id = 42, 
                    name = 'Travel audience', 
                    integration = 'mparticle', 
                    integration_id = '382370BKDB946', ),
                redeem = True,
                achievement = talon_one.models.update_achievement_progress_block_1_achievement.UpdateAchievementProgressBlock_1_achievement(
                    id = 42, 
                    name = 'Order50Discount', 
                    title = '50% off on 50th purchase.', 
                    target = 50, ),
                target = talon_one.models.update_attribute_value_block_1_target.UpdateAttributeValueBlock_1_target(
                    type = 'profile', ),
        )
        """

    def testPromotionBlock(self):
        """Test PromotionBlock"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
