# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from talon_one.models.rollback_deducted_loyalty_points_effect_props import RollbackDeductedLoyaltyPointsEffectProps

class TestRollbackDeductedLoyaltyPointsEffectProps(unittest.TestCase):
    """RollbackDeductedLoyaltyPointsEffectProps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RollbackDeductedLoyaltyPointsEffectProps:
        """Test RollbackDeductedLoyaltyPointsEffectProps
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RollbackDeductedLoyaltyPointsEffectProps`
        """
        model = RollbackDeductedLoyaltyPointsEffectProps()
        if include_optional:
            return RollbackDeductedLoyaltyPointsEffectProps(
                program_id = 56,
                sub_ledger_id = '',
                value = 1.337,
                recipient_integration_id = 'URNGV8294NV',
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expiry_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                transaction_uuid = '',
                card_identifier = 'summer-loyalty-card-0543'
            )
        else:
            return RollbackDeductedLoyaltyPointsEffectProps(
                program_id = 56,
                sub_ledger_id = '',
                value = 1.337,
                recipient_integration_id = 'URNGV8294NV',
                transaction_uuid = '',
        )
        """

    def testRollbackDeductedLoyaltyPointsEffectProps(self):
        """Test RollbackDeductedLoyaltyPointsEffectProps"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
