# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from talon_one.models.risk_detail import RiskDetail

class TestRiskDetail(unittest.TestCase):
    """RiskDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RiskDetail:
        """Test RiskDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RiskDetail`
        """
        model = RiskDetail()
        if include_optional:
            return RiskDetail(
                id = 6,
                created = '2020-06-10T09:05:27.993483Z',
                notification_id = 3,
                run_date = '2026-06-05',
                group_key = '7',
                application_id = 7,
                status = 'active',
                criticality = 'critical',
                entity = 'customer_profile',
                activity = 'discounted_amount',
                time_frame = '1_week',
                reported_date = '2026-06-05T06:26:13.698884Z',
                affected_entity_count = 4437,
                description = 'Unusual discount usage detected for 4437 customer profiles.',
                modified = '2026-06-05T06:26:13.698884Z',
                affected_entities = [
                    talon_one.models.risk_affected_entity_item.RiskAffectedEntityItem(
                        entity_id = '174165415', 
                        activity_value = 2898.2, 
                        threshold = 60, 
                        severity_ratio = 48.3, 
                        criticality = 'critical', )
                    ]
            )
        else:
            return RiskDetail(
                id = 6,
                created = '2020-06-10T09:05:27.993483Z',
                notification_id = 3,
                run_date = '2026-06-05',
                group_key = '7',
                status = 'active',
                criticality = 'critical',
                entity = 'customer_profile',
                activity = 'discounted_amount',
                time_frame = '1_week',
                reported_date = '2026-06-05T06:26:13.698884Z',
                affected_entity_count = 4437,
                modified = '2026-06-05T06:26:13.698884Z',
                affected_entities = [
                    talon_one.models.risk_affected_entity_item.RiskAffectedEntityItem(
                        entity_id = '174165415', 
                        activity_value = 2898.2, 
                        threshold = 60, 
                        severity_ratio = 48.3, 
                        criticality = 'critical', )
                    ],
        )
        """

    def testRiskDetail(self):
        """Test RiskDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
