# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from talon_one.models.get_loyalty_card_transaction_logs200_response import GetLoyaltyCardTransactionLogs200Response

class TestGetLoyaltyCardTransactionLogs200Response(unittest.TestCase):
    """GetLoyaltyCardTransactionLogs200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLoyaltyCardTransactionLogs200Response:
        """Test GetLoyaltyCardTransactionLogs200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLoyaltyCardTransactionLogs200Response`
        """
        model = GetLoyaltyCardTransactionLogs200Response()
        if include_optional:
            return GetLoyaltyCardTransactionLogs200Response(
                has_more = True,
                data = [
                    talon_one.models.card_ledger_transaction_log_entry.CardLedgerTransactionLogEntry(
                        transaction_uuid = 'ce59f12a-f53b-4014-a745-636d93f2bd3f', 
                        created = '2022-01-02T15:04:05Z07:00', 
                        program_id = 324, 
                        card_identifier = 'summer-loyalty-card-0543', 
                        application_id = 322, 
                        session_id = 233, 
                        customer_session_id = '05c2da0d-48fa-4aa1-b629-898f58f1584d', 
                        type = 'addition', 
                        name = 'Reward 10% points of a purchase's current total', 
                        start_date = '2022-01-02T15:04:05Z07:00', 
                        expiry_date = '2022-08-02T15:04:05Z07:00', 
                        subledger_id = 'sub-123', 
                        amount = 10.25, 
                        id = 123, )
                    ]
            )
        else:
            return GetLoyaltyCardTransactionLogs200Response(
                has_more = True,
                data = [
                    talon_one.models.card_ledger_transaction_log_entry.CardLedgerTransactionLogEntry(
                        transaction_uuid = 'ce59f12a-f53b-4014-a745-636d93f2bd3f', 
                        created = '2022-01-02T15:04:05Z07:00', 
                        program_id = 324, 
                        card_identifier = 'summer-loyalty-card-0543', 
                        application_id = 322, 
                        session_id = 233, 
                        customer_session_id = '05c2da0d-48fa-4aa1-b629-898f58f1584d', 
                        type = 'addition', 
                        name = 'Reward 10% points of a purchase's current total', 
                        start_date = '2022-01-02T15:04:05Z07:00', 
                        expiry_date = '2022-08-02T15:04:05Z07:00', 
                        subledger_id = 'sub-123', 
                        amount = 10.25, 
                        id = 123, )
                    ],
        )
        """

    def testGetLoyaltyCardTransactionLogs200Response(self):
        """Test GetLoyaltyCardTransactionLogs200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
