# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from talon_one.models.update_achievement_progress_block import UpdateAchievementProgressBlock

class TestUpdateAchievementProgressBlock(unittest.TestCase):
    """UpdateAchievementProgressBlock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAchievementProgressBlock:
        """Test UpdateAchievementProgressBlock
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAchievementProgressBlock`
        """
        model = UpdateAchievementProgressBlock()
        if include_optional:
            return UpdateAchievementProgressBlock(
                id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
                type = '',
                tags = [
                    ''
                    ],
                operator = 'increaseBy',
                value = '10',
                achievement = talon_one.models.update_achievement_progress_block_1_achievement.UpdateAchievementProgressBlock_1_achievement(
                    id = 42, 
                    name = 'Order50Discount', 
                    title = '50% off on 50th purchase.', 
                    target = 50, )
            )
        else:
            return UpdateAchievementProgressBlock(
                type = '',
                operator = 'increaseBy',
                value = '10',
                achievement = talon_one.models.update_achievement_progress_block_1_achievement.UpdateAchievementProgressBlock_1_achievement(
                    id = 42, 
                    name = 'Order50Discount', 
                    title = '50% off on 50th purchase.', 
                    target = 50, ),
        )
        """

    def testUpdateAchievementProgressBlock(self):
        """Test UpdateAchievementProgressBlock"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
