# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from talon_one.models.session_coupons import SessionCoupons

class TestSessionCoupons(unittest.TestCase):
    """SessionCoupons unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionCoupons:
        """Test SessionCoupons
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionCoupons`
        """
        model = SessionCoupons()
        if include_optional:
            return SessionCoupons(
                session_integration_id = 'cc53e4fa-547f-4f5e-8333-76e05c381f67',
                coupon_code = 'SUMMER2025'
            )
        else:
            return SessionCoupons(
                session_integration_id = 'cc53e4fa-547f-4f5e-8333-76e05c381f67',
        )
        """

    def testSessionCoupons(self):
        """Test SessionCoupons"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
