# coding: utf-8

# flake8: noqa

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "26.01"

# Define package exports
__all__ = [
    "IntegrationApi",
    "ManagementApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "APIError",
    "AcceptCouponEffectProps",
    "AcceptReferralEffectProps",
    "AccessLogEntry",
    "Account",
    "AccountAdditionalCost",
    "AccountAnalytics",
    "AccountDashboardStatistic",
    "AccountDashboardStatisticCampaigns",
    "AccountDashboardStatisticDiscount",
    "AccountDashboardStatisticLoyaltyPoints",
    "AccountDashboardStatisticReferrals",
    "AccountDashboardStatisticRevenue",
    "AccountEntity",
    "AccountLimits",
    "Achievement",
    "AchievementAdditionalProperties",
    "AchievementBase",
    "AchievementProgress",
    "AchievementProgressWithDefinition",
    "AchievementStatusEntry",
    "ActivateLoyaltyPoints",
    "ActivateLoyaltyPointsResponse",
    "ActivateUserRequest",
    "AddFreeItemEffectProps",
    "AddItemCatalogAction",
    "AddLoyaltyPoints",
    "AddLoyaltyPointsEffectProps",
    "AddPriceAdjustmentCatalogAction",
    "AddToAudienceEffectProps",
    "AddedDeductedPointsBalancesAction",
    "AddedDeductedPointsBalancesNotification",
    "AddedDeductedPointsBalancesNotificationPolicy",
    "AddedDeductedPointsNotification",
    "AddedDeductedPointsNotificationPolicy",
    "AdditionalCampaignProperties",
    "AdditionalCost",
    "AnalyticsDataPoint",
    "AnalyticsDataPointWithTrend",
    "AnalyticsDataPointWithTrendAndInfluencedRate",
    "AnalyticsDataPointWithTrendAndUplift",
    "AnalyticsProduct",
    "AnalyticsSKU",
    "Application",
    "ApplicationAPIKey",
    "ApplicationAnalyticsDataPoint",
    "ApplicationApiHealth",
    "ApplicationCIF",
    "ApplicationCIFExpression",
    "ApplicationCIFReferences",
    "ApplicationCampaignAnalytics",
    "ApplicationCampaignStats",
    "ApplicationCustomer",
    "ApplicationCustomerEntity",
    "ApplicationEntity",
    "ApplicationEvent",
    "ApplicationNotification",
    "ApplicationReferee",
    "ApplicationSession",
    "ApplicationSessionEntity",
    "ApplicationStoreEntity",
    "AsyncCouponCreationResponse",
    "AsyncCouponDeletionJobResponse",
    "AsyncCouponsData",
    "Attribute",
    "AttributesMandatory",
    "AttributesSettings",
    "Audience",
    "AudienceAnalytics",
    "AudienceCustomer",
    "AudienceIntegrationID",
    "AudienceMembership",
    "AudienceReference",
    "AwardGiveawayEffectProps",
    "BaseCampaign",
    "BaseLoyaltyProgram",
    "BaseNotification",
    "BaseNotificationEntity",
    "BaseNotificationWebhook",
    "BaseNotifications",
    "BaseSamlConnection",
    "BestPriorPrice",
    "BestPriorPriceMetadata",
    "BestPriorPriceRequest",
    "BestPriorPriceRequestTarget",
    "Binding",
    "BulkApplicationNotification",
    "BulkOperationOnCampaigns",
    "Campaign",
    "CampaignActivationRequest",
    "CampaignAnalytics",
    "CampaignBudget",
    "CampaignCollection",
    "CampaignCollectionEditedNotification",
    "CampaignCollectionEditedNotificationItem",
    "CampaignCollectionWithoutPayload",
    "CampaignCopy",
    "CampaignCreatedNotification",
    "CampaignCreatedNotificationItem",
    "CampaignDeactivationRequest",
    "CampaignDeletedNotification",
    "CampaignDeletedNotificationItem",
    "CampaignDetail",
    "CampaignEditedNotification",
    "CampaignEditedNotificationItem",
    "CampaignEntity",
    "CampaignEvaluationGroup",
    "CampaignEvaluationPosition",
    "CampaignEvaluationTreeChangedMessage",
    "CampaignEvaluationTreeChangedNotification",
    "CampaignGroup",
    "CampaignGroupEntity",
    "CampaignLogSummary",
    "CampaignNotificationBase",
    "CampaignNotificationGeneric",
    "CampaignNotificationItemBase",
    "CampaignNotificationPolicy",
    "CampaignRulesetChangedNotification",
    "CampaignRulesetChangedNotificationItem",
    "CampaignSearch",
    "CampaignSet",
    "CampaignSetBranchNode",
    "CampaignSetLeafNode",
    "CampaignSetNode",
    "CampaignStateChangedNotification",
    "CampaignStateChangedNotificationItem",
    "CampaignStoreBudget",
    "CampaignStoreBudgetLimitConfig",
    "CampaignTemplate",
    "CampaignTemplateCollection",
    "CampaignTemplateCouponReservationSettings",
    "CampaignTemplateParams",
    "CampaignVersions",
    "CardAddedDeductedPointsBalancesNotification",
    "CardAddedDeductedPointsBalancesNotificationPolicy",
    "CardAddedDeductedPointsNotification",
    "CardAddedDeductedPointsNotificationPolicy",
    "CardExpiringPointsNotificationPolicy",
    "CardExpiringPointsNotificationTrigger",
    "CardLedgerPointsEntryIntegrationAPI",
    "CardLedgerTransactionLogEntry",
    "CardLedgerTransactionLogEntryIntegrationAPI",
    "CartItem",
    "Catalog",
    "CatalogActionFilter",
    "CatalogItem",
    "CatalogSyncRequest",
    "CatalogsStrikethroughNotificationPolicy",
    "Change",
    "ChangeLoyaltyTierLevelEffectProps",
    "ChangeProfilePassword",
    "CodeGeneratorSettings",
    "Collection",
    "CollectionItem",
    "CollectionWithoutPayload",
    "Coupon",
    "CouponConstraints",
    "CouponCreatedEffectProps",
    "CouponCreationJob",
    "CouponDeletionFilters",
    "CouponDeletionJob",
    "CouponEntity",
    "CouponFailureSummary",
    "CouponLimitConfigs",
    "CouponRejectionReason",
    "CouponRejections",
    "CouponReservations",
    "CouponSearch",
    "CouponValue",
    "CouponsNotificationData",
    "CouponsNotificationPolicy",
    "CreateAchievement",
    "CreateApplicationAPIKey",
    "CreateCouponData",
    "CreateCoupons200Response",
    "CreateManagementKey",
    "CreateReferralsForMultipleAdvocates201Response",
    "CreateTemplateCampaign",
    "CreateTemplateCampaignResponse",
    "CustomEffect",
    "CustomEffectProps",
    "CustomerActivityReport",
    "CustomerAnalytics",
    "CustomerInventory",
    "CustomerProfile",
    "CustomerProfileAudienceRequest",
    "CustomerProfileAudienceRequestItem",
    "CustomerProfileEntity",
    "CustomerProfileIntegrationRequestV2",
    "CustomerProfileIntegrationResponseV2",
    "CustomerProfileSearchQuery",
    "CustomerProfileUpdateV2Response",
    "CustomerSession",
    "CustomerSessionV2",
    "DeactivateUserRequest",
    "DeductLoyaltyPoints",
    "DeductLoyaltyPointsEffectProps",
    "DeleteCouponsData",
    "DeleteUserRequest",
    "Effect",
    "EffectEntity",
    "EmailEntity",
    "Endpoint",
    "Entity",
    "EntityWithTalangVisibleID",
    "Environment",
    "ErrorEffectProps",
    "ErrorResponse",
    "ErrorResponseWithStatus",
    "ErrorSource",
    "EvaluableCampaignIds",
    "Event",
    "EventType",
    "EventV2",
    "EventV3",
    "ExpiringCardPointsData",
    "ExpiringCardPointsNotification",
    "ExpiringCouponsData",
    "ExpiringCouponsNotification",
    "ExpiringCouponsNotificationPolicy",
    "ExpiringCouponsNotificationTrigger",
    "ExpiringPointsData",
    "ExpiringPointsNotification",
    "ExpiringPointsNotificationPolicy",
    "ExpiringPointsNotificationTrigger",
    "Export",
    "ExtendLoyaltyPointsExpiryDateEffectProps",
    "ExtendedCoupon",
    "FeatureFlag",
    "FeaturesFeed",
    "FuncArgDef",
    "FunctionDef",
    "GenerateAuditLogSummary",
    "GenerateCampaignDescription",
    "GenerateCampaignSummary",
    "GenerateCampaignTags",
    "GenerateCouponFailureDetailedSummary",
    "GenerateCouponFailureSummary",
    "GenerateItemFilterDescription",
    "GenerateLoyaltyCard",
    "GenerateRuleTitle",
    "GenerateRuleTitleRule",
    "GenerateUserSessionSummary",
    "GetAccessLogsWithoutTotalCount200Response",
    "GetAdditionalCosts200Response",
    "GetApplicationCustomerFriends200Response",
    "GetApplicationCustomers200Response",
    "GetApplicationCustomersByAttributes200Response",
    "GetApplicationEventTypes200Response",
    "GetApplicationEventsWithoutTotalCount200Response",
    "GetApplicationSessions200Response",
    "GetApplications200Response",
    "GetAttributes200Response",
    "GetAudienceMemberships200Response",
    "GetAudiences200Response",
    "GetAudiencesAnalytics200Response",
    "GetCampaignAnalytics200Response",
    "GetCampaignGroups200Response",
    "GetCampaignTemplates200Response",
    "GetCampaigns200Response",
    "GetChanges200Response",
    "GetCollectionItems200Response",
    "GetCouponsWithoutTotalCount200Response",
    "GetCustomerAchievementHistory200Response",
    "GetCustomerAchievements200Response",
    "GetCustomerActivityReportsWithoutTotalCount200Response",
    "GetCustomerProfileAchievementProgress200Response",
    "GetCustomerProfiles200Response",
    "GetCustomersByAttributes200Response",
    "GetDashboardStatistics200Response",
    "GetEventTypes200Response",
    "GetExports200Response",
    "GetIntegrationCouponRequest",
    "GetLoyaltyCardPoints200Response",
    "GetLoyaltyCardTransactionLogs200Response",
    "GetLoyaltyCardTransactions200Response",
    "GetLoyaltyCards200Response",
    "GetLoyaltyProgramProfilePoints200Response",
    "GetLoyaltyProgramProfileTransactions200Response",
    "GetLoyaltyProgramTransactions200Response",
    "GetLoyaltyPrograms200Response",
    "GetReferralsWithoutTotalCount200Response",
    "GetReservedCustomers200Response",
    "GetRulesets200Response",
    "GetUsers200Response",
    "GetWebhooks200Response",
    "Giveaway",
    "GiveawaysPool",
    "HiddenConditionsEffects",
    "IdentifiableEntity",
    "ImportEntity",
    "IncreaseAchievementProgressEffectProps",
    "IntegrationCoupon",
    "IntegrationCustomerProfileAudienceRequest",
    "IntegrationCustomerProfileAudienceRequestItem",
    "IntegrationCustomerSessionResponse",
    "IntegrationEntity",
    "IntegrationEvent",
    "IntegrationEventV2Request",
    "IntegrationEventV3Request",
    "IntegrationEventV3Response",
    "IntegrationProfileEntity",
    "IntegrationProfileEntityV3",
    "IntegrationRequest",
    "IntegrationState",
    "IntegrationStateV2",
    "IntegrationStoreEntity",
    "InventoryCoupon",
    "InventoryReferral",
    "ItemAttribute",
    "LabelTargetAudience",
    "LabelTargetNone",
    "LedgerEntry",
    "LedgerInfo",
    "LedgerPointsEntryIntegrationAPI",
    "LedgerTransactionLogEntryIntegrationAPI",
    "LibraryAttribute",
    "LimitConfig",
    "LimitCounter",
    "ListAccountCollections200Response",
    "ListAchievements200Response",
    "ListAllRolesV2200Response",
    "ListCampaignStoreBudgetLimits200Response",
    "ListCampaignStoreBudgets",
    "ListCampaignStoreBudgetsStore",
    "ListCatalogItems200Response",
    "ListStores200Response",
    "LoginParams",
    "Loyalty",
    "LoyaltyBalance",
    "LoyaltyBalanceWithTier",
    "LoyaltyBalances",
    "LoyaltyBalancesWithTiers",
    "LoyaltyCard",
    "LoyaltyCardBalances",
    "LoyaltyCardBatch",
    "LoyaltyCardBatchResponse",
    "LoyaltyCardProfileRegistration",
    "LoyaltyCardRegistration",
    "LoyaltyDashboardData",
    "LoyaltyDashboardPointsBreakdown",
    "LoyaltyLedger",
    "LoyaltyLedgerEntry",
    "LoyaltyLedgerEntryExpiryDateChange",
    "LoyaltyLedgerEntryFlags",
    "LoyaltyLedgerTransactions",
    "LoyaltyMembership",
    "LoyaltyProgram",
    "LoyaltyProgramBalance",
    "LoyaltyProgramEntity",
    "LoyaltyProgramLedgers",
    "LoyaltyProgramTransaction",
    "LoyaltySubLedger",
    "LoyaltyTier",
    "ManagementKey",
    "ManagerConfig",
    "MessageLogEntries",
    "MessageLogEntry",
    "MessageLogRequest",
    "MessageLogResponse",
    "MessageTest",
    "Meta",
    "ModelImport",
    "ModelReturn",
    "MultiApplicationEntity",
    "MultipleAttribute",
    "MultipleAudiences",
    "MultipleAudiencesItem",
    "MultipleCustomerProfileIntegrationRequest",
    "MultipleCustomerProfileIntegrationRequestItem",
    "MultipleCustomerProfileIntegrationResponseV2",
    "MultipleNewAttribute",
    "MultipleNewAudiences",
    "MutableEntity",
    "NewAccount",
    "NewAccountSignUp",
    "NewAdditionalCost",
    "NewAppWideCouponDeletionJob",
    "NewApplication",
    "NewApplicationAPIKey",
    "NewApplicationCIF",
    "NewApplicationCIFExpression",
    "NewAttribute",
    "NewAudience",
    "NewBaseNotification",
    "NewCampaign",
    "NewCampaignCollection",
    "NewCampaignEvaluationGroup",
    "NewCampaignGroup",
    "NewCampaignSet",
    "NewCampaignStoreBudget",
    "NewCampaignStoreBudgetStoreLimit",
    "NewCampaignTemplate",
    "NewCatalog",
    "NewCollection",
    "NewCouponCreationJob",
    "NewCouponDeletionJob",
    "NewCoupons",
    "NewCouponsForMultipleRecipients",
    "NewCustomEffect",
    "NewCustomerProfile",
    "NewCustomerSession",
    "NewCustomerSessionV2",
    "NewEvent",
    "NewEventType",
    "NewExternalInvitation",
    "NewGiveawaysPool",
    "NewInternalAudience",
    "NewInvitation",
    "NewInviteEmail",
    "NewLoyaltyProgram",
    "NewLoyaltyTier",
    "NewManagementKey",
    "NewMessageTest",
    "NewMultipleAudiencesItem",
    "NewNotificationWebhook",
    "NewOutgoingIntegrationWebhook",
    "NewPassword",
    "NewPasswordEmail",
    "NewPicklist",
    "NewPriceAdjustment",
    "NewPriceType",
    "NewReferral",
    "NewReferralsForMultipleAdvocates",
    "NewReturn",
    "NewRevisionVersion",
    "NewRole",
    "NewRoleV2",
    "NewRuleset",
    "NewSamlConnection",
    "NewSecondaryDeployment",
    "NewStore",
    "NewTemplateDef",
    "NewUser",
    "NewWebhook",
    "Notification",
    "NotificationActivation",
    "NotificationListItem",
    "OktaEvent",
    "OktaEventPayload",
    "OktaEventPayloadData",
    "OktaEventTarget",
    "OneTimeCode",
    "OutgoingIntegrationBrazePolicy",
    "OutgoingIntegrationCleverTapPolicy",
    "OutgoingIntegrationConfiguration",
    "OutgoingIntegrationIterablePolicy",
    "OutgoingIntegrationMoEngagePolicy",
    "OutgoingIntegrationTemplate",
    "OutgoingIntegrationTemplateWithConfigurationDetails",
    "OutgoingIntegrationTemplates",
    "OutgoingIntegrationType",
    "OutgoingIntegrationTypes",
    "PatchItemCatalogAction",
    "PatchManyItemsCatalogAction",
    "PendingActivePointsData",
    "PendingActivePointsNotification",
    "PendingPointsNotificationPolicy",
    "Picklist",
    "PriceDetail",
    "PriceType",
    "PriceTypeReferenceDetail",
    "PriceTypeReferences",
    "PrismaticConfig",
    "PrismaticEventPayloadCouponBasedNotifications",
    "PrismaticEventPayloadCouponBasedNotificationsLimits",
    "PrismaticEventPayloadLoyaltyProfileBasedNotifications",
    "PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction",
    "PrismaticFlow",
    "PrismaticFlowConfig",
    "PrismaticFlowWithConfig",
    "PrismaticPaginatedEventPayload",
    "Product",
    "ProductSearchMatch",
    "ProductUnitAnalytics",
    "ProductUnitAnalyticsDataPoint",
    "ProductUnitAnalyticsTotals",
    "ProfileAudiencesChanges",
    "ProjectedTier",
    "RedeemReferralEffectProps",
    "Referral",
    "ReferralConstraints",
    "ReferralCreatedEffectProps",
    "ReferralRejectionReason",
    "RejectCouponEffectProps",
    "RejectReferralEffectProps",
    "RemoveFromAudienceEffectProps",
    "RemoveItemCatalogAction",
    "RemoveManyItemsCatalogAction",
    "ReopenSessionResponse",
    "ReserveCouponEffectProps",
    "ReturnIntegrationRequest",
    "ReturnedCartItem",
    "Revision",
    "RevisionActivation",
    "RevisionActivationRequest",
    "RevisionVersion",
    "Role",
    "RoleAssign",
    "RoleMembership",
    "RoleV2",
    "RoleV2ApplicationDetails",
    "RoleV2Base",
    "RoleV2PermissionSet",
    "RoleV2Permissions",
    "RoleV2Readonly",
    "RoleV2RolesGroup",
    "RollbackAddedLoyaltyPointsEffectProps",
    "RollbackCouponEffectProps",
    "RollbackDeductedLoyaltyPointsEffectProps",
    "RollbackDiscountEffectProps",
    "RollbackIncreasedAchievementProgressEffectProps",
    "RollbackReferralEffectProps",
    "Rule",
    "RuleFailureReason",
    "Ruleset",
    "SSOConfig",
    "SamlConnection",
    "SamlConnectionInternal",
    "SamlConnectionMetadata",
    "SamlLoginEndpoint",
    "ScimBaseGroup",
    "ScimBaseUser",
    "ScimBaseUserName",
    "ScimGroup",
    "ScimGroupMember",
    "ScimGroupsListResponse",
    "ScimNewUser",
    "ScimPatchOperation",
    "ScimPatchRequest",
    "ScimResource",
    "ScimResourceTypesListResponse",
    "ScimSchemaResource",
    "ScimSchemasListResponse",
    "ScimServiceProviderConfigResponse",
    "ScimServiceProviderConfigResponseBulk",
    "ScimServiceProviderConfigResponseChangePassword",
    "ScimServiceProviderConfigResponseFilter",
    "ScimServiceProviderConfigResponsePatch",
    "ScimServiceProviderConfigResponseSort",
    "ScimUser",
    "ScimUsersListResponse",
    "SecondaryDeployment",
    "Session",
    "SessionCoupons",
    "SetDiscountEffectProps",
    "SetDiscountPerAdditionalCostEffectProps",
    "SetDiscountPerAdditionalCostPerItemEffectProps",
    "SetDiscountPerItemEffectProps",
    "SetLoyaltyPointsExpiryDateEffectProps",
    "ShowBundleMetadataEffectProps",
    "ShowNotificationEffectProps",
    "SkuUnitAnalytics",
    "SkuUnitAnalyticsDataPoint",
    "SlotDef",
    "Store",
    "StrikethroughChangedItem",
    "StrikethroughCustomEffectPerItemProps",
    "StrikethroughDebugResponse",
    "StrikethroughEffect",
    "StrikethroughLabelingNotification",
    "StrikethroughSetDiscountPerItemEffectProps",
    "StrikethroughSetDiscountPerItemMemberEffectProps",
    "StrikethroughTrigger",
    "SummarizeCampaignStoreBudget200Response",
    "SummaryCampaignStoreBudget",
    "TalangAttribute",
    "TalangAttributeVisibility",
    "TemplateArgDef",
    "TemplateDef",
    "TemplateLimitConfig",
    "Tier",
    "TierDowngradeData",
    "TierDowngradeNotification",
    "TierDowngradeNotificationPolicy",
    "TierUpgradeData",
    "TierUpgradeNotification",
    "TierUpgradeNotificationPolicy",
    "TierWillDowngradeData",
    "TierWillDowngradeNotification",
    "TierWillDowngradeNotificationPolicy",
    "TierWillDowngradeNotificationTrigger",
    "TimePoint",
    "TrackEventV2Response",
    "TransferLoyaltyCard",
    "TriggerWebhookEffectProps",
    "TwoFAConfig",
    "UpdateAccount",
    "UpdateAchievement",
    "UpdateApplication",
    "UpdateApplicationAPIKey",
    "UpdateApplicationCIF",
    "UpdateAttributeEffectProps",
    "UpdateAudience",
    "UpdateCampaign",
    "UpdateCampaignCollection",
    "UpdateCampaignEvaluationGroup",
    "UpdateCampaignGroup",
    "UpdateCampaignTemplate",
    "UpdateCatalog",
    "UpdateCollection",
    "UpdateCoupon",
    "UpdateCouponBatch",
    "UpdateCouponsData",
    "UpdateCustomEffect",
    "UpdateCustomerProfileV2409Response",
    "UpdateCustomerSessionV2409Response",
    "UpdateLoyaltyCard",
    "UpdateLoyaltyProgram",
    "UpdateLoyaltyProgramTier",
    "UpdatePicklist",
    "UpdatePriceType",
    "UpdateReferral",
    "UpdateReferralBatch",
    "UpdateRole",
    "UpdateStore",
    "UpdateUser",
    "User",
    "UserEntity",
    "ValueMap",
    "Webhook",
    "WebhookAuthentication",
    "WebhookAuthenticationBase",
    "WebhookAuthenticationDataBasic",
    "WebhookAuthenticationDataCustom",
    "WebhookAuthenticationWebhookRef",
    "WebhookWithOutgoingIntegrationDetails",
    "WillAwardGiveawayEffectProps",
]

# import apis into sdk package
from talon_one.api.integration_api import IntegrationApi as IntegrationApi
from talon_one.api.management_api import ManagementApi as ManagementApi

# import ApiClient
from talon_one.api_response import ApiResponse as ApiResponse
from talon_one.api_client import ApiClient as ApiClient
from talon_one.configuration import Configuration as Configuration
from talon_one.exceptions import OpenApiException as OpenApiException
from talon_one.exceptions import ApiTypeError as ApiTypeError
from talon_one.exceptions import ApiValueError as ApiValueError
from talon_one.exceptions import ApiKeyError as ApiKeyError
from talon_one.exceptions import ApiAttributeError as ApiAttributeError
from talon_one.exceptions import ApiException as ApiException

# import models into sdk package
from talon_one.models.api_error import APIError as APIError
from talon_one.models.accept_coupon_effect_props import AcceptCouponEffectProps as AcceptCouponEffectProps
from talon_one.models.accept_referral_effect_props import AcceptReferralEffectProps as AcceptReferralEffectProps
from talon_one.models.access_log_entry import AccessLogEntry as AccessLogEntry
from talon_one.models.account import Account as Account
from talon_one.models.account_additional_cost import AccountAdditionalCost as AccountAdditionalCost
from talon_one.models.account_analytics import AccountAnalytics as AccountAnalytics
from talon_one.models.account_dashboard_statistic import AccountDashboardStatistic as AccountDashboardStatistic
from talon_one.models.account_dashboard_statistic_campaigns import AccountDashboardStatisticCampaigns as AccountDashboardStatisticCampaigns
from talon_one.models.account_dashboard_statistic_discount import AccountDashboardStatisticDiscount as AccountDashboardStatisticDiscount
from talon_one.models.account_dashboard_statistic_loyalty_points import AccountDashboardStatisticLoyaltyPoints as AccountDashboardStatisticLoyaltyPoints
from talon_one.models.account_dashboard_statistic_referrals import AccountDashboardStatisticReferrals as AccountDashboardStatisticReferrals
from talon_one.models.account_dashboard_statistic_revenue import AccountDashboardStatisticRevenue as AccountDashboardStatisticRevenue
from talon_one.models.account_entity import AccountEntity as AccountEntity
from talon_one.models.account_limits import AccountLimits as AccountLimits
from talon_one.models.achievement import Achievement as Achievement
from talon_one.models.achievement_additional_properties import AchievementAdditionalProperties as AchievementAdditionalProperties
from talon_one.models.achievement_base import AchievementBase as AchievementBase
from talon_one.models.achievement_progress import AchievementProgress as AchievementProgress
from talon_one.models.achievement_progress_with_definition import AchievementProgressWithDefinition as AchievementProgressWithDefinition
from talon_one.models.achievement_status_entry import AchievementStatusEntry as AchievementStatusEntry
from talon_one.models.activate_loyalty_points import ActivateLoyaltyPoints as ActivateLoyaltyPoints
from talon_one.models.activate_loyalty_points_response import ActivateLoyaltyPointsResponse as ActivateLoyaltyPointsResponse
from talon_one.models.activate_user_request import ActivateUserRequest as ActivateUserRequest
from talon_one.models.add_free_item_effect_props import AddFreeItemEffectProps as AddFreeItemEffectProps
from talon_one.models.add_item_catalog_action import AddItemCatalogAction as AddItemCatalogAction
from talon_one.models.add_loyalty_points import AddLoyaltyPoints as AddLoyaltyPoints
from talon_one.models.add_loyalty_points_effect_props import AddLoyaltyPointsEffectProps as AddLoyaltyPointsEffectProps
from talon_one.models.add_price_adjustment_catalog_action import AddPriceAdjustmentCatalogAction as AddPriceAdjustmentCatalogAction
from talon_one.models.add_to_audience_effect_props import AddToAudienceEffectProps as AddToAudienceEffectProps
from talon_one.models.added_deducted_points_balances_action import AddedDeductedPointsBalancesAction as AddedDeductedPointsBalancesAction
from talon_one.models.added_deducted_points_balances_notification import AddedDeductedPointsBalancesNotification as AddedDeductedPointsBalancesNotification
from talon_one.models.added_deducted_points_balances_notification_policy import AddedDeductedPointsBalancesNotificationPolicy as AddedDeductedPointsBalancesNotificationPolicy
from talon_one.models.added_deducted_points_notification import AddedDeductedPointsNotification as AddedDeductedPointsNotification
from talon_one.models.added_deducted_points_notification_policy import AddedDeductedPointsNotificationPolicy as AddedDeductedPointsNotificationPolicy
from talon_one.models.additional_campaign_properties import AdditionalCampaignProperties as AdditionalCampaignProperties
from talon_one.models.additional_cost import AdditionalCost as AdditionalCost
from talon_one.models.analytics_data_point import AnalyticsDataPoint as AnalyticsDataPoint
from talon_one.models.analytics_data_point_with_trend import AnalyticsDataPointWithTrend as AnalyticsDataPointWithTrend
from talon_one.models.analytics_data_point_with_trend_and_influenced_rate import AnalyticsDataPointWithTrendAndInfluencedRate as AnalyticsDataPointWithTrendAndInfluencedRate
from talon_one.models.analytics_data_point_with_trend_and_uplift import AnalyticsDataPointWithTrendAndUplift as AnalyticsDataPointWithTrendAndUplift
from talon_one.models.analytics_product import AnalyticsProduct as AnalyticsProduct
from talon_one.models.analytics_sku import AnalyticsSKU as AnalyticsSKU
from talon_one.models.application import Application as Application
from talon_one.models.application_api_key import ApplicationAPIKey as ApplicationAPIKey
from talon_one.models.application_analytics_data_point import ApplicationAnalyticsDataPoint as ApplicationAnalyticsDataPoint
from talon_one.models.application_api_health import ApplicationApiHealth as ApplicationApiHealth
from talon_one.models.application_cif import ApplicationCIF as ApplicationCIF
from talon_one.models.application_cif_expression import ApplicationCIFExpression as ApplicationCIFExpression
from talon_one.models.application_cif_references import ApplicationCIFReferences as ApplicationCIFReferences
from talon_one.models.application_campaign_analytics import ApplicationCampaignAnalytics as ApplicationCampaignAnalytics
from talon_one.models.application_campaign_stats import ApplicationCampaignStats as ApplicationCampaignStats
from talon_one.models.application_customer import ApplicationCustomer as ApplicationCustomer
from talon_one.models.application_customer_entity import ApplicationCustomerEntity as ApplicationCustomerEntity
from talon_one.models.application_entity import ApplicationEntity as ApplicationEntity
from talon_one.models.application_event import ApplicationEvent as ApplicationEvent
from talon_one.models.application_notification import ApplicationNotification as ApplicationNotification
from talon_one.models.application_referee import ApplicationReferee as ApplicationReferee
from talon_one.models.application_session import ApplicationSession as ApplicationSession
from talon_one.models.application_session_entity import ApplicationSessionEntity as ApplicationSessionEntity
from talon_one.models.application_store_entity import ApplicationStoreEntity as ApplicationStoreEntity
from talon_one.models.async_coupon_creation_response import AsyncCouponCreationResponse as AsyncCouponCreationResponse
from talon_one.models.async_coupon_deletion_job_response import AsyncCouponDeletionJobResponse as AsyncCouponDeletionJobResponse
from talon_one.models.async_coupons_data import AsyncCouponsData as AsyncCouponsData
from talon_one.models.attribute import Attribute as Attribute
from talon_one.models.attributes_mandatory import AttributesMandatory as AttributesMandatory
from talon_one.models.attributes_settings import AttributesSettings as AttributesSettings
from talon_one.models.audience import Audience as Audience
from talon_one.models.audience_analytics import AudienceAnalytics as AudienceAnalytics
from talon_one.models.audience_customer import AudienceCustomer as AudienceCustomer
from talon_one.models.audience_integration_id import AudienceIntegrationID as AudienceIntegrationID
from talon_one.models.audience_membership import AudienceMembership as AudienceMembership
from talon_one.models.audience_reference import AudienceReference as AudienceReference
from talon_one.models.award_giveaway_effect_props import AwardGiveawayEffectProps as AwardGiveawayEffectProps
from talon_one.models.base_campaign import BaseCampaign as BaseCampaign
from talon_one.models.base_loyalty_program import BaseLoyaltyProgram as BaseLoyaltyProgram
from talon_one.models.base_notification import BaseNotification as BaseNotification
from talon_one.models.base_notification_entity import BaseNotificationEntity as BaseNotificationEntity
from talon_one.models.base_notification_webhook import BaseNotificationWebhook as BaseNotificationWebhook
from talon_one.models.base_notifications import BaseNotifications as BaseNotifications
from talon_one.models.base_saml_connection import BaseSamlConnection as BaseSamlConnection
from talon_one.models.best_prior_price import BestPriorPrice as BestPriorPrice
from talon_one.models.best_prior_price_metadata import BestPriorPriceMetadata as BestPriorPriceMetadata
from talon_one.models.best_prior_price_request import BestPriorPriceRequest as BestPriorPriceRequest
from talon_one.models.best_prior_price_request_target import BestPriorPriceRequestTarget as BestPriorPriceRequestTarget
from talon_one.models.binding import Binding as Binding
from talon_one.models.bulk_application_notification import BulkApplicationNotification as BulkApplicationNotification
from talon_one.models.bulk_operation_on_campaigns import BulkOperationOnCampaigns as BulkOperationOnCampaigns
from talon_one.models.campaign import Campaign as Campaign
from talon_one.models.campaign_activation_request import CampaignActivationRequest as CampaignActivationRequest
from talon_one.models.campaign_analytics import CampaignAnalytics as CampaignAnalytics
from talon_one.models.campaign_budget import CampaignBudget as CampaignBudget
from talon_one.models.campaign_collection import CampaignCollection as CampaignCollection
from talon_one.models.campaign_collection_edited_notification import CampaignCollectionEditedNotification as CampaignCollectionEditedNotification
from talon_one.models.campaign_collection_edited_notification_item import CampaignCollectionEditedNotificationItem as CampaignCollectionEditedNotificationItem
from talon_one.models.campaign_collection_without_payload import CampaignCollectionWithoutPayload as CampaignCollectionWithoutPayload
from talon_one.models.campaign_copy import CampaignCopy as CampaignCopy
from talon_one.models.campaign_created_notification import CampaignCreatedNotification as CampaignCreatedNotification
from talon_one.models.campaign_created_notification_item import CampaignCreatedNotificationItem as CampaignCreatedNotificationItem
from talon_one.models.campaign_deactivation_request import CampaignDeactivationRequest as CampaignDeactivationRequest
from talon_one.models.campaign_deleted_notification import CampaignDeletedNotification as CampaignDeletedNotification
from talon_one.models.campaign_deleted_notification_item import CampaignDeletedNotificationItem as CampaignDeletedNotificationItem
from talon_one.models.campaign_detail import CampaignDetail as CampaignDetail
from talon_one.models.campaign_edited_notification import CampaignEditedNotification as CampaignEditedNotification
from talon_one.models.campaign_edited_notification_item import CampaignEditedNotificationItem as CampaignEditedNotificationItem
from talon_one.models.campaign_entity import CampaignEntity as CampaignEntity
from talon_one.models.campaign_evaluation_group import CampaignEvaluationGroup as CampaignEvaluationGroup
from talon_one.models.campaign_evaluation_position import CampaignEvaluationPosition as CampaignEvaluationPosition
from talon_one.models.campaign_evaluation_tree_changed_message import CampaignEvaluationTreeChangedMessage as CampaignEvaluationTreeChangedMessage
from talon_one.models.campaign_evaluation_tree_changed_notification import CampaignEvaluationTreeChangedNotification as CampaignEvaluationTreeChangedNotification
from talon_one.models.campaign_group import CampaignGroup as CampaignGroup
from talon_one.models.campaign_group_entity import CampaignGroupEntity as CampaignGroupEntity
from talon_one.models.campaign_log_summary import CampaignLogSummary as CampaignLogSummary
from talon_one.models.campaign_notification_base import CampaignNotificationBase as CampaignNotificationBase
from talon_one.models.campaign_notification_generic import CampaignNotificationGeneric as CampaignNotificationGeneric
from talon_one.models.campaign_notification_item_base import CampaignNotificationItemBase as CampaignNotificationItemBase
from talon_one.models.campaign_notification_policy import CampaignNotificationPolicy as CampaignNotificationPolicy
from talon_one.models.campaign_ruleset_changed_notification import CampaignRulesetChangedNotification as CampaignRulesetChangedNotification
from talon_one.models.campaign_ruleset_changed_notification_item import CampaignRulesetChangedNotificationItem as CampaignRulesetChangedNotificationItem
from talon_one.models.campaign_search import CampaignSearch as CampaignSearch
from talon_one.models.campaign_set import CampaignSet as CampaignSet
from talon_one.models.campaign_set_branch_node import CampaignSetBranchNode as CampaignSetBranchNode
from talon_one.models.campaign_set_leaf_node import CampaignSetLeafNode as CampaignSetLeafNode
from talon_one.models.campaign_set_node import CampaignSetNode as CampaignSetNode
from talon_one.models.campaign_state_changed_notification import CampaignStateChangedNotification as CampaignStateChangedNotification
from talon_one.models.campaign_state_changed_notification_item import CampaignStateChangedNotificationItem as CampaignStateChangedNotificationItem
from talon_one.models.campaign_store_budget import CampaignStoreBudget as CampaignStoreBudget
from talon_one.models.campaign_store_budget_limit_config import CampaignStoreBudgetLimitConfig as CampaignStoreBudgetLimitConfig
from talon_one.models.campaign_template import CampaignTemplate as CampaignTemplate
from talon_one.models.campaign_template_collection import CampaignTemplateCollection as CampaignTemplateCollection
from talon_one.models.campaign_template_coupon_reservation_settings import CampaignTemplateCouponReservationSettings as CampaignTemplateCouponReservationSettings
from talon_one.models.campaign_template_params import CampaignTemplateParams as CampaignTemplateParams
from talon_one.models.campaign_versions import CampaignVersions as CampaignVersions
from talon_one.models.card_added_deducted_points_balances_notification import CardAddedDeductedPointsBalancesNotification as CardAddedDeductedPointsBalancesNotification
from talon_one.models.card_added_deducted_points_balances_notification_policy import CardAddedDeductedPointsBalancesNotificationPolicy as CardAddedDeductedPointsBalancesNotificationPolicy
from talon_one.models.card_added_deducted_points_notification import CardAddedDeductedPointsNotification as CardAddedDeductedPointsNotification
from talon_one.models.card_added_deducted_points_notification_policy import CardAddedDeductedPointsNotificationPolicy as CardAddedDeductedPointsNotificationPolicy
from talon_one.models.card_expiring_points_notification_policy import CardExpiringPointsNotificationPolicy as CardExpiringPointsNotificationPolicy
from talon_one.models.card_expiring_points_notification_trigger import CardExpiringPointsNotificationTrigger as CardExpiringPointsNotificationTrigger
from talon_one.models.card_ledger_points_entry_integration_api import CardLedgerPointsEntryIntegrationAPI as CardLedgerPointsEntryIntegrationAPI
from talon_one.models.card_ledger_transaction_log_entry import CardLedgerTransactionLogEntry as CardLedgerTransactionLogEntry
from talon_one.models.card_ledger_transaction_log_entry_integration_api import CardLedgerTransactionLogEntryIntegrationAPI as CardLedgerTransactionLogEntryIntegrationAPI
from talon_one.models.cart_item import CartItem as CartItem
from talon_one.models.catalog import Catalog as Catalog
from talon_one.models.catalog_action_filter import CatalogActionFilter as CatalogActionFilter
from talon_one.models.catalog_item import CatalogItem as CatalogItem
from talon_one.models.catalog_sync_request import CatalogSyncRequest as CatalogSyncRequest
from talon_one.models.catalogs_strikethrough_notification_policy import CatalogsStrikethroughNotificationPolicy as CatalogsStrikethroughNotificationPolicy
from talon_one.models.change import Change as Change
from talon_one.models.change_loyalty_tier_level_effect_props import ChangeLoyaltyTierLevelEffectProps as ChangeLoyaltyTierLevelEffectProps
from talon_one.models.change_profile_password import ChangeProfilePassword as ChangeProfilePassword
from talon_one.models.code_generator_settings import CodeGeneratorSettings as CodeGeneratorSettings
from talon_one.models.collection import Collection as Collection
from talon_one.models.collection_item import CollectionItem as CollectionItem
from talon_one.models.collection_without_payload import CollectionWithoutPayload as CollectionWithoutPayload
from talon_one.models.coupon import Coupon as Coupon
from talon_one.models.coupon_constraints import CouponConstraints as CouponConstraints
from talon_one.models.coupon_created_effect_props import CouponCreatedEffectProps as CouponCreatedEffectProps
from talon_one.models.coupon_creation_job import CouponCreationJob as CouponCreationJob
from talon_one.models.coupon_deletion_filters import CouponDeletionFilters as CouponDeletionFilters
from talon_one.models.coupon_deletion_job import CouponDeletionJob as CouponDeletionJob
from talon_one.models.coupon_entity import CouponEntity as CouponEntity
from talon_one.models.coupon_failure_summary import CouponFailureSummary as CouponFailureSummary
from talon_one.models.coupon_limit_configs import CouponLimitConfigs as CouponLimitConfigs
from talon_one.models.coupon_rejection_reason import CouponRejectionReason as CouponRejectionReason
from talon_one.models.coupon_rejections import CouponRejections as CouponRejections
from talon_one.models.coupon_reservations import CouponReservations as CouponReservations
from talon_one.models.coupon_search import CouponSearch as CouponSearch
from talon_one.models.coupon_value import CouponValue as CouponValue
from talon_one.models.coupons_notification_data import CouponsNotificationData as CouponsNotificationData
from talon_one.models.coupons_notification_policy import CouponsNotificationPolicy as CouponsNotificationPolicy
from talon_one.models.create_achievement import CreateAchievement as CreateAchievement
from talon_one.models.create_application_api_key import CreateApplicationAPIKey as CreateApplicationAPIKey
from talon_one.models.create_coupon_data import CreateCouponData as CreateCouponData
from talon_one.models.create_coupons200_response import CreateCoupons200Response as CreateCoupons200Response
from talon_one.models.create_management_key import CreateManagementKey as CreateManagementKey
from talon_one.models.create_referrals_for_multiple_advocates201_response import CreateReferralsForMultipleAdvocates201Response as CreateReferralsForMultipleAdvocates201Response
from talon_one.models.create_template_campaign import CreateTemplateCampaign as CreateTemplateCampaign
from talon_one.models.create_template_campaign_response import CreateTemplateCampaignResponse as CreateTemplateCampaignResponse
from talon_one.models.custom_effect import CustomEffect as CustomEffect
from talon_one.models.custom_effect_props import CustomEffectProps as CustomEffectProps
from talon_one.models.customer_activity_report import CustomerActivityReport as CustomerActivityReport
from talon_one.models.customer_analytics import CustomerAnalytics as CustomerAnalytics
from talon_one.models.customer_inventory import CustomerInventory as CustomerInventory
from talon_one.models.customer_profile import CustomerProfile as CustomerProfile
from talon_one.models.customer_profile_audience_request import CustomerProfileAudienceRequest as CustomerProfileAudienceRequest
from talon_one.models.customer_profile_audience_request_item import CustomerProfileAudienceRequestItem as CustomerProfileAudienceRequestItem
from talon_one.models.customer_profile_entity import CustomerProfileEntity as CustomerProfileEntity
from talon_one.models.customer_profile_integration_request_v2 import CustomerProfileIntegrationRequestV2 as CustomerProfileIntegrationRequestV2
from talon_one.models.customer_profile_integration_response_v2 import CustomerProfileIntegrationResponseV2 as CustomerProfileIntegrationResponseV2
from talon_one.models.customer_profile_search_query import CustomerProfileSearchQuery as CustomerProfileSearchQuery
from talon_one.models.customer_profile_update_v2_response import CustomerProfileUpdateV2Response as CustomerProfileUpdateV2Response
from talon_one.models.customer_session import CustomerSession as CustomerSession
from talon_one.models.customer_session_v2 import CustomerSessionV2 as CustomerSessionV2
from talon_one.models.deactivate_user_request import DeactivateUserRequest as DeactivateUserRequest
from talon_one.models.deduct_loyalty_points import DeductLoyaltyPoints as DeductLoyaltyPoints
from talon_one.models.deduct_loyalty_points_effect_props import DeductLoyaltyPointsEffectProps as DeductLoyaltyPointsEffectProps
from talon_one.models.delete_coupons_data import DeleteCouponsData as DeleteCouponsData
from talon_one.models.delete_user_request import DeleteUserRequest as DeleteUserRequest
from talon_one.models.effect import Effect as Effect
from talon_one.models.effect_entity import EffectEntity as EffectEntity
from talon_one.models.email_entity import EmailEntity as EmailEntity
from talon_one.models.endpoint import Endpoint as Endpoint
from talon_one.models.entity import Entity as Entity
from talon_one.models.entity_with_talang_visible_id import EntityWithTalangVisibleID as EntityWithTalangVisibleID
from talon_one.models.environment import Environment as Environment
from talon_one.models.error_effect_props import ErrorEffectProps as ErrorEffectProps
from talon_one.models.error_response import ErrorResponse as ErrorResponse
from talon_one.models.error_response_with_status import ErrorResponseWithStatus as ErrorResponseWithStatus
from talon_one.models.error_source import ErrorSource as ErrorSource
from talon_one.models.evaluable_campaign_ids import EvaluableCampaignIds as EvaluableCampaignIds
from talon_one.models.event import Event as Event
from talon_one.models.event_type import EventType as EventType
from talon_one.models.event_v2 import EventV2 as EventV2
from talon_one.models.event_v3 import EventV3 as EventV3
from talon_one.models.expiring_card_points_data import ExpiringCardPointsData as ExpiringCardPointsData
from talon_one.models.expiring_card_points_notification import ExpiringCardPointsNotification as ExpiringCardPointsNotification
from talon_one.models.expiring_coupons_data import ExpiringCouponsData as ExpiringCouponsData
from talon_one.models.expiring_coupons_notification import ExpiringCouponsNotification as ExpiringCouponsNotification
from talon_one.models.expiring_coupons_notification_policy import ExpiringCouponsNotificationPolicy as ExpiringCouponsNotificationPolicy
from talon_one.models.expiring_coupons_notification_trigger import ExpiringCouponsNotificationTrigger as ExpiringCouponsNotificationTrigger
from talon_one.models.expiring_points_data import ExpiringPointsData as ExpiringPointsData
from talon_one.models.expiring_points_notification import ExpiringPointsNotification as ExpiringPointsNotification
from talon_one.models.expiring_points_notification_policy import ExpiringPointsNotificationPolicy as ExpiringPointsNotificationPolicy
from talon_one.models.expiring_points_notification_trigger import ExpiringPointsNotificationTrigger as ExpiringPointsNotificationTrigger
from talon_one.models.export import Export as Export
from talon_one.models.extend_loyalty_points_expiry_date_effect_props import ExtendLoyaltyPointsExpiryDateEffectProps as ExtendLoyaltyPointsExpiryDateEffectProps
from talon_one.models.extended_coupon import ExtendedCoupon as ExtendedCoupon
from talon_one.models.feature_flag import FeatureFlag as FeatureFlag
from talon_one.models.features_feed import FeaturesFeed as FeaturesFeed
from talon_one.models.func_arg_def import FuncArgDef as FuncArgDef
from talon_one.models.function_def import FunctionDef as FunctionDef
from talon_one.models.generate_audit_log_summary import GenerateAuditLogSummary as GenerateAuditLogSummary
from talon_one.models.generate_campaign_description import GenerateCampaignDescription as GenerateCampaignDescription
from talon_one.models.generate_campaign_summary import GenerateCampaignSummary as GenerateCampaignSummary
from talon_one.models.generate_campaign_tags import GenerateCampaignTags as GenerateCampaignTags
from talon_one.models.generate_coupon_failure_detailed_summary import GenerateCouponFailureDetailedSummary as GenerateCouponFailureDetailedSummary
from talon_one.models.generate_coupon_failure_summary import GenerateCouponFailureSummary as GenerateCouponFailureSummary
from talon_one.models.generate_item_filter_description import GenerateItemFilterDescription as GenerateItemFilterDescription
from talon_one.models.generate_loyalty_card import GenerateLoyaltyCard as GenerateLoyaltyCard
from talon_one.models.generate_rule_title import GenerateRuleTitle as GenerateRuleTitle
from talon_one.models.generate_rule_title_rule import GenerateRuleTitleRule as GenerateRuleTitleRule
from talon_one.models.generate_user_session_summary import GenerateUserSessionSummary as GenerateUserSessionSummary
from talon_one.models.get_access_logs_without_total_count200_response import GetAccessLogsWithoutTotalCount200Response as GetAccessLogsWithoutTotalCount200Response
from talon_one.models.get_additional_costs200_response import GetAdditionalCosts200Response as GetAdditionalCosts200Response
from talon_one.models.get_application_customer_friends200_response import GetApplicationCustomerFriends200Response as GetApplicationCustomerFriends200Response
from talon_one.models.get_application_customers200_response import GetApplicationCustomers200Response as GetApplicationCustomers200Response
from talon_one.models.get_application_customers_by_attributes200_response import GetApplicationCustomersByAttributes200Response as GetApplicationCustomersByAttributes200Response
from talon_one.models.get_application_event_types200_response import GetApplicationEventTypes200Response as GetApplicationEventTypes200Response
from talon_one.models.get_application_events_without_total_count200_response import GetApplicationEventsWithoutTotalCount200Response as GetApplicationEventsWithoutTotalCount200Response
from talon_one.models.get_application_sessions200_response import GetApplicationSessions200Response as GetApplicationSessions200Response
from talon_one.models.get_applications200_response import GetApplications200Response as GetApplications200Response
from talon_one.models.get_attributes200_response import GetAttributes200Response as GetAttributes200Response
from talon_one.models.get_audience_memberships200_response import GetAudienceMemberships200Response as GetAudienceMemberships200Response
from talon_one.models.get_audiences200_response import GetAudiences200Response as GetAudiences200Response
from talon_one.models.get_audiences_analytics200_response import GetAudiencesAnalytics200Response as GetAudiencesAnalytics200Response
from talon_one.models.get_campaign_analytics200_response import GetCampaignAnalytics200Response as GetCampaignAnalytics200Response
from talon_one.models.get_campaign_groups200_response import GetCampaignGroups200Response as GetCampaignGroups200Response
from talon_one.models.get_campaign_templates200_response import GetCampaignTemplates200Response as GetCampaignTemplates200Response
from talon_one.models.get_campaigns200_response import GetCampaigns200Response as GetCampaigns200Response
from talon_one.models.get_changes200_response import GetChanges200Response as GetChanges200Response
from talon_one.models.get_collection_items200_response import GetCollectionItems200Response as GetCollectionItems200Response
from talon_one.models.get_coupons_without_total_count200_response import GetCouponsWithoutTotalCount200Response as GetCouponsWithoutTotalCount200Response
from talon_one.models.get_customer_achievement_history200_response import GetCustomerAchievementHistory200Response as GetCustomerAchievementHistory200Response
from talon_one.models.get_customer_achievements200_response import GetCustomerAchievements200Response as GetCustomerAchievements200Response
from talon_one.models.get_customer_activity_reports_without_total_count200_response import GetCustomerActivityReportsWithoutTotalCount200Response as GetCustomerActivityReportsWithoutTotalCount200Response
from talon_one.models.get_customer_profile_achievement_progress200_response import GetCustomerProfileAchievementProgress200Response as GetCustomerProfileAchievementProgress200Response
from talon_one.models.get_customer_profiles200_response import GetCustomerProfiles200Response as GetCustomerProfiles200Response
from talon_one.models.get_customers_by_attributes200_response import GetCustomersByAttributes200Response as GetCustomersByAttributes200Response
from talon_one.models.get_dashboard_statistics200_response import GetDashboardStatistics200Response as GetDashboardStatistics200Response
from talon_one.models.get_event_types200_response import GetEventTypes200Response as GetEventTypes200Response
from talon_one.models.get_exports200_response import GetExports200Response as GetExports200Response
from talon_one.models.get_integration_coupon_request import GetIntegrationCouponRequest as GetIntegrationCouponRequest
from talon_one.models.get_loyalty_card_points200_response import GetLoyaltyCardPoints200Response as GetLoyaltyCardPoints200Response
from talon_one.models.get_loyalty_card_transaction_logs200_response import GetLoyaltyCardTransactionLogs200Response as GetLoyaltyCardTransactionLogs200Response
from talon_one.models.get_loyalty_card_transactions200_response import GetLoyaltyCardTransactions200Response as GetLoyaltyCardTransactions200Response
from talon_one.models.get_loyalty_cards200_response import GetLoyaltyCards200Response as GetLoyaltyCards200Response
from talon_one.models.get_loyalty_program_profile_points200_response import GetLoyaltyProgramProfilePoints200Response as GetLoyaltyProgramProfilePoints200Response
from talon_one.models.get_loyalty_program_profile_transactions200_response import GetLoyaltyProgramProfileTransactions200Response as GetLoyaltyProgramProfileTransactions200Response
from talon_one.models.get_loyalty_program_transactions200_response import GetLoyaltyProgramTransactions200Response as GetLoyaltyProgramTransactions200Response
from talon_one.models.get_loyalty_programs200_response import GetLoyaltyPrograms200Response as GetLoyaltyPrograms200Response
from talon_one.models.get_referrals_without_total_count200_response import GetReferralsWithoutTotalCount200Response as GetReferralsWithoutTotalCount200Response
from talon_one.models.get_reserved_customers200_response import GetReservedCustomers200Response as GetReservedCustomers200Response
from talon_one.models.get_rulesets200_response import GetRulesets200Response as GetRulesets200Response
from talon_one.models.get_users200_response import GetUsers200Response as GetUsers200Response
from talon_one.models.get_webhooks200_response import GetWebhooks200Response as GetWebhooks200Response
from talon_one.models.giveaway import Giveaway as Giveaway
from talon_one.models.giveaways_pool import GiveawaysPool as GiveawaysPool
from talon_one.models.hidden_conditions_effects import HiddenConditionsEffects as HiddenConditionsEffects
from talon_one.models.identifiable_entity import IdentifiableEntity as IdentifiableEntity
from talon_one.models.import_entity import ImportEntity as ImportEntity
from talon_one.models.increase_achievement_progress_effect_props import IncreaseAchievementProgressEffectProps as IncreaseAchievementProgressEffectProps
from talon_one.models.integration_coupon import IntegrationCoupon as IntegrationCoupon
from talon_one.models.integration_customer_profile_audience_request import IntegrationCustomerProfileAudienceRequest as IntegrationCustomerProfileAudienceRequest
from talon_one.models.integration_customer_profile_audience_request_item import IntegrationCustomerProfileAudienceRequestItem as IntegrationCustomerProfileAudienceRequestItem
from talon_one.models.integration_customer_session_response import IntegrationCustomerSessionResponse as IntegrationCustomerSessionResponse
from talon_one.models.integration_entity import IntegrationEntity as IntegrationEntity
from talon_one.models.integration_event import IntegrationEvent as IntegrationEvent
from talon_one.models.integration_event_v2_request import IntegrationEventV2Request as IntegrationEventV2Request
from talon_one.models.integration_event_v3_request import IntegrationEventV3Request as IntegrationEventV3Request
from talon_one.models.integration_event_v3_response import IntegrationEventV3Response as IntegrationEventV3Response
from talon_one.models.integration_profile_entity import IntegrationProfileEntity as IntegrationProfileEntity
from talon_one.models.integration_profile_entity_v3 import IntegrationProfileEntityV3 as IntegrationProfileEntityV3
from talon_one.models.integration_request import IntegrationRequest as IntegrationRequest
from talon_one.models.integration_state import IntegrationState as IntegrationState
from talon_one.models.integration_state_v2 import IntegrationStateV2 as IntegrationStateV2
from talon_one.models.integration_store_entity import IntegrationStoreEntity as IntegrationStoreEntity
from talon_one.models.inventory_coupon import InventoryCoupon as InventoryCoupon
from talon_one.models.inventory_referral import InventoryReferral as InventoryReferral
from talon_one.models.item_attribute import ItemAttribute as ItemAttribute
from talon_one.models.label_target_audience import LabelTargetAudience as LabelTargetAudience
from talon_one.models.label_target_none import LabelTargetNone as LabelTargetNone
from talon_one.models.ledger_entry import LedgerEntry as LedgerEntry
from talon_one.models.ledger_info import LedgerInfo as LedgerInfo
from talon_one.models.ledger_points_entry_integration_api import LedgerPointsEntryIntegrationAPI as LedgerPointsEntryIntegrationAPI
from talon_one.models.ledger_transaction_log_entry_integration_api import LedgerTransactionLogEntryIntegrationAPI as LedgerTransactionLogEntryIntegrationAPI
from talon_one.models.library_attribute import LibraryAttribute as LibraryAttribute
from talon_one.models.limit_config import LimitConfig as LimitConfig
from talon_one.models.limit_counter import LimitCounter as LimitCounter
from talon_one.models.list_account_collections200_response import ListAccountCollections200Response as ListAccountCollections200Response
from talon_one.models.list_achievements200_response import ListAchievements200Response as ListAchievements200Response
from talon_one.models.list_all_roles_v2200_response import ListAllRolesV2200Response as ListAllRolesV2200Response
from talon_one.models.list_campaign_store_budget_limits200_response import ListCampaignStoreBudgetLimits200Response as ListCampaignStoreBudgetLimits200Response
from talon_one.models.list_campaign_store_budgets import ListCampaignStoreBudgets as ListCampaignStoreBudgets
from talon_one.models.list_campaign_store_budgets_store import ListCampaignStoreBudgetsStore as ListCampaignStoreBudgetsStore
from talon_one.models.list_catalog_items200_response import ListCatalogItems200Response as ListCatalogItems200Response
from talon_one.models.list_stores200_response import ListStores200Response as ListStores200Response
from talon_one.models.login_params import LoginParams as LoginParams
from talon_one.models.loyalty import Loyalty as Loyalty
from talon_one.models.loyalty_balance import LoyaltyBalance as LoyaltyBalance
from talon_one.models.loyalty_balance_with_tier import LoyaltyBalanceWithTier as LoyaltyBalanceWithTier
from talon_one.models.loyalty_balances import LoyaltyBalances as LoyaltyBalances
from talon_one.models.loyalty_balances_with_tiers import LoyaltyBalancesWithTiers as LoyaltyBalancesWithTiers
from talon_one.models.loyalty_card import LoyaltyCard as LoyaltyCard
from talon_one.models.loyalty_card_balances import LoyaltyCardBalances as LoyaltyCardBalances
from talon_one.models.loyalty_card_batch import LoyaltyCardBatch as LoyaltyCardBatch
from talon_one.models.loyalty_card_batch_response import LoyaltyCardBatchResponse as LoyaltyCardBatchResponse
from talon_one.models.loyalty_card_profile_registration import LoyaltyCardProfileRegistration as LoyaltyCardProfileRegistration
from talon_one.models.loyalty_card_registration import LoyaltyCardRegistration as LoyaltyCardRegistration
from talon_one.models.loyalty_dashboard_data import LoyaltyDashboardData as LoyaltyDashboardData
from talon_one.models.loyalty_dashboard_points_breakdown import LoyaltyDashboardPointsBreakdown as LoyaltyDashboardPointsBreakdown
from talon_one.models.loyalty_ledger import LoyaltyLedger as LoyaltyLedger
from talon_one.models.loyalty_ledger_entry import LoyaltyLedgerEntry as LoyaltyLedgerEntry
from talon_one.models.loyalty_ledger_entry_expiry_date_change import LoyaltyLedgerEntryExpiryDateChange as LoyaltyLedgerEntryExpiryDateChange
from talon_one.models.loyalty_ledger_entry_flags import LoyaltyLedgerEntryFlags as LoyaltyLedgerEntryFlags
from talon_one.models.loyalty_ledger_transactions import LoyaltyLedgerTransactions as LoyaltyLedgerTransactions
from talon_one.models.loyalty_membership import LoyaltyMembership as LoyaltyMembership
from talon_one.models.loyalty_program import LoyaltyProgram as LoyaltyProgram
from talon_one.models.loyalty_program_balance import LoyaltyProgramBalance as LoyaltyProgramBalance
from talon_one.models.loyalty_program_entity import LoyaltyProgramEntity as LoyaltyProgramEntity
from talon_one.models.loyalty_program_ledgers import LoyaltyProgramLedgers as LoyaltyProgramLedgers
from talon_one.models.loyalty_program_transaction import LoyaltyProgramTransaction as LoyaltyProgramTransaction
from talon_one.models.loyalty_sub_ledger import LoyaltySubLedger as LoyaltySubLedger
from talon_one.models.loyalty_tier import LoyaltyTier as LoyaltyTier
from talon_one.models.management_key import ManagementKey as ManagementKey
from talon_one.models.manager_config import ManagerConfig as ManagerConfig
from talon_one.models.message_log_entries import MessageLogEntries as MessageLogEntries
from talon_one.models.message_log_entry import MessageLogEntry as MessageLogEntry
from talon_one.models.message_log_request import MessageLogRequest as MessageLogRequest
from talon_one.models.message_log_response import MessageLogResponse as MessageLogResponse
from talon_one.models.message_test import MessageTest as MessageTest
from talon_one.models.meta import Meta as Meta
from talon_one.models.model_import import ModelImport as ModelImport
from talon_one.models.model_return import ModelReturn as ModelReturn
from talon_one.models.multi_application_entity import MultiApplicationEntity as MultiApplicationEntity
from talon_one.models.multiple_attribute import MultipleAttribute as MultipleAttribute
from talon_one.models.multiple_audiences import MultipleAudiences as MultipleAudiences
from talon_one.models.multiple_audiences_item import MultipleAudiencesItem as MultipleAudiencesItem
from talon_one.models.multiple_customer_profile_integration_request import MultipleCustomerProfileIntegrationRequest as MultipleCustomerProfileIntegrationRequest
from talon_one.models.multiple_customer_profile_integration_request_item import MultipleCustomerProfileIntegrationRequestItem as MultipleCustomerProfileIntegrationRequestItem
from talon_one.models.multiple_customer_profile_integration_response_v2 import MultipleCustomerProfileIntegrationResponseV2 as MultipleCustomerProfileIntegrationResponseV2
from talon_one.models.multiple_new_attribute import MultipleNewAttribute as MultipleNewAttribute
from talon_one.models.multiple_new_audiences import MultipleNewAudiences as MultipleNewAudiences
from talon_one.models.mutable_entity import MutableEntity as MutableEntity
from talon_one.models.new_account import NewAccount as NewAccount
from talon_one.models.new_account_sign_up import NewAccountSignUp as NewAccountSignUp
from talon_one.models.new_additional_cost import NewAdditionalCost as NewAdditionalCost
from talon_one.models.new_app_wide_coupon_deletion_job import NewAppWideCouponDeletionJob as NewAppWideCouponDeletionJob
from talon_one.models.new_application import NewApplication as NewApplication
from talon_one.models.new_application_api_key import NewApplicationAPIKey as NewApplicationAPIKey
from talon_one.models.new_application_cif import NewApplicationCIF as NewApplicationCIF
from talon_one.models.new_application_cif_expression import NewApplicationCIFExpression as NewApplicationCIFExpression
from talon_one.models.new_attribute import NewAttribute as NewAttribute
from talon_one.models.new_audience import NewAudience as NewAudience
from talon_one.models.new_base_notification import NewBaseNotification as NewBaseNotification
from talon_one.models.new_campaign import NewCampaign as NewCampaign
from talon_one.models.new_campaign_collection import NewCampaignCollection as NewCampaignCollection
from talon_one.models.new_campaign_evaluation_group import NewCampaignEvaluationGroup as NewCampaignEvaluationGroup
from talon_one.models.new_campaign_group import NewCampaignGroup as NewCampaignGroup
from talon_one.models.new_campaign_set import NewCampaignSet as NewCampaignSet
from talon_one.models.new_campaign_store_budget import NewCampaignStoreBudget as NewCampaignStoreBudget
from talon_one.models.new_campaign_store_budget_store_limit import NewCampaignStoreBudgetStoreLimit as NewCampaignStoreBudgetStoreLimit
from talon_one.models.new_campaign_template import NewCampaignTemplate as NewCampaignTemplate
from talon_one.models.new_catalog import NewCatalog as NewCatalog
from talon_one.models.new_collection import NewCollection as NewCollection
from talon_one.models.new_coupon_creation_job import NewCouponCreationJob as NewCouponCreationJob
from talon_one.models.new_coupon_deletion_job import NewCouponDeletionJob as NewCouponDeletionJob
from talon_one.models.new_coupons import NewCoupons as NewCoupons
from talon_one.models.new_coupons_for_multiple_recipients import NewCouponsForMultipleRecipients as NewCouponsForMultipleRecipients
from talon_one.models.new_custom_effect import NewCustomEffect as NewCustomEffect
from talon_one.models.new_customer_profile import NewCustomerProfile as NewCustomerProfile
from talon_one.models.new_customer_session import NewCustomerSession as NewCustomerSession
from talon_one.models.new_customer_session_v2 import NewCustomerSessionV2 as NewCustomerSessionV2
from talon_one.models.new_event import NewEvent as NewEvent
from talon_one.models.new_event_type import NewEventType as NewEventType
from talon_one.models.new_external_invitation import NewExternalInvitation as NewExternalInvitation
from talon_one.models.new_giveaways_pool import NewGiveawaysPool as NewGiveawaysPool
from talon_one.models.new_internal_audience import NewInternalAudience as NewInternalAudience
from talon_one.models.new_invitation import NewInvitation as NewInvitation
from talon_one.models.new_invite_email import NewInviteEmail as NewInviteEmail
from talon_one.models.new_loyalty_program import NewLoyaltyProgram as NewLoyaltyProgram
from talon_one.models.new_loyalty_tier import NewLoyaltyTier as NewLoyaltyTier
from talon_one.models.new_management_key import NewManagementKey as NewManagementKey
from talon_one.models.new_message_test import NewMessageTest as NewMessageTest
from talon_one.models.new_multiple_audiences_item import NewMultipleAudiencesItem as NewMultipleAudiencesItem
from talon_one.models.new_notification_webhook import NewNotificationWebhook as NewNotificationWebhook
from talon_one.models.new_outgoing_integration_webhook import NewOutgoingIntegrationWebhook as NewOutgoingIntegrationWebhook
from talon_one.models.new_password import NewPassword as NewPassword
from talon_one.models.new_password_email import NewPasswordEmail as NewPasswordEmail
from talon_one.models.new_picklist import NewPicklist as NewPicklist
from talon_one.models.new_price_adjustment import NewPriceAdjustment as NewPriceAdjustment
from talon_one.models.new_price_type import NewPriceType as NewPriceType
from talon_one.models.new_referral import NewReferral as NewReferral
from talon_one.models.new_referrals_for_multiple_advocates import NewReferralsForMultipleAdvocates as NewReferralsForMultipleAdvocates
from talon_one.models.new_return import NewReturn as NewReturn
from talon_one.models.new_revision_version import NewRevisionVersion as NewRevisionVersion
from talon_one.models.new_role import NewRole as NewRole
from talon_one.models.new_role_v2 import NewRoleV2 as NewRoleV2
from talon_one.models.new_ruleset import NewRuleset as NewRuleset
from talon_one.models.new_saml_connection import NewSamlConnection as NewSamlConnection
from talon_one.models.new_secondary_deployment import NewSecondaryDeployment as NewSecondaryDeployment
from talon_one.models.new_store import NewStore as NewStore
from talon_one.models.new_template_def import NewTemplateDef as NewTemplateDef
from talon_one.models.new_user import NewUser as NewUser
from talon_one.models.new_webhook import NewWebhook as NewWebhook
from talon_one.models.notification import Notification as Notification
from talon_one.models.notification_activation import NotificationActivation as NotificationActivation
from talon_one.models.notification_list_item import NotificationListItem as NotificationListItem
from talon_one.models.okta_event import OktaEvent as OktaEvent
from talon_one.models.okta_event_payload import OktaEventPayload as OktaEventPayload
from talon_one.models.okta_event_payload_data import OktaEventPayloadData as OktaEventPayloadData
from talon_one.models.okta_event_target import OktaEventTarget as OktaEventTarget
from talon_one.models.one_time_code import OneTimeCode as OneTimeCode
from talon_one.models.outgoing_integration_braze_policy import OutgoingIntegrationBrazePolicy as OutgoingIntegrationBrazePolicy
from talon_one.models.outgoing_integration_clever_tap_policy import OutgoingIntegrationCleverTapPolicy as OutgoingIntegrationCleverTapPolicy
from talon_one.models.outgoing_integration_configuration import OutgoingIntegrationConfiguration as OutgoingIntegrationConfiguration
from talon_one.models.outgoing_integration_iterable_policy import OutgoingIntegrationIterablePolicy as OutgoingIntegrationIterablePolicy
from talon_one.models.outgoing_integration_mo_engage_policy import OutgoingIntegrationMoEngagePolicy as OutgoingIntegrationMoEngagePolicy
from talon_one.models.outgoing_integration_template import OutgoingIntegrationTemplate as OutgoingIntegrationTemplate
from talon_one.models.outgoing_integration_template_with_configuration_details import OutgoingIntegrationTemplateWithConfigurationDetails as OutgoingIntegrationTemplateWithConfigurationDetails
from talon_one.models.outgoing_integration_templates import OutgoingIntegrationTemplates as OutgoingIntegrationTemplates
from talon_one.models.outgoing_integration_type import OutgoingIntegrationType as OutgoingIntegrationType
from talon_one.models.outgoing_integration_types import OutgoingIntegrationTypes as OutgoingIntegrationTypes
from talon_one.models.patch_item_catalog_action import PatchItemCatalogAction as PatchItemCatalogAction
from talon_one.models.patch_many_items_catalog_action import PatchManyItemsCatalogAction as PatchManyItemsCatalogAction
from talon_one.models.pending_active_points_data import PendingActivePointsData as PendingActivePointsData
from talon_one.models.pending_active_points_notification import PendingActivePointsNotification as PendingActivePointsNotification
from talon_one.models.pending_points_notification_policy import PendingPointsNotificationPolicy as PendingPointsNotificationPolicy
from talon_one.models.picklist import Picklist as Picklist
from talon_one.models.price_detail import PriceDetail as PriceDetail
from talon_one.models.price_type import PriceType as PriceType
from talon_one.models.price_type_reference_detail import PriceTypeReferenceDetail as PriceTypeReferenceDetail
from talon_one.models.price_type_references import PriceTypeReferences as PriceTypeReferences
from talon_one.models.prismatic_config import PrismaticConfig as PrismaticConfig
from talon_one.models.prismatic_event_payload_coupon_based_notifications import PrismaticEventPayloadCouponBasedNotifications as PrismaticEventPayloadCouponBasedNotifications
from talon_one.models.prismatic_event_payload_coupon_based_notifications_limits import PrismaticEventPayloadCouponBasedNotificationsLimits as PrismaticEventPayloadCouponBasedNotificationsLimits
from talon_one.models.prismatic_event_payload_loyalty_profile_based_notifications import PrismaticEventPayloadLoyaltyProfileBasedNotifications as PrismaticEventPayloadLoyaltyProfileBasedNotifications
from talon_one.models.prismatic_event_payload_loyalty_profile_based_notifications_action import PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction as PrismaticEventPayloadLoyaltyProfileBasedNotificationsAction
from talon_one.models.prismatic_flow import PrismaticFlow as PrismaticFlow
from talon_one.models.prismatic_flow_config import PrismaticFlowConfig as PrismaticFlowConfig
from talon_one.models.prismatic_flow_with_config import PrismaticFlowWithConfig as PrismaticFlowWithConfig
from talon_one.models.prismatic_paginated_event_payload import PrismaticPaginatedEventPayload as PrismaticPaginatedEventPayload
from talon_one.models.product import Product as Product
from talon_one.models.product_search_match import ProductSearchMatch as ProductSearchMatch
from talon_one.models.product_unit_analytics import ProductUnitAnalytics as ProductUnitAnalytics
from talon_one.models.product_unit_analytics_data_point import ProductUnitAnalyticsDataPoint as ProductUnitAnalyticsDataPoint
from talon_one.models.product_unit_analytics_totals import ProductUnitAnalyticsTotals as ProductUnitAnalyticsTotals
from talon_one.models.profile_audiences_changes import ProfileAudiencesChanges as ProfileAudiencesChanges
from talon_one.models.projected_tier import ProjectedTier as ProjectedTier
from talon_one.models.redeem_referral_effect_props import RedeemReferralEffectProps as RedeemReferralEffectProps
from talon_one.models.referral import Referral as Referral
from talon_one.models.referral_constraints import ReferralConstraints as ReferralConstraints
from talon_one.models.referral_created_effect_props import ReferralCreatedEffectProps as ReferralCreatedEffectProps
from talon_one.models.referral_rejection_reason import ReferralRejectionReason as ReferralRejectionReason
from talon_one.models.reject_coupon_effect_props import RejectCouponEffectProps as RejectCouponEffectProps
from talon_one.models.reject_referral_effect_props import RejectReferralEffectProps as RejectReferralEffectProps
from talon_one.models.remove_from_audience_effect_props import RemoveFromAudienceEffectProps as RemoveFromAudienceEffectProps
from talon_one.models.remove_item_catalog_action import RemoveItemCatalogAction as RemoveItemCatalogAction
from talon_one.models.remove_many_items_catalog_action import RemoveManyItemsCatalogAction as RemoveManyItemsCatalogAction
from talon_one.models.reopen_session_response import ReopenSessionResponse as ReopenSessionResponse
from talon_one.models.reserve_coupon_effect_props import ReserveCouponEffectProps as ReserveCouponEffectProps
from talon_one.models.return_integration_request import ReturnIntegrationRequest as ReturnIntegrationRequest
from talon_one.models.returned_cart_item import ReturnedCartItem as ReturnedCartItem
from talon_one.models.revision import Revision as Revision
from talon_one.models.revision_activation import RevisionActivation as RevisionActivation
from talon_one.models.revision_activation_request import RevisionActivationRequest as RevisionActivationRequest
from talon_one.models.revision_version import RevisionVersion as RevisionVersion
from talon_one.models.role import Role as Role
from talon_one.models.role_assign import RoleAssign as RoleAssign
from talon_one.models.role_membership import RoleMembership as RoleMembership
from talon_one.models.role_v2 import RoleV2 as RoleV2
from talon_one.models.role_v2_application_details import RoleV2ApplicationDetails as RoleV2ApplicationDetails
from talon_one.models.role_v2_base import RoleV2Base as RoleV2Base
from talon_one.models.role_v2_permission_set import RoleV2PermissionSet as RoleV2PermissionSet
from talon_one.models.role_v2_permissions import RoleV2Permissions as RoleV2Permissions
from talon_one.models.role_v2_readonly import RoleV2Readonly as RoleV2Readonly
from talon_one.models.role_v2_roles_group import RoleV2RolesGroup as RoleV2RolesGroup
from talon_one.models.rollback_added_loyalty_points_effect_props import RollbackAddedLoyaltyPointsEffectProps as RollbackAddedLoyaltyPointsEffectProps
from talon_one.models.rollback_coupon_effect_props import RollbackCouponEffectProps as RollbackCouponEffectProps
from talon_one.models.rollback_deducted_loyalty_points_effect_props import RollbackDeductedLoyaltyPointsEffectProps as RollbackDeductedLoyaltyPointsEffectProps
from talon_one.models.rollback_discount_effect_props import RollbackDiscountEffectProps as RollbackDiscountEffectProps
from talon_one.models.rollback_increased_achievement_progress_effect_props import RollbackIncreasedAchievementProgressEffectProps as RollbackIncreasedAchievementProgressEffectProps
from talon_one.models.rollback_referral_effect_props import RollbackReferralEffectProps as RollbackReferralEffectProps
from talon_one.models.rule import Rule as Rule
from talon_one.models.rule_failure_reason import RuleFailureReason as RuleFailureReason
from talon_one.models.ruleset import Ruleset as Ruleset
from talon_one.models.sso_config import SSOConfig as SSOConfig
from talon_one.models.saml_connection import SamlConnection as SamlConnection
from talon_one.models.saml_connection_internal import SamlConnectionInternal as SamlConnectionInternal
from talon_one.models.saml_connection_metadata import SamlConnectionMetadata as SamlConnectionMetadata
from talon_one.models.saml_login_endpoint import SamlLoginEndpoint as SamlLoginEndpoint
from talon_one.models.scim_base_group import ScimBaseGroup as ScimBaseGroup
from talon_one.models.scim_base_user import ScimBaseUser as ScimBaseUser
from talon_one.models.scim_base_user_name import ScimBaseUserName as ScimBaseUserName
from talon_one.models.scim_group import ScimGroup as ScimGroup
from talon_one.models.scim_group_member import ScimGroupMember as ScimGroupMember
from talon_one.models.scim_groups_list_response import ScimGroupsListResponse as ScimGroupsListResponse
from talon_one.models.scim_new_user import ScimNewUser as ScimNewUser
from talon_one.models.scim_patch_operation import ScimPatchOperation as ScimPatchOperation
from talon_one.models.scim_patch_request import ScimPatchRequest as ScimPatchRequest
from talon_one.models.scim_resource import ScimResource as ScimResource
from talon_one.models.scim_resource_types_list_response import ScimResourceTypesListResponse as ScimResourceTypesListResponse
from talon_one.models.scim_schema_resource import ScimSchemaResource as ScimSchemaResource
from talon_one.models.scim_schemas_list_response import ScimSchemasListResponse as ScimSchemasListResponse
from talon_one.models.scim_service_provider_config_response import ScimServiceProviderConfigResponse as ScimServiceProviderConfigResponse
from talon_one.models.scim_service_provider_config_response_bulk import ScimServiceProviderConfigResponseBulk as ScimServiceProviderConfigResponseBulk
from talon_one.models.scim_service_provider_config_response_change_password import ScimServiceProviderConfigResponseChangePassword as ScimServiceProviderConfigResponseChangePassword
from talon_one.models.scim_service_provider_config_response_filter import ScimServiceProviderConfigResponseFilter as ScimServiceProviderConfigResponseFilter
from talon_one.models.scim_service_provider_config_response_patch import ScimServiceProviderConfigResponsePatch as ScimServiceProviderConfigResponsePatch
from talon_one.models.scim_service_provider_config_response_sort import ScimServiceProviderConfigResponseSort as ScimServiceProviderConfigResponseSort
from talon_one.models.scim_user import ScimUser as ScimUser
from talon_one.models.scim_users_list_response import ScimUsersListResponse as ScimUsersListResponse
from talon_one.models.secondary_deployment import SecondaryDeployment as SecondaryDeployment
from talon_one.models.session import Session as Session
from talon_one.models.session_coupons import SessionCoupons as SessionCoupons
from talon_one.models.set_discount_effect_props import SetDiscountEffectProps as SetDiscountEffectProps
from talon_one.models.set_discount_per_additional_cost_effect_props import SetDiscountPerAdditionalCostEffectProps as SetDiscountPerAdditionalCostEffectProps
from talon_one.models.set_discount_per_additional_cost_per_item_effect_props import SetDiscountPerAdditionalCostPerItemEffectProps as SetDiscountPerAdditionalCostPerItemEffectProps
from talon_one.models.set_discount_per_item_effect_props import SetDiscountPerItemEffectProps as SetDiscountPerItemEffectProps
from talon_one.models.set_loyalty_points_expiry_date_effect_props import SetLoyaltyPointsExpiryDateEffectProps as SetLoyaltyPointsExpiryDateEffectProps
from talon_one.models.show_bundle_metadata_effect_props import ShowBundleMetadataEffectProps as ShowBundleMetadataEffectProps
from talon_one.models.show_notification_effect_props import ShowNotificationEffectProps as ShowNotificationEffectProps
from talon_one.models.sku_unit_analytics import SkuUnitAnalytics as SkuUnitAnalytics
from talon_one.models.sku_unit_analytics_data_point import SkuUnitAnalyticsDataPoint as SkuUnitAnalyticsDataPoint
from talon_one.models.slot_def import SlotDef as SlotDef
from talon_one.models.store import Store as Store
from talon_one.models.strikethrough_changed_item import StrikethroughChangedItem as StrikethroughChangedItem
from talon_one.models.strikethrough_custom_effect_per_item_props import StrikethroughCustomEffectPerItemProps as StrikethroughCustomEffectPerItemProps
from talon_one.models.strikethrough_debug_response import StrikethroughDebugResponse as StrikethroughDebugResponse
from talon_one.models.strikethrough_effect import StrikethroughEffect as StrikethroughEffect
from talon_one.models.strikethrough_labeling_notification import StrikethroughLabelingNotification as StrikethroughLabelingNotification
from talon_one.models.strikethrough_set_discount_per_item_effect_props import StrikethroughSetDiscountPerItemEffectProps as StrikethroughSetDiscountPerItemEffectProps
from talon_one.models.strikethrough_set_discount_per_item_member_effect_props import StrikethroughSetDiscountPerItemMemberEffectProps as StrikethroughSetDiscountPerItemMemberEffectProps
from talon_one.models.strikethrough_trigger import StrikethroughTrigger as StrikethroughTrigger
from talon_one.models.summarize_campaign_store_budget200_response import SummarizeCampaignStoreBudget200Response as SummarizeCampaignStoreBudget200Response
from talon_one.models.summary_campaign_store_budget import SummaryCampaignStoreBudget as SummaryCampaignStoreBudget
from talon_one.models.talang_attribute import TalangAttribute as TalangAttribute
from talon_one.models.talang_attribute_visibility import TalangAttributeVisibility as TalangAttributeVisibility
from talon_one.models.template_arg_def import TemplateArgDef as TemplateArgDef
from talon_one.models.template_def import TemplateDef as TemplateDef
from talon_one.models.template_limit_config import TemplateLimitConfig as TemplateLimitConfig
from talon_one.models.tier import Tier as Tier
from talon_one.models.tier_downgrade_data import TierDowngradeData as TierDowngradeData
from talon_one.models.tier_downgrade_notification import TierDowngradeNotification as TierDowngradeNotification
from talon_one.models.tier_downgrade_notification_policy import TierDowngradeNotificationPolicy as TierDowngradeNotificationPolicy
from talon_one.models.tier_upgrade_data import TierUpgradeData as TierUpgradeData
from talon_one.models.tier_upgrade_notification import TierUpgradeNotification as TierUpgradeNotification
from talon_one.models.tier_upgrade_notification_policy import TierUpgradeNotificationPolicy as TierUpgradeNotificationPolicy
from talon_one.models.tier_will_downgrade_data import TierWillDowngradeData as TierWillDowngradeData
from talon_one.models.tier_will_downgrade_notification import TierWillDowngradeNotification as TierWillDowngradeNotification
from talon_one.models.tier_will_downgrade_notification_policy import TierWillDowngradeNotificationPolicy as TierWillDowngradeNotificationPolicy
from talon_one.models.tier_will_downgrade_notification_trigger import TierWillDowngradeNotificationTrigger as TierWillDowngradeNotificationTrigger
from talon_one.models.time_point import TimePoint as TimePoint
from talon_one.models.track_event_v2_response import TrackEventV2Response as TrackEventV2Response
from talon_one.models.transfer_loyalty_card import TransferLoyaltyCard as TransferLoyaltyCard
from talon_one.models.trigger_webhook_effect_props import TriggerWebhookEffectProps as TriggerWebhookEffectProps
from talon_one.models.two_fa_config import TwoFAConfig as TwoFAConfig
from talon_one.models.update_account import UpdateAccount as UpdateAccount
from talon_one.models.update_achievement import UpdateAchievement as UpdateAchievement
from talon_one.models.update_application import UpdateApplication as UpdateApplication
from talon_one.models.update_application_api_key import UpdateApplicationAPIKey as UpdateApplicationAPIKey
from talon_one.models.update_application_cif import UpdateApplicationCIF as UpdateApplicationCIF
from talon_one.models.update_attribute_effect_props import UpdateAttributeEffectProps as UpdateAttributeEffectProps
from talon_one.models.update_audience import UpdateAudience as UpdateAudience
from talon_one.models.update_campaign import UpdateCampaign as UpdateCampaign
from talon_one.models.update_campaign_collection import UpdateCampaignCollection as UpdateCampaignCollection
from talon_one.models.update_campaign_evaluation_group import UpdateCampaignEvaluationGroup as UpdateCampaignEvaluationGroup
from talon_one.models.update_campaign_group import UpdateCampaignGroup as UpdateCampaignGroup
from talon_one.models.update_campaign_template import UpdateCampaignTemplate as UpdateCampaignTemplate
from talon_one.models.update_catalog import UpdateCatalog as UpdateCatalog
from talon_one.models.update_collection import UpdateCollection as UpdateCollection
from talon_one.models.update_coupon import UpdateCoupon as UpdateCoupon
from talon_one.models.update_coupon_batch import UpdateCouponBatch as UpdateCouponBatch
from talon_one.models.update_coupons_data import UpdateCouponsData as UpdateCouponsData
from talon_one.models.update_custom_effect import UpdateCustomEffect as UpdateCustomEffect
from talon_one.models.update_customer_profile_v2409_response import UpdateCustomerProfileV2409Response as UpdateCustomerProfileV2409Response
from talon_one.models.update_customer_session_v2409_response import UpdateCustomerSessionV2409Response as UpdateCustomerSessionV2409Response
from talon_one.models.update_loyalty_card import UpdateLoyaltyCard as UpdateLoyaltyCard
from talon_one.models.update_loyalty_program import UpdateLoyaltyProgram as UpdateLoyaltyProgram
from talon_one.models.update_loyalty_program_tier import UpdateLoyaltyProgramTier as UpdateLoyaltyProgramTier
from talon_one.models.update_picklist import UpdatePicklist as UpdatePicklist
from talon_one.models.update_price_type import UpdatePriceType as UpdatePriceType
from talon_one.models.update_referral import UpdateReferral as UpdateReferral
from talon_one.models.update_referral_batch import UpdateReferralBatch as UpdateReferralBatch
from talon_one.models.update_role import UpdateRole as UpdateRole
from talon_one.models.update_store import UpdateStore as UpdateStore
from talon_one.models.update_user import UpdateUser as UpdateUser
from talon_one.models.user import User as User
from talon_one.models.user_entity import UserEntity as UserEntity
from talon_one.models.value_map import ValueMap as ValueMap
from talon_one.models.webhook import Webhook as Webhook
from talon_one.models.webhook_authentication import WebhookAuthentication as WebhookAuthentication
from talon_one.models.webhook_authentication_base import WebhookAuthenticationBase as WebhookAuthenticationBase
from talon_one.models.webhook_authentication_data_basic import WebhookAuthenticationDataBasic as WebhookAuthenticationDataBasic
from talon_one.models.webhook_authentication_data_custom import WebhookAuthenticationDataCustom as WebhookAuthenticationDataCustom
from talon_one.models.webhook_authentication_webhook_ref import WebhookAuthenticationWebhookRef as WebhookAuthenticationWebhookRef
from talon_one.models.webhook_with_outgoing_integration_details import WebhookWithOutgoingIntegrationDetails as WebhookWithOutgoingIntegrationDetails
from talon_one.models.will_award_giveaway_effect_props import WillAwardGiveawayEffectProps as WillAwardGiveawayEffectProps

