# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from talon_one.models.award_discount_additional_cost_target import AwardDiscountAdditionalCostTarget
from talon_one.models.award_discount_all_items_target import AwardDiscountAllItemsTarget
from talon_one.models.award_discount_bundle_target import AwardDiscountBundleTarget
from talon_one.models.award_discount_cart_target import AwardDiscountCartTarget
from talon_one.models.award_discount_global_filter_target import AwardDiscountGlobalFilterTarget
from talon_one.models.award_discount_selector_target import AwardDiscountSelectorTarget
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

AWARDDISCOUNTTARGET_ONE_OF_SCHEMAS = ["AwardDiscountAdditionalCostTarget", "AwardDiscountAllItemsTarget", "AwardDiscountBundleTarget", "AwardDiscountCartTarget", "AwardDiscountGlobalFilterTarget", "AwardDiscountSelectorTarget"]

class AwardDiscountTarget(BaseModel):
    """
    Identifies the scope a discount applies to. The `type` field selects the concrete target variant.
    """
    # data type: AwardDiscountCartTarget
    oneof_schema_1_validator: Optional[AwardDiscountCartTarget] = None
    # data type: AwardDiscountAllItemsTarget
    oneof_schema_2_validator: Optional[AwardDiscountAllItemsTarget] = None
    # data type: AwardDiscountGlobalFilterTarget
    oneof_schema_3_validator: Optional[AwardDiscountGlobalFilterTarget] = None
    # data type: AwardDiscountSelectorTarget
    oneof_schema_4_validator: Optional[AwardDiscountSelectorTarget] = None
    # data type: AwardDiscountBundleTarget
    oneof_schema_5_validator: Optional[AwardDiscountBundleTarget] = None
    # data type: AwardDiscountAdditionalCostTarget
    oneof_schema_6_validator: Optional[AwardDiscountAdditionalCostTarget] = None
    actual_instance: Optional[Union[AwardDiscountAdditionalCostTarget, AwardDiscountAllItemsTarget, AwardDiscountBundleTarget, AwardDiscountCartTarget, AwardDiscountGlobalFilterTarget, AwardDiscountSelectorTarget]] = None
    one_of_schemas: Set[str] = { "AwardDiscountAdditionalCostTarget", "AwardDiscountAllItemsTarget", "AwardDiscountBundleTarget", "AwardDiscountCartTarget", "AwardDiscountGlobalFilterTarget", "AwardDiscountSelectorTarget" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = AwardDiscountTarget.model_construct()
        error_messages = []
        match = 0
        # validate data type: AwardDiscountCartTarget
        if not isinstance(v, AwardDiscountCartTarget):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AwardDiscountCartTarget`")
        else:
            match += 1
        # validate data type: AwardDiscountAllItemsTarget
        if not isinstance(v, AwardDiscountAllItemsTarget):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AwardDiscountAllItemsTarget`")
        else:
            match += 1
        # validate data type: AwardDiscountGlobalFilterTarget
        if not isinstance(v, AwardDiscountGlobalFilterTarget):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AwardDiscountGlobalFilterTarget`")
        else:
            match += 1
        # validate data type: AwardDiscountSelectorTarget
        if not isinstance(v, AwardDiscountSelectorTarget):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AwardDiscountSelectorTarget`")
        else:
            match += 1
        # validate data type: AwardDiscountBundleTarget
        if not isinstance(v, AwardDiscountBundleTarget):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AwardDiscountBundleTarget`")
        else:
            match += 1
        # validate data type: AwardDiscountAdditionalCostTarget
        if not isinstance(v, AwardDiscountAdditionalCostTarget):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AwardDiscountAdditionalCostTarget`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in AwardDiscountTarget with oneOf schemas: AwardDiscountAdditionalCostTarget, AwardDiscountAllItemsTarget, AwardDiscountBundleTarget, AwardDiscountCartTarget, AwardDiscountGlobalFilterTarget, AwardDiscountSelectorTarget. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in AwardDiscountTarget with oneOf schemas: AwardDiscountAdditionalCostTarget, AwardDiscountAllItemsTarget, AwardDiscountBundleTarget, AwardDiscountCartTarget, AwardDiscountGlobalFilterTarget, AwardDiscountSelectorTarget. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into AwardDiscountCartTarget
        try:
            instance.actual_instance = AwardDiscountCartTarget.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AwardDiscountAllItemsTarget
        try:
            instance.actual_instance = AwardDiscountAllItemsTarget.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AwardDiscountGlobalFilterTarget
        try:
            instance.actual_instance = AwardDiscountGlobalFilterTarget.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AwardDiscountSelectorTarget
        try:
            instance.actual_instance = AwardDiscountSelectorTarget.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AwardDiscountBundleTarget
        try:
            instance.actual_instance = AwardDiscountBundleTarget.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AwardDiscountAdditionalCostTarget
        try:
            instance.actual_instance = AwardDiscountAdditionalCostTarget.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into AwardDiscountTarget with oneOf schemas: AwardDiscountAdditionalCostTarget, AwardDiscountAllItemsTarget, AwardDiscountBundleTarget, AwardDiscountCartTarget, AwardDiscountGlobalFilterTarget, AwardDiscountSelectorTarget. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into AwardDiscountTarget with oneOf schemas: AwardDiscountAdditionalCostTarget, AwardDiscountAllItemsTarget, AwardDiscountBundleTarget, AwardDiscountCartTarget, AwardDiscountGlobalFilterTarget, AwardDiscountSelectorTarget. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AwardDiscountAdditionalCostTarget, AwardDiscountAllItemsTarget, AwardDiscountBundleTarget, AwardDiscountCartTarget, AwardDiscountGlobalFilterTarget, AwardDiscountSelectorTarget]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


