# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from talon_one.models.campaign_budget import CampaignBudget
from talon_one.models.code_generator_settings import CodeGeneratorSettings
from talon_one.models.limit_config import LimitConfig
from typing import Optional, Set
from typing_extensions import Self

class Campaign(BaseModel):
    """
    Campaign
    """ # noqa: E501
    id: StrictInt = Field(description="Unique ID for this entity.")
    created: datetime = Field(description="The exact moment this entity was created.")
    application_id: StrictInt = Field(description="The ID of the Application that owns this entity.", alias="applicationId")
    user_id: StrictInt = Field(description="The ID of the user associated with this entity.", alias="userId")
    name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="A user-facing name for this campaign.")
    description: Optional[StrictStr] = Field(default=None, description="A detailed description of the campaign.")
    start_time: Optional[datetime] = Field(default=None, description="Timestamp when the campaign will become active.", alias="startTime")
    end_time: Optional[datetime] = Field(default=None, description="Timestamp when the campaign will become inactive.", alias="endTime")
    attributes: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary properties associated with this campaign.")
    state: StrictStr = Field(description="A disabled or archived campaign is not evaluated for rules or coupons. ")
    active_ruleset_id: Optional[StrictInt] = Field(default=None, description="[ID of Ruleset](https://docs.talon.one/management-api#operation/getRulesets) this campaign applies on customer session evaluation. ", alias="activeRulesetId")
    tags: Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=50)]], Field(max_length=50)] = Field(description="A list of tags for the campaign.")
    reevaluate_on_return: StrictBool = Field(description="Indicates whether this campaign should be reevaluated when a customer returns an item.", alias="reevaluateOnReturn")
    features: List[StrictStr] = Field(description="The features enabled in this campaign.")
    coupon_settings: Optional[CodeGeneratorSettings] = Field(default=None, alias="couponSettings")
    referral_settings: Optional[CodeGeneratorSettings] = Field(default=None, alias="referralSettings")
    limits: List[LimitConfig] = Field(description="The set of [budget limits](https://docs.talon.one/docs/product/campaigns/settings/managing-campaign-budgets) for this campaign. ")
    campaign_groups: Optional[List[StrictInt]] = Field(default=None, description="The IDs of the [campaign groups](https://docs.talon.one/docs/product/account/managing-campaign-groups) this campaign belongs to. ", alias="campaignGroups")
    type: Optional[StrictStr] = Field(default='advanced', description="The campaign type. Possible type values:   - `cartItem`: Type of campaign that can apply effects only to cart items.   - `advanced`: Type of campaign that can apply effects to customer sessions and cart items. ")
    linked_store_ids: Optional[List[StrictInt]] = Field(default=None, description="A list of store IDs that you want to link to the campaign.  **Note:** Campaigns with linked store IDs will only be evaluated when there is a [customer session update](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) that references a linked store. ", alias="linkedStoreIds")
    budgets: Optional[List[CampaignBudget]] = Field(default=None, description="A list of all the budgets that are defined by this campaign and their usage.  **Note:** Budgets that are not defined do not appear in this list and their usage is not counted until they are defined. ")
    coupon_redemption_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Number of coupons redeemed in the campaign. ", alias="couponRedemptionCount")
    referral_redemption_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Number of referral codes redeemed in the campaign. ", alias="referralRedemptionCount")
    discount_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total amount of discounts redeemed in the campaign. ", alias="discountCount")
    discount_effect_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of times discounts were redeemed in this campaign. ", alias="discountEffectCount")
    coupon_creation_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of coupons created by rules in this campaign. ", alias="couponCreationCount")
    custom_effect_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of custom effects triggered by rules in this campaign. ", alias="customEffectCount")
    referral_creation_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of referrals created by rules in this campaign. ", alias="referralCreationCount")
    add_free_item_effect_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of times the [add free item effect](https://docs.talon.one/docs/dev/integration-api/api-effects#addfreeitem) can be triggered in this campaign. ", alias="addFreeItemEffectCount")
    awarded_giveaways_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of giveaways awarded by rules in this campaign. ", alias="awardedGiveawaysCount")
    created_loyalty_points_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty points created by rules in this campaign. ", alias="createdLoyaltyPointsCount")
    created_loyalty_points_effect_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty point creation effects triggered by rules in this campaign. ", alias="createdLoyaltyPointsEffectCount")
    redeemed_loyalty_points_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty points redeemed by rules in this campaign. ", alias="redeemedLoyaltyPointsCount")
    redeemed_loyalty_points_effect_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of loyalty point redemption effects triggered by rules in this campaign. ", alias="redeemedLoyaltyPointsEffectCount")
    call_api_effect_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of webhooks triggered by rules in this campaign. ", alias="callApiEffectCount")
    reservecoupon_effect_count: Optional[StrictInt] = Field(default=None, description="This property is **deprecated**. The count should be available under *budgets* property. Total number of reserve coupon effects triggered by rules in this campaign. ", alias="reservecouponEffectCount")
    last_activity: Optional[datetime] = Field(default=None, description="Timestamp of the most recent event received by this campaign.", alias="lastActivity")
    updated: Optional[datetime] = Field(default=None, description="Timestamp of the most recent update to the campaign's property. Updates to external entities used in this campaign are **not** registered by this property, such as collection or coupon updates. ")
    created_by: Optional[StrictStr] = Field(default=None, description="Name of the user who created this campaign if available.", alias="createdBy")
    updated_by: Optional[StrictStr] = Field(default=None, description="Name of the user who last updated this campaign if available.", alias="updatedBy")
    template_id: Optional[StrictInt] = Field(default=None, description="The ID of the Campaign Template this Campaign was created from.", alias="templateId")
    frontend_state: StrictStr = Field(description="The campaign state displayed in the Campaign Manager.", alias="frontendState")
    stores_imported: StrictBool = Field(description="Indicates whether the linked stores were imported via a CSV file.", alias="storesImported")
    value_maps_ids: Optional[List[StrictInt]] = Field(default=None, description="A list of value map IDs for the campaign.", alias="valueMapsIds")
    experiment_id: Optional[StrictInt] = Field(default=None, description="The ID of the Experiment this Campaign is part of.", alias="experimentId")
    revision_frontend_state: Optional[StrictStr] = Field(default=None, description="The campaign revision state displayed in the Campaign Manager.", alias="revisionFrontendState")
    active_revision_id: Optional[StrictInt] = Field(default=None, description="ID of the revision that was last activated on this campaign. ", alias="activeRevisionId")
    active_revision_version_id: Optional[StrictInt] = Field(default=None, description="ID of the revision version that is active on the campaign. ", alias="activeRevisionVersionId")
    version: Optional[StrictInt] = Field(default=None, description="Incrementing number representing how many revisions have been activated on this campaign, starts from 0 for a new campaign. ")
    current_revision_id: Optional[StrictInt] = Field(default=None, description="ID of the revision currently being modified for the campaign. ", alias="currentRevisionId")
    current_revision_version_id: Optional[StrictInt] = Field(default=None, description="ID of the latest version applied on the current revision. ", alias="currentRevisionVersionId")
    stage_revision: Optional[StrictBool] = Field(default=False, description="Flag for determining whether we use current revision when sending requests with staging API key. ", alias="stageRevision")
    __properties: ClassVar[List[str]] = ["id", "created", "applicationId", "userId", "name", "description", "startTime", "endTime", "attributes", "state", "activeRulesetId", "tags", "reevaluateOnReturn", "features", "couponSettings", "referralSettings", "limits", "campaignGroups", "type", "linkedStoreIds", "budgets", "couponRedemptionCount", "referralRedemptionCount", "discountCount", "discountEffectCount", "couponCreationCount", "customEffectCount", "referralCreationCount", "addFreeItemEffectCount", "awardedGiveawaysCount", "createdLoyaltyPointsCount", "createdLoyaltyPointsEffectCount", "redeemedLoyaltyPointsCount", "redeemedLoyaltyPointsEffectCount", "callApiEffectCount", "reservecouponEffectCount", "lastActivity", "updated", "createdBy", "updatedBy", "templateId", "frontendState", "storesImported", "valueMapsIds", "experimentId", "revisionFrontendState", "activeRevisionId", "activeRevisionVersionId", "version", "currentRevisionId", "currentRevisionVersionId", "stageRevision"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['enabled', 'disabled', 'archived']):
            raise ValueError("must be one of enum values ('enabled', 'disabled', 'archived')")
        return value

    @field_validator('features')
    def features_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['coupons', 'referrals', 'loyalty', 'giveaways', 'strikethrough', 'achievements']):
                raise ValueError("each list item must be one of ('coupons', 'referrals', 'loyalty', 'giveaways', 'strikethrough', 'achievements')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['cartItem', 'advanced']):
            raise ValueError("must be one of enum values ('cartItem', 'advanced')")
        return value

    @field_validator('frontend_state')
    def frontend_state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['expired', 'scheduled', 'running', 'disabled', 'archived', 'staged']):
            raise ValueError("must be one of enum values ('expired', 'scheduled', 'running', 'disabled', 'archived', 'staged')")
        return value

    @field_validator('revision_frontend_state')
    def revision_frontend_state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['revised', 'pending']):
            raise ValueError("must be one of enum values ('revised', 'pending')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Campaign from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coupon_settings
        if self.coupon_settings:
            _dict['couponSettings'] = self.coupon_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of referral_settings
        if self.referral_settings:
            _dict['referralSettings'] = self.referral_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in limits (list)
        _items = []
        if self.limits:
            for _item_limits in self.limits:
                if _item_limits:
                    _items.append(_item_limits.to_dict())
            _dict['limits'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in budgets (list)
        _items = []
        if self.budgets:
            for _item_budgets in self.budgets:
                if _item_budgets:
                    _items.append(_item_budgets.to_dict())
            _dict['budgets'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Campaign from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "applicationId": obj.get("applicationId"),
            "userId": obj.get("userId"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "startTime": obj.get("startTime"),
            "endTime": obj.get("endTime"),
            "attributes": obj.get("attributes"),
            "state": obj.get("state") if obj.get("state") is not None else 'enabled',
            "activeRulesetId": obj.get("activeRulesetId"),
            "tags": obj.get("tags"),
            "reevaluateOnReturn": obj.get("reevaluateOnReturn"),
            "features": obj.get("features"),
            "couponSettings": CodeGeneratorSettings.from_dict(obj["couponSettings"]) if obj.get("couponSettings") is not None else None,
            "referralSettings": CodeGeneratorSettings.from_dict(obj["referralSettings"]) if obj.get("referralSettings") is not None else None,
            "limits": [LimitConfig.from_dict(_item) for _item in obj["limits"]] if obj.get("limits") is not None else None,
            "campaignGroups": obj.get("campaignGroups"),
            "type": obj.get("type") if obj.get("type") is not None else 'advanced',
            "linkedStoreIds": obj.get("linkedStoreIds"),
            "budgets": [CampaignBudget.from_dict(_item) for _item in obj["budgets"]] if obj.get("budgets") is not None else None,
            "couponRedemptionCount": obj.get("couponRedemptionCount"),
            "referralRedemptionCount": obj.get("referralRedemptionCount"),
            "discountCount": obj.get("discountCount"),
            "discountEffectCount": obj.get("discountEffectCount"),
            "couponCreationCount": obj.get("couponCreationCount"),
            "customEffectCount": obj.get("customEffectCount"),
            "referralCreationCount": obj.get("referralCreationCount"),
            "addFreeItemEffectCount": obj.get("addFreeItemEffectCount"),
            "awardedGiveawaysCount": obj.get("awardedGiveawaysCount"),
            "createdLoyaltyPointsCount": obj.get("createdLoyaltyPointsCount"),
            "createdLoyaltyPointsEffectCount": obj.get("createdLoyaltyPointsEffectCount"),
            "redeemedLoyaltyPointsCount": obj.get("redeemedLoyaltyPointsCount"),
            "redeemedLoyaltyPointsEffectCount": obj.get("redeemedLoyaltyPointsEffectCount"),
            "callApiEffectCount": obj.get("callApiEffectCount"),
            "reservecouponEffectCount": obj.get("reservecouponEffectCount"),
            "lastActivity": obj.get("lastActivity"),
            "updated": obj.get("updated"),
            "createdBy": obj.get("createdBy"),
            "updatedBy": obj.get("updatedBy"),
            "templateId": obj.get("templateId"),
            "frontendState": obj.get("frontendState"),
            "storesImported": obj.get("storesImported"),
            "valueMapsIds": obj.get("valueMapsIds"),
            "experimentId": obj.get("experimentId"),
            "revisionFrontendState": obj.get("revisionFrontendState"),
            "activeRevisionId": obj.get("activeRevisionId"),
            "activeRevisionVersionId": obj.get("activeRevisionVersionId"),
            "version": obj.get("version"),
            "currentRevisionId": obj.get("currentRevisionId"),
            "currentRevisionVersionId": obj.get("currentRevisionVersionId"),
            "stageRevision": obj.get("stageRevision") if obj.get("stageRevision") is not None else False
        })
        return _obj


