# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from talon_one.models.campaign_set_node import CampaignSetNode
from typing import Optional, Set
from typing_extensions import Self

class CampaignSetBranchNode(BaseModel):
    """
    CampaignSetBranchNode
    """ # noqa: E501
    type: StrictStr = Field(description="Indicates the node type.")
    name: StrictStr = Field(description="Name of the set.")
    operator: StrictStr = Field(description="An indicator of how the set operates on its elements.")
    elements: List[CampaignSetNode] = Field(description="Child elements of this set.")
    group_id: StrictInt = Field(description="The ID of the campaign set.", alias="groupId")
    locked: StrictBool = Field(description="An indicator of whether the campaign set is locked for modification.")
    description: Optional[StrictStr] = Field(default=None, description="A description of the campaign set.")
    evaluation_mode: StrictStr = Field(description="The mode by which campaigns in the campaign evaluation group are evaluated.", alias="evaluationMode")
    evaluation_scope: StrictStr = Field(description="The evaluation scope of the campaign evaluation group.", alias="evaluationScope")
    __properties: ClassVar[List[str]] = ["type", "name", "operator", "elements", "groupId", "locked", "description", "evaluationMode", "evaluationScope"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SET']):
            raise ValueError("must be one of enum values ('SET')")
        return value

    @field_validator('operator')
    def operator_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ALL', 'FIRST']):
            raise ValueError("must be one of enum values ('ALL', 'FIRST')")
        return value

    @field_validator('evaluation_mode')
    def evaluation_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['stackable', 'listOrder', 'lowestDiscount', 'highestDiscount']):
            raise ValueError("must be one of enum values ('stackable', 'listOrder', 'lowestDiscount', 'highestDiscount')")
        return value

    @field_validator('evaluation_scope')
    def evaluation_scope_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['cartItem', 'session']):
            raise ValueError("must be one of enum values ('cartItem', 'session')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CampaignSetBranchNode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in elements (list)
        _items = []
        if self.elements:
            for _item_elements in self.elements:
                if _item_elements:
                    _items.append(_item_elements.to_dict())
            _dict['elements'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CampaignSetBranchNode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "name": obj.get("name"),
            "operator": obj.get("operator"),
            "elements": [CampaignSetNode.from_dict(_item) for _item in obj["elements"]] if obj.get("elements") is not None else None,
            "groupId": obj.get("groupId"),
            "locked": obj.get("locked"),
            "description": obj.get("description"),
            "evaluationMode": obj.get("evaluationMode"),
            "evaluationScope": obj.get("evaluationScope")
        })
        return _obj


