# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from talon_one.models.achievement_progress_with_definition import AchievementProgressWithDefinition
from talon_one.models.customer_profile import CustomerProfile
from talon_one.models.giveaway import Giveaway
from talon_one.models.inventory_coupon import InventoryCoupon
from talon_one.models.inventory_referral import InventoryReferral
from talon_one.models.loyalty import Loyalty
from typing import Optional, Set
from typing_extensions import Self

class CustomerInventory(BaseModel):
    """
    CustomerInventory
    """ # noqa: E501
    profile: Optional[CustomerProfile] = None
    loyalty: Optional[Loyalty] = None
    referrals: Optional[List[InventoryReferral]] = None
    coupons: Optional[List[InventoryCoupon]] = Field(default=None, description="The coupons reserved by this profile. This array includes hard and soft reservations. ")
    giveaways: Optional[List[Giveaway]] = None
    achievements: Optional[List[AchievementProgressWithDefinition]] = None
    __properties: ClassVar[List[str]] = ["profile", "loyalty", "referrals", "coupons", "giveaways", "achievements"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerInventory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of profile
        if self.profile:
            _dict['profile'] = self.profile.to_dict()
        # override the default output from pydantic by calling `to_dict()` of loyalty
        if self.loyalty:
            _dict['loyalty'] = self.loyalty.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in referrals (list)
        _items = []
        if self.referrals:
            for _item_referrals in self.referrals:
                if _item_referrals:
                    _items.append(_item_referrals.to_dict())
            _dict['referrals'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in coupons (list)
        _items = []
        if self.coupons:
            for _item_coupons in self.coupons:
                if _item_coupons:
                    _items.append(_item_coupons.to_dict())
            _dict['coupons'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in giveaways (list)
        _items = []
        if self.giveaways:
            for _item_giveaways in self.giveaways:
                if _item_giveaways:
                    _items.append(_item_giveaways.to_dict())
            _dict['giveaways'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in achievements (list)
        _items = []
        if self.achievements:
            for _item_achievements in self.achievements:
                if _item_achievements:
                    _items.append(_item_achievements.to_dict())
            _dict['achievements'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerInventory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "profile": CustomerProfile.from_dict(obj["profile"]) if obj.get("profile") is not None else None,
            "loyalty": Loyalty.from_dict(obj["loyalty"]) if obj.get("loyalty") is not None else None,
            "referrals": [InventoryReferral.from_dict(_item) for _item in obj["referrals"]] if obj.get("referrals") is not None else None,
            "coupons": [InventoryCoupon.from_dict(_item) for _item in obj["coupons"]] if obj.get("coupons") is not None else None,
            "giveaways": [Giveaway.from_dict(_item) for _item in obj["giveaways"]] if obj.get("giveaways") is not None else None,
            "achievements": [AchievementProgressWithDefinition.from_dict(_item) for _item in obj["achievements"]] if obj.get("achievements") is not None else None
        })
        return _obj


