# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class CustomerAnalytics(BaseModel):
    """
    A summary report of customer activity for a given time range.
    """ # noqa: E501
    accepted_coupons: StrictInt = Field(description="Total accepted coupons for this customer.", alias="acceptedCoupons")
    created_coupons: StrictInt = Field(description="Total created coupons for this customer.", alias="createdCoupons")
    free_items: StrictInt = Field(description="Total free items given to this customer.", alias="freeItems")
    total_orders: StrictInt = Field(description="Total orders made by this customer.", alias="totalOrders")
    total_discounted_orders: StrictInt = Field(description="Total orders made by this customer that had a discount.", alias="totalDiscountedOrders")
    total_revenue: Union[StrictFloat, StrictInt] = Field(description="Total Revenue across all closed sessions.", alias="totalRevenue")
    total_discounts: Union[StrictFloat, StrictInt] = Field(description="The sum of discounts that were given across all closed sessions.", alias="totalDiscounts")
    __properties: ClassVar[List[str]] = ["acceptedCoupons", "createdCoupons", "freeItems", "totalOrders", "totalDiscountedOrders", "totalRevenue", "totalDiscounts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerAnalytics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerAnalytics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acceptedCoupons": obj.get("acceptedCoupons"),
            "createdCoupons": obj.get("createdCoupons"),
            "freeItems": obj.get("freeItems"),
            "totalOrders": obj.get("totalOrders"),
            "totalDiscountedOrders": obj.get("totalDiscountedOrders"),
            "totalRevenue": obj.get("totalRevenue"),
            "totalDiscounts": obj.get("totalDiscounts")
        })
        return _obj


