# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from talon_one.models.accept_coupon_effect_props import AcceptCouponEffectProps
from talon_one.models.accept_referral_effect_props import AcceptReferralEffectProps
from talon_one.models.add_free_item_effect_props import AddFreeItemEffectProps
from talon_one.models.add_loyalty_points_effect_props import AddLoyaltyPointsEffectProps
from talon_one.models.add_to_audience_effect_props import AddToAudienceEffectProps
from talon_one.models.award_giveaway_effect_props import AwardGiveawayEffectProps
from talon_one.models.change_loyalty_tier_level_effect_props import ChangeLoyaltyTierLevelEffectProps
from talon_one.models.coupon_created_effect_props import CouponCreatedEffectProps
from talon_one.models.custom_effect_props import CustomEffectProps
from talon_one.models.deduct_loyalty_points_effect_props import DeductLoyaltyPointsEffectProps
from talon_one.models.error_effect_props import ErrorEffectProps
from talon_one.models.extend_loyalty_points_expiry_date_effect_props import ExtendLoyaltyPointsExpiryDateEffectProps
from talon_one.models.increase_achievement_progress_effect_props import IncreaseAchievementProgressEffectProps
from talon_one.models.redeem_referral_effect_props import RedeemReferralEffectProps
from talon_one.models.referral_created_effect_props import ReferralCreatedEffectProps
from talon_one.models.reject_coupon_effect_props import RejectCouponEffectProps
from talon_one.models.reject_referral_effect_props import RejectReferralEffectProps
from talon_one.models.remove_from_audience_effect_props import RemoveFromAudienceEffectProps
from talon_one.models.reserve_coupon_effect_props import ReserveCouponEffectProps
from talon_one.models.rollback_added_loyalty_points_effect_props import RollbackAddedLoyaltyPointsEffectProps
from talon_one.models.rollback_coupon_effect_props import RollbackCouponEffectProps
from talon_one.models.rollback_deducted_loyalty_points_effect_props import RollbackDeductedLoyaltyPointsEffectProps
from talon_one.models.rollback_discount_effect_props import RollbackDiscountEffectProps
from talon_one.models.rollback_increased_achievement_progress_effect_props import RollbackIncreasedAchievementProgressEffectProps
from talon_one.models.rollback_referral_effect_props import RollbackReferralEffectProps
from talon_one.models.set_discount_effect_props import SetDiscountEffectProps
from talon_one.models.set_discount_per_additional_cost_effect_props import SetDiscountPerAdditionalCostEffectProps
from talon_one.models.set_discount_per_additional_cost_per_item_effect_props import SetDiscountPerAdditionalCostPerItemEffectProps
from talon_one.models.set_discount_per_item_effect_props import SetDiscountPerItemEffectProps
from talon_one.models.set_loyalty_points_expiry_date_effect_props import SetLoyaltyPointsExpiryDateEffectProps
from talon_one.models.show_bundle_metadata_effect_props import ShowBundleMetadataEffectProps
from talon_one.models.show_notification_effect_props import ShowNotificationEffectProps
from talon_one.models.trigger_webhook_effect_props import TriggerWebhookEffectProps
from talon_one.models.update_attribute_effect_props import UpdateAttributeEffectProps
from talon_one.models.will_award_giveaway_effect_props import WillAwardGiveawayEffectProps
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

EFFECTPROPS_ONE_OF_SCHEMAS = ["AcceptCouponEffectProps", "AcceptReferralEffectProps", "AddFreeItemEffectProps", "AddLoyaltyPointsEffectProps", "AddToAudienceEffectProps", "AwardGiveawayEffectProps", "ChangeLoyaltyTierLevelEffectProps", "CouponCreatedEffectProps", "CustomEffectProps", "DeductLoyaltyPointsEffectProps", "ErrorEffectProps", "ExtendLoyaltyPointsExpiryDateEffectProps", "IncreaseAchievementProgressEffectProps", "RedeemReferralEffectProps", "ReferralCreatedEffectProps", "RejectCouponEffectProps", "RejectReferralEffectProps", "RemoveFromAudienceEffectProps", "ReserveCouponEffectProps", "RollbackAddedLoyaltyPointsEffectProps", "RollbackCouponEffectProps", "RollbackDeductedLoyaltyPointsEffectProps", "RollbackDiscountEffectProps", "RollbackIncreasedAchievementProgressEffectProps", "RollbackReferralEffectProps", "SetDiscountEffectProps", "SetDiscountPerAdditionalCostEffectProps", "SetDiscountPerAdditionalCostPerItemEffectProps", "SetDiscountPerItemEffectProps", "SetLoyaltyPointsExpiryDateEffectProps", "ShowBundleMetadataEffectProps", "ShowNotificationEffectProps", "TriggerWebhookEffectProps", "UpdateAttributeEffectProps", "WillAwardGiveawayEffectProps"]

class EffectProps(BaseModel):
    """
    The properties of the effect. See [API effects](https://docs.talon.one/docs/dev/integration-api/api-effects).
    """
    # data type: AcceptCouponEffectProps
    oneof_schema_1_validator: Optional[AcceptCouponEffectProps] = None
    # data type: AcceptReferralEffectProps
    oneof_schema_2_validator: Optional[AcceptReferralEffectProps] = None
    # data type: RedeemReferralEffectProps
    oneof_schema_3_validator: Optional[RedeemReferralEffectProps] = None
    # data type: RejectCouponEffectProps
    oneof_schema_4_validator: Optional[RejectCouponEffectProps] = None
    # data type: RejectReferralEffectProps
    oneof_schema_5_validator: Optional[RejectReferralEffectProps] = None
    # data type: CouponCreatedEffectProps
    oneof_schema_6_validator: Optional[CouponCreatedEffectProps] = None
    # data type: ReferralCreatedEffectProps
    oneof_schema_7_validator: Optional[ReferralCreatedEffectProps] = None
    # data type: SetDiscountEffectProps
    oneof_schema_8_validator: Optional[SetDiscountEffectProps] = None
    # data type: SetDiscountPerItemEffectProps
    oneof_schema_9_validator: Optional[SetDiscountPerItemEffectProps] = None
    # data type: SetDiscountPerAdditionalCostEffectProps
    oneof_schema_10_validator: Optional[SetDiscountPerAdditionalCostEffectProps] = None
    # data type: TriggerWebhookEffectProps
    oneof_schema_11_validator: Optional[TriggerWebhookEffectProps] = None
    # data type: AddLoyaltyPointsEffectProps
    oneof_schema_12_validator: Optional[AddLoyaltyPointsEffectProps] = None
    # data type: DeductLoyaltyPointsEffectProps
    oneof_schema_13_validator: Optional[DeductLoyaltyPointsEffectProps] = None
    # data type: ChangeLoyaltyTierLevelEffectProps
    oneof_schema_14_validator: Optional[ChangeLoyaltyTierLevelEffectProps] = None
    # data type: AddFreeItemEffectProps
    oneof_schema_15_validator: Optional[AddFreeItemEffectProps] = None
    # data type: ShowNotificationEffectProps
    oneof_schema_16_validator: Optional[ShowNotificationEffectProps] = None
    # data type: UpdateAttributeEffectProps
    oneof_schema_17_validator: Optional[UpdateAttributeEffectProps] = None
    # data type: RollbackCouponEffectProps
    oneof_schema_18_validator: Optional[RollbackCouponEffectProps] = None
    # data type: RollbackReferralEffectProps
    oneof_schema_19_validator: Optional[RollbackReferralEffectProps] = None
    # data type: RollbackDiscountEffectProps
    oneof_schema_20_validator: Optional[RollbackDiscountEffectProps] = None
    # data type: RollbackAddedLoyaltyPointsEffectProps
    oneof_schema_21_validator: Optional[RollbackAddedLoyaltyPointsEffectProps] = None
    # data type: RollbackDeductedLoyaltyPointsEffectProps
    oneof_schema_22_validator: Optional[RollbackDeductedLoyaltyPointsEffectProps] = None
    # data type: ShowBundleMetadataEffectProps
    oneof_schema_23_validator: Optional[ShowBundleMetadataEffectProps] = None
    # data type: AwardGiveawayEffectProps
    oneof_schema_24_validator: Optional[AwardGiveawayEffectProps] = None
    # data type: WillAwardGiveawayEffectProps
    oneof_schema_25_validator: Optional[WillAwardGiveawayEffectProps] = None
    # data type: ErrorEffectProps
    oneof_schema_26_validator: Optional[ErrorEffectProps] = None
    # data type: CustomEffectProps
    oneof_schema_27_validator: Optional[CustomEffectProps] = None
    # data type: SetDiscountPerAdditionalCostPerItemEffectProps
    oneof_schema_28_validator: Optional[SetDiscountPerAdditionalCostPerItemEffectProps] = None
    # data type: ReserveCouponEffectProps
    oneof_schema_29_validator: Optional[ReserveCouponEffectProps] = None
    # data type: AddToAudienceEffectProps
    oneof_schema_30_validator: Optional[AddToAudienceEffectProps] = None
    # data type: RemoveFromAudienceEffectProps
    oneof_schema_31_validator: Optional[RemoveFromAudienceEffectProps] = None
    # data type: IncreaseAchievementProgressEffectProps
    oneof_schema_32_validator: Optional[IncreaseAchievementProgressEffectProps] = None
    # data type: RollbackIncreasedAchievementProgressEffectProps
    oneof_schema_33_validator: Optional[RollbackIncreasedAchievementProgressEffectProps] = None
    # data type: ExtendLoyaltyPointsExpiryDateEffectProps
    oneof_schema_34_validator: Optional[ExtendLoyaltyPointsExpiryDateEffectProps] = None
    # data type: SetLoyaltyPointsExpiryDateEffectProps
    oneof_schema_35_validator: Optional[SetLoyaltyPointsExpiryDateEffectProps] = None
    actual_instance: Optional[Union[AcceptCouponEffectProps, AcceptReferralEffectProps, AddFreeItemEffectProps, AddLoyaltyPointsEffectProps, AddToAudienceEffectProps, AwardGiveawayEffectProps, ChangeLoyaltyTierLevelEffectProps, CouponCreatedEffectProps, CustomEffectProps, DeductLoyaltyPointsEffectProps, ErrorEffectProps, ExtendLoyaltyPointsExpiryDateEffectProps, IncreaseAchievementProgressEffectProps, RedeemReferralEffectProps, ReferralCreatedEffectProps, RejectCouponEffectProps, RejectReferralEffectProps, RemoveFromAudienceEffectProps, ReserveCouponEffectProps, RollbackAddedLoyaltyPointsEffectProps, RollbackCouponEffectProps, RollbackDeductedLoyaltyPointsEffectProps, RollbackDiscountEffectProps, RollbackIncreasedAchievementProgressEffectProps, RollbackReferralEffectProps, SetDiscountEffectProps, SetDiscountPerAdditionalCostEffectProps, SetDiscountPerAdditionalCostPerItemEffectProps, SetDiscountPerItemEffectProps, SetLoyaltyPointsExpiryDateEffectProps, ShowBundleMetadataEffectProps, ShowNotificationEffectProps, TriggerWebhookEffectProps, UpdateAttributeEffectProps, WillAwardGiveawayEffectProps]] = None
    one_of_schemas: Set[str] = { "AcceptCouponEffectProps", "AcceptReferralEffectProps", "AddFreeItemEffectProps", "AddLoyaltyPointsEffectProps", "AddToAudienceEffectProps", "AwardGiveawayEffectProps", "ChangeLoyaltyTierLevelEffectProps", "CouponCreatedEffectProps", "CustomEffectProps", "DeductLoyaltyPointsEffectProps", "ErrorEffectProps", "ExtendLoyaltyPointsExpiryDateEffectProps", "IncreaseAchievementProgressEffectProps", "RedeemReferralEffectProps", "ReferralCreatedEffectProps", "RejectCouponEffectProps", "RejectReferralEffectProps", "RemoveFromAudienceEffectProps", "ReserveCouponEffectProps", "RollbackAddedLoyaltyPointsEffectProps", "RollbackCouponEffectProps", "RollbackDeductedLoyaltyPointsEffectProps", "RollbackDiscountEffectProps", "RollbackIncreasedAchievementProgressEffectProps", "RollbackReferralEffectProps", "SetDiscountEffectProps", "SetDiscountPerAdditionalCostEffectProps", "SetDiscountPerAdditionalCostPerItemEffectProps", "SetDiscountPerItemEffectProps", "SetLoyaltyPointsExpiryDateEffectProps", "ShowBundleMetadataEffectProps", "ShowNotificationEffectProps", "TriggerWebhookEffectProps", "UpdateAttributeEffectProps", "WillAwardGiveawayEffectProps" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = EffectProps.model_construct()
        error_messages = []
        match = 0
        # validate data type: AcceptCouponEffectProps
        if not isinstance(v, AcceptCouponEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AcceptCouponEffectProps`")
        else:
            match += 1
        # validate data type: AcceptReferralEffectProps
        if not isinstance(v, AcceptReferralEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AcceptReferralEffectProps`")
        else:
            match += 1
        # validate data type: RedeemReferralEffectProps
        if not isinstance(v, RedeemReferralEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RedeemReferralEffectProps`")
        else:
            match += 1
        # validate data type: RejectCouponEffectProps
        if not isinstance(v, RejectCouponEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RejectCouponEffectProps`")
        else:
            match += 1
        # validate data type: RejectReferralEffectProps
        if not isinstance(v, RejectReferralEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RejectReferralEffectProps`")
        else:
            match += 1
        # validate data type: CouponCreatedEffectProps
        if not isinstance(v, CouponCreatedEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CouponCreatedEffectProps`")
        else:
            match += 1
        # validate data type: ReferralCreatedEffectProps
        if not isinstance(v, ReferralCreatedEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReferralCreatedEffectProps`")
        else:
            match += 1
        # validate data type: SetDiscountEffectProps
        if not isinstance(v, SetDiscountEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SetDiscountEffectProps`")
        else:
            match += 1
        # validate data type: SetDiscountPerItemEffectProps
        if not isinstance(v, SetDiscountPerItemEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SetDiscountPerItemEffectProps`")
        else:
            match += 1
        # validate data type: SetDiscountPerAdditionalCostEffectProps
        if not isinstance(v, SetDiscountPerAdditionalCostEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SetDiscountPerAdditionalCostEffectProps`")
        else:
            match += 1
        # validate data type: TriggerWebhookEffectProps
        if not isinstance(v, TriggerWebhookEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TriggerWebhookEffectProps`")
        else:
            match += 1
        # validate data type: AddLoyaltyPointsEffectProps
        if not isinstance(v, AddLoyaltyPointsEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AddLoyaltyPointsEffectProps`")
        else:
            match += 1
        # validate data type: DeductLoyaltyPointsEffectProps
        if not isinstance(v, DeductLoyaltyPointsEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DeductLoyaltyPointsEffectProps`")
        else:
            match += 1
        # validate data type: ChangeLoyaltyTierLevelEffectProps
        if not isinstance(v, ChangeLoyaltyTierLevelEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ChangeLoyaltyTierLevelEffectProps`")
        else:
            match += 1
        # validate data type: AddFreeItemEffectProps
        if not isinstance(v, AddFreeItemEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AddFreeItemEffectProps`")
        else:
            match += 1
        # validate data type: ShowNotificationEffectProps
        if not isinstance(v, ShowNotificationEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShowNotificationEffectProps`")
        else:
            match += 1
        # validate data type: UpdateAttributeEffectProps
        if not isinstance(v, UpdateAttributeEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UpdateAttributeEffectProps`")
        else:
            match += 1
        # validate data type: RollbackCouponEffectProps
        if not isinstance(v, RollbackCouponEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RollbackCouponEffectProps`")
        else:
            match += 1
        # validate data type: RollbackReferralEffectProps
        if not isinstance(v, RollbackReferralEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RollbackReferralEffectProps`")
        else:
            match += 1
        # validate data type: RollbackDiscountEffectProps
        if not isinstance(v, RollbackDiscountEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RollbackDiscountEffectProps`")
        else:
            match += 1
        # validate data type: RollbackAddedLoyaltyPointsEffectProps
        if not isinstance(v, RollbackAddedLoyaltyPointsEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RollbackAddedLoyaltyPointsEffectProps`")
        else:
            match += 1
        # validate data type: RollbackDeductedLoyaltyPointsEffectProps
        if not isinstance(v, RollbackDeductedLoyaltyPointsEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RollbackDeductedLoyaltyPointsEffectProps`")
        else:
            match += 1
        # validate data type: ShowBundleMetadataEffectProps
        if not isinstance(v, ShowBundleMetadataEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShowBundleMetadataEffectProps`")
        else:
            match += 1
        # validate data type: AwardGiveawayEffectProps
        if not isinstance(v, AwardGiveawayEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AwardGiveawayEffectProps`")
        else:
            match += 1
        # validate data type: WillAwardGiveawayEffectProps
        if not isinstance(v, WillAwardGiveawayEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WillAwardGiveawayEffectProps`")
        else:
            match += 1
        # validate data type: ErrorEffectProps
        if not isinstance(v, ErrorEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ErrorEffectProps`")
        else:
            match += 1
        # validate data type: CustomEffectProps
        if not isinstance(v, CustomEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CustomEffectProps`")
        else:
            match += 1
        # validate data type: SetDiscountPerAdditionalCostPerItemEffectProps
        if not isinstance(v, SetDiscountPerAdditionalCostPerItemEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SetDiscountPerAdditionalCostPerItemEffectProps`")
        else:
            match += 1
        # validate data type: ReserveCouponEffectProps
        if not isinstance(v, ReserveCouponEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReserveCouponEffectProps`")
        else:
            match += 1
        # validate data type: AddToAudienceEffectProps
        if not isinstance(v, AddToAudienceEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AddToAudienceEffectProps`")
        else:
            match += 1
        # validate data type: RemoveFromAudienceEffectProps
        if not isinstance(v, RemoveFromAudienceEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RemoveFromAudienceEffectProps`")
        else:
            match += 1
        # validate data type: IncreaseAchievementProgressEffectProps
        if not isinstance(v, IncreaseAchievementProgressEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IncreaseAchievementProgressEffectProps`")
        else:
            match += 1
        # validate data type: RollbackIncreasedAchievementProgressEffectProps
        if not isinstance(v, RollbackIncreasedAchievementProgressEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RollbackIncreasedAchievementProgressEffectProps`")
        else:
            match += 1
        # validate data type: ExtendLoyaltyPointsExpiryDateEffectProps
        if not isinstance(v, ExtendLoyaltyPointsExpiryDateEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExtendLoyaltyPointsExpiryDateEffectProps`")
        else:
            match += 1
        # validate data type: SetLoyaltyPointsExpiryDateEffectProps
        if not isinstance(v, SetLoyaltyPointsExpiryDateEffectProps):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SetLoyaltyPointsExpiryDateEffectProps`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in EffectProps with oneOf schemas: AcceptCouponEffectProps, AcceptReferralEffectProps, AddFreeItemEffectProps, AddLoyaltyPointsEffectProps, AddToAudienceEffectProps, AwardGiveawayEffectProps, ChangeLoyaltyTierLevelEffectProps, CouponCreatedEffectProps, CustomEffectProps, DeductLoyaltyPointsEffectProps, ErrorEffectProps, ExtendLoyaltyPointsExpiryDateEffectProps, IncreaseAchievementProgressEffectProps, RedeemReferralEffectProps, ReferralCreatedEffectProps, RejectCouponEffectProps, RejectReferralEffectProps, RemoveFromAudienceEffectProps, ReserveCouponEffectProps, RollbackAddedLoyaltyPointsEffectProps, RollbackCouponEffectProps, RollbackDeductedLoyaltyPointsEffectProps, RollbackDiscountEffectProps, RollbackIncreasedAchievementProgressEffectProps, RollbackReferralEffectProps, SetDiscountEffectProps, SetDiscountPerAdditionalCostEffectProps, SetDiscountPerAdditionalCostPerItemEffectProps, SetDiscountPerItemEffectProps, SetLoyaltyPointsExpiryDateEffectProps, ShowBundleMetadataEffectProps, ShowNotificationEffectProps, TriggerWebhookEffectProps, UpdateAttributeEffectProps, WillAwardGiveawayEffectProps. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in EffectProps with oneOf schemas: AcceptCouponEffectProps, AcceptReferralEffectProps, AddFreeItemEffectProps, AddLoyaltyPointsEffectProps, AddToAudienceEffectProps, AwardGiveawayEffectProps, ChangeLoyaltyTierLevelEffectProps, CouponCreatedEffectProps, CustomEffectProps, DeductLoyaltyPointsEffectProps, ErrorEffectProps, ExtendLoyaltyPointsExpiryDateEffectProps, IncreaseAchievementProgressEffectProps, RedeemReferralEffectProps, ReferralCreatedEffectProps, RejectCouponEffectProps, RejectReferralEffectProps, RemoveFromAudienceEffectProps, ReserveCouponEffectProps, RollbackAddedLoyaltyPointsEffectProps, RollbackCouponEffectProps, RollbackDeductedLoyaltyPointsEffectProps, RollbackDiscountEffectProps, RollbackIncreasedAchievementProgressEffectProps, RollbackReferralEffectProps, SetDiscountEffectProps, SetDiscountPerAdditionalCostEffectProps, SetDiscountPerAdditionalCostPerItemEffectProps, SetDiscountPerItemEffectProps, SetLoyaltyPointsExpiryDateEffectProps, ShowBundleMetadataEffectProps, ShowNotificationEffectProps, TriggerWebhookEffectProps, UpdateAttributeEffectProps, WillAwardGiveawayEffectProps. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into AcceptCouponEffectProps
        try:
            instance.actual_instance = AcceptCouponEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AcceptReferralEffectProps
        try:
            instance.actual_instance = AcceptReferralEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RedeemReferralEffectProps
        try:
            instance.actual_instance = RedeemReferralEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RejectCouponEffectProps
        try:
            instance.actual_instance = RejectCouponEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RejectReferralEffectProps
        try:
            instance.actual_instance = RejectReferralEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CouponCreatedEffectProps
        try:
            instance.actual_instance = CouponCreatedEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReferralCreatedEffectProps
        try:
            instance.actual_instance = ReferralCreatedEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SetDiscountEffectProps
        try:
            instance.actual_instance = SetDiscountEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SetDiscountPerItemEffectProps
        try:
            instance.actual_instance = SetDiscountPerItemEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SetDiscountPerAdditionalCostEffectProps
        try:
            instance.actual_instance = SetDiscountPerAdditionalCostEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TriggerWebhookEffectProps
        try:
            instance.actual_instance = TriggerWebhookEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AddLoyaltyPointsEffectProps
        try:
            instance.actual_instance = AddLoyaltyPointsEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DeductLoyaltyPointsEffectProps
        try:
            instance.actual_instance = DeductLoyaltyPointsEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ChangeLoyaltyTierLevelEffectProps
        try:
            instance.actual_instance = ChangeLoyaltyTierLevelEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AddFreeItemEffectProps
        try:
            instance.actual_instance = AddFreeItemEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShowNotificationEffectProps
        try:
            instance.actual_instance = ShowNotificationEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UpdateAttributeEffectProps
        try:
            instance.actual_instance = UpdateAttributeEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RollbackCouponEffectProps
        try:
            instance.actual_instance = RollbackCouponEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RollbackReferralEffectProps
        try:
            instance.actual_instance = RollbackReferralEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RollbackDiscountEffectProps
        try:
            instance.actual_instance = RollbackDiscountEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RollbackAddedLoyaltyPointsEffectProps
        try:
            instance.actual_instance = RollbackAddedLoyaltyPointsEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RollbackDeductedLoyaltyPointsEffectProps
        try:
            instance.actual_instance = RollbackDeductedLoyaltyPointsEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ShowBundleMetadataEffectProps
        try:
            instance.actual_instance = ShowBundleMetadataEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AwardGiveawayEffectProps
        try:
            instance.actual_instance = AwardGiveawayEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WillAwardGiveawayEffectProps
        try:
            instance.actual_instance = WillAwardGiveawayEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ErrorEffectProps
        try:
            instance.actual_instance = ErrorEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CustomEffectProps
        try:
            instance.actual_instance = CustomEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SetDiscountPerAdditionalCostPerItemEffectProps
        try:
            instance.actual_instance = SetDiscountPerAdditionalCostPerItemEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReserveCouponEffectProps
        try:
            instance.actual_instance = ReserveCouponEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AddToAudienceEffectProps
        try:
            instance.actual_instance = AddToAudienceEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RemoveFromAudienceEffectProps
        try:
            instance.actual_instance = RemoveFromAudienceEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IncreaseAchievementProgressEffectProps
        try:
            instance.actual_instance = IncreaseAchievementProgressEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RollbackIncreasedAchievementProgressEffectProps
        try:
            instance.actual_instance = RollbackIncreasedAchievementProgressEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExtendLoyaltyPointsExpiryDateEffectProps
        try:
            instance.actual_instance = ExtendLoyaltyPointsExpiryDateEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SetLoyaltyPointsExpiryDateEffectProps
        try:
            instance.actual_instance = SetLoyaltyPointsExpiryDateEffectProps.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into EffectProps with oneOf schemas: AcceptCouponEffectProps, AcceptReferralEffectProps, AddFreeItemEffectProps, AddLoyaltyPointsEffectProps, AddToAudienceEffectProps, AwardGiveawayEffectProps, ChangeLoyaltyTierLevelEffectProps, CouponCreatedEffectProps, CustomEffectProps, DeductLoyaltyPointsEffectProps, ErrorEffectProps, ExtendLoyaltyPointsExpiryDateEffectProps, IncreaseAchievementProgressEffectProps, RedeemReferralEffectProps, ReferralCreatedEffectProps, RejectCouponEffectProps, RejectReferralEffectProps, RemoveFromAudienceEffectProps, ReserveCouponEffectProps, RollbackAddedLoyaltyPointsEffectProps, RollbackCouponEffectProps, RollbackDeductedLoyaltyPointsEffectProps, RollbackDiscountEffectProps, RollbackIncreasedAchievementProgressEffectProps, RollbackReferralEffectProps, SetDiscountEffectProps, SetDiscountPerAdditionalCostEffectProps, SetDiscountPerAdditionalCostPerItemEffectProps, SetDiscountPerItemEffectProps, SetLoyaltyPointsExpiryDateEffectProps, ShowBundleMetadataEffectProps, ShowNotificationEffectProps, TriggerWebhookEffectProps, UpdateAttributeEffectProps, WillAwardGiveawayEffectProps. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into EffectProps with oneOf schemas: AcceptCouponEffectProps, AcceptReferralEffectProps, AddFreeItemEffectProps, AddLoyaltyPointsEffectProps, AddToAudienceEffectProps, AwardGiveawayEffectProps, ChangeLoyaltyTierLevelEffectProps, CouponCreatedEffectProps, CustomEffectProps, DeductLoyaltyPointsEffectProps, ErrorEffectProps, ExtendLoyaltyPointsExpiryDateEffectProps, IncreaseAchievementProgressEffectProps, RedeemReferralEffectProps, ReferralCreatedEffectProps, RejectCouponEffectProps, RejectReferralEffectProps, RemoveFromAudienceEffectProps, ReserveCouponEffectProps, RollbackAddedLoyaltyPointsEffectProps, RollbackCouponEffectProps, RollbackDeductedLoyaltyPointsEffectProps, RollbackDiscountEffectProps, RollbackIncreasedAchievementProgressEffectProps, RollbackReferralEffectProps, SetDiscountEffectProps, SetDiscountPerAdditionalCostEffectProps, SetDiscountPerAdditionalCostPerItemEffectProps, SetDiscountPerItemEffectProps, SetLoyaltyPointsExpiryDateEffectProps, ShowBundleMetadataEffectProps, ShowNotificationEffectProps, TriggerWebhookEffectProps, UpdateAttributeEffectProps, WillAwardGiveawayEffectProps. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AcceptCouponEffectProps, AcceptReferralEffectProps, AddFreeItemEffectProps, AddLoyaltyPointsEffectProps, AddToAudienceEffectProps, AwardGiveawayEffectProps, ChangeLoyaltyTierLevelEffectProps, CouponCreatedEffectProps, CustomEffectProps, DeductLoyaltyPointsEffectProps, ErrorEffectProps, ExtendLoyaltyPointsExpiryDateEffectProps, IncreaseAchievementProgressEffectProps, RedeemReferralEffectProps, ReferralCreatedEffectProps, RejectCouponEffectProps, RejectReferralEffectProps, RemoveFromAudienceEffectProps, ReserveCouponEffectProps, RollbackAddedLoyaltyPointsEffectProps, RollbackCouponEffectProps, RollbackDeductedLoyaltyPointsEffectProps, RollbackDiscountEffectProps, RollbackIncreasedAchievementProgressEffectProps, RollbackReferralEffectProps, SetDiscountEffectProps, SetDiscountPerAdditionalCostEffectProps, SetDiscountPerAdditionalCostPerItemEffectProps, SetDiscountPerItemEffectProps, SetLoyaltyPointsExpiryDateEffectProps, ShowBundleMetadataEffectProps, ShowNotificationEffectProps, TriggerWebhookEffectProps, UpdateAttributeEffectProps, WillAwardGiveawayEffectProps]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


