# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from talon_one.models.ledger_entry import LedgerEntry
from talon_one.models.meta import Meta
from typing import Optional, Set
from typing_extensions import Self

class Event(BaseModel):
    """
    Event
    """ # noqa: E501
    id: StrictInt = Field(description="The internal ID of this entity.")
    created: datetime = Field(description="The time this entity was created.")
    application_id: StrictInt = Field(description="The ID of the Application that owns this entity.", alias="applicationId")
    profile_id: Optional[StrictStr] = Field(default=None, description="ID of the customer profile set by your integration layer.  **Note:** If the customer does not yet have a known `profileId`, we recommend you use a guest `profileId`. ", alias="profileId")
    store_integration_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=1000)]] = Field(default=None, description="The integration ID of the store. You choose this ID when you create a store.", alias="storeIntegrationId")
    type: Annotated[str, Field(min_length=1, strict=True)] = Field(description="A string representing the event. Must not be a reserved event name.")
    attributes: Dict[str, Any] = Field(description="Arbitrary additional JSON data associated with the event.")
    session_id: Optional[StrictStr] = Field(default=None, description="The ID of the session that this event occurred in.", alias="sessionId")
    effects: List[Dict[str, Any]] = Field(description="An array of effects generated by the rules of the enabled campaigns of the Application.  You decide how to apply them in your system. See the list of [API effects](https://docs.talon.one/docs/dev/integration-api/api-effects). ")
    ledger_entries: Optional[List[LedgerEntry]] = Field(default=None, description="Ledger entries for the event.", alias="ledgerEntries")
    meta: Optional[Meta] = None
    __properties: ClassVar[List[str]] = ["id", "created", "applicationId", "profileId", "storeIntegrationId", "type", "attributes", "sessionId", "effects", "ledgerEntries", "meta"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Event from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ledger_entries (list)
        _items = []
        if self.ledger_entries:
            for _item_ledger_entries in self.ledger_entries:
                if _item_ledger_entries:
                    _items.append(_item_ledger_entries.to_dict())
            _dict['ledgerEntries'] = _items
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Event from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "applicationId": obj.get("applicationId"),
            "profileId": obj.get("profileId"),
            "storeIntegrationId": obj.get("storeIntegrationId"),
            "type": obj.get("type"),
            "attributes": obj.get("attributes"),
            "sessionId": obj.get("sessionId"),
            "effects": obj.get("effects"),
            "ledgerEntries": [LedgerEntry.from_dict(_item) for _item in obj["ledgerEntries"]] if obj.get("ledgerEntries") is not None else None,
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None
        })
        return _obj


