# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from talon_one.models.coupon_rejection_reason import CouponRejectionReason
from talon_one.models.referral_rejection_reason import ReferralRejectionReason
from typing import Optional, Set
from typing_extensions import Self

class Meta(BaseModel):
    """
    Meta
    """ # noqa: E501
    campaigns: Optional[Dict[str, Any]] = Field(default=None, description="Maps each evaluated campaign ID to a key-value list of that campaigns attributes. Campaigns without attributes will be omitted.")
    coupons: Optional[Dict[str, Any]] = Field(default=None, description="Maps the coupon value to a key-value list of that coupons attributes.")
    coupon_rejection_reason: Optional[CouponRejectionReason] = Field(default=None, alias="couponRejectionReason")
    referral_rejection_reason: Optional[ReferralRejectionReason] = Field(default=None, alias="referralRejectionReason")
    warnings: Optional[Dict[str, Any]] = Field(default=None, description="Contains warnings about possible misuse.")
    __properties: ClassVar[List[str]] = ["campaigns", "coupons", "couponRejectionReason", "referralRejectionReason", "warnings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Meta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coupon_rejection_reason
        if self.coupon_rejection_reason:
            _dict['couponRejectionReason'] = self.coupon_rejection_reason.to_dict()
        # override the default output from pydantic by calling `to_dict()` of referral_rejection_reason
        if self.referral_rejection_reason:
            _dict['referralRejectionReason'] = self.referral_rejection_reason.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Meta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "campaigns": obj.get("campaigns"),
            "coupons": obj.get("coupons"),
            "couponRejectionReason": CouponRejectionReason.from_dict(obj["couponRejectionReason"]) if obj.get("couponRejectionReason") is not None else None,
            "referralRejectionReason": ReferralRejectionReason.from_dict(obj["referralRejectionReason"]) if obj.get("referralRejectionReason") is not None else None,
            "warnings": obj.get("warnings")
        })
        return _obj


