# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class NewPriceAdjustment(BaseModel):
    """
    NewPriceAdjustment
    """ # noqa: E501
    price_type: StrictStr = Field(description="The price type (e.g. the price for members only) to apply to a given SKU.", alias="priceType")
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The value of the price type applied to the SKU. When set to `null`, the defined price type no longer applies to the SKU.")
    reference_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="A unique reference identifier, e.g. a UUID.", alias="referenceId")
    calculated_at: Optional[datetime] = Field(default=None, description="The time at which this price was calculated. If provided, this is used to determine the most recent price adjustment to choose if price adjustments overlap. Defaults to internal creation time if not provided.", alias="calculatedAt")
    effective_from: Optional[datetime] = Field(default=None, description="The date and time from which the price adjustment is effective.", alias="effectiveFrom")
    effective_until: Optional[datetime] = Field(default=None, description="The date and time until which the price adjustment is effective.", alias="effectiveUntil")
    context_id: Optional[StrictStr] = Field(default=None, description="Identifier of the context of this price adjustment (e.g. summer sale).", alias="contextId")
    __properties: ClassVar[List[str]] = ["priceType", "price", "referenceId", "calculatedAt", "effectiveFrom", "effectiveUntil", "contextId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NewPriceAdjustment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if price (nullable) is None
        # and model_fields_set contains the field
        if self.price is None and "price" in self.model_fields_set:
            _dict['price'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NewPriceAdjustment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "priceType": obj.get("priceType"),
            "price": obj.get("price"),
            "referenceId": obj.get("referenceId"),
            "calculatedAt": obj.get("calculatedAt"),
            "effectiveFrom": obj.get("effectiveFrom"),
            "effectiveUntil": obj.get("effectiveUntil"),
            "contextId": obj.get("contextId")
        })
        return _obj


