# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OutboundLogRequest(BaseModel):
    """
    Details of the outbound HTTP request.
    """ # noqa: E501
    method: StrictStr = Field(description="HTTP method of the outbound request.", json_schema_extra={"examples": ["POST"]})
    url: StrictStr = Field(description="Target URL of the outbound request.", json_schema_extra={"examples": ["https://example.com/webhook"]})
    headers: List[StrictStr] = Field(description="HTTP headers sent with the outbound request.", json_schema_extra={"examples": [["content-type: application/json"]]})
    body: Dict[str, Any] = Field(description="JSON request payload.", json_schema_extra={"examples": [{"ProfileIntegrationID": "URNGV8294NV", "LoyaltyProgramID": 5, "SubledgerID": "sub-123", "Amount": 10.99, "Reason": "Compensation", "TypeOfChange": "campaign_manager", "EmployeeName": "Franziska Schneider", "UserID": 25, "Operation": "addition", "StartDate": "2023-01-24T14:15:22Z", "ExpiryDate": "2024-01-24T14:15:22Z", "SessionIntegrationID": "cc53e4fa-547f-4f5e-8333-76e05c381f67", "NotificationType": "LoyaltyPointsDeducted", "TransactionUUID": "1a6a7599-2622-4489-9034-5a62da3944e0"}]})
    __properties: ClassVar[List[str]] = ["method", "url", "headers", "body"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OutboundLogRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OutboundLogRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "method": obj.get("method"),
            "url": obj.get("url"),
            "headers": obj.get("headers"),
            "body": obj.get("body")
        })
        return _obj


