# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from talon_one.models.outgoing_integration_braze_policy import OutgoingIntegrationBrazePolicy
from talon_one.models.outgoing_integration_clever_tap_policy import OutgoingIntegrationCleverTapPolicy
from talon_one.models.outgoing_integration_iterable_policy import OutgoingIntegrationIterablePolicy
from talon_one.models.outgoing_integration_mo_engage_policy import OutgoingIntegrationMoEngagePolicy
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

OUTGOINGINTEGRATIONCONFIGURATIONPOLICY_ONE_OF_SCHEMAS = ["OutgoingIntegrationBrazePolicy", "OutgoingIntegrationCleverTapPolicy", "OutgoingIntegrationIterablePolicy", "OutgoingIntegrationMoEngagePolicy"]

class OutgoingIntegrationConfigurationPolicy(BaseModel):
    """
    The outgoing integration policy specific to each integration type.
    """
    # data type: OutgoingIntegrationBrazePolicy
    oneof_schema_1_validator: Optional[OutgoingIntegrationBrazePolicy] = None
    # data type: OutgoingIntegrationCleverTapPolicy
    oneof_schema_2_validator: Optional[OutgoingIntegrationCleverTapPolicy] = None
    # data type: OutgoingIntegrationMoEngagePolicy
    oneof_schema_3_validator: Optional[OutgoingIntegrationMoEngagePolicy] = None
    # data type: OutgoingIntegrationIterablePolicy
    oneof_schema_4_validator: Optional[OutgoingIntegrationIterablePolicy] = None
    actual_instance: Optional[Union[OutgoingIntegrationBrazePolicy, OutgoingIntegrationCleverTapPolicy, OutgoingIntegrationIterablePolicy, OutgoingIntegrationMoEngagePolicy]] = None
    one_of_schemas: Set[str] = { "OutgoingIntegrationBrazePolicy", "OutgoingIntegrationCleverTapPolicy", "OutgoingIntegrationIterablePolicy", "OutgoingIntegrationMoEngagePolicy" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = OutgoingIntegrationConfigurationPolicy.model_construct()
        error_messages = []
        match = 0
        # validate data type: OutgoingIntegrationBrazePolicy
        if not isinstance(v, OutgoingIntegrationBrazePolicy):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OutgoingIntegrationBrazePolicy`")
        else:
            match += 1
        # validate data type: OutgoingIntegrationCleverTapPolicy
        if not isinstance(v, OutgoingIntegrationCleverTapPolicy):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OutgoingIntegrationCleverTapPolicy`")
        else:
            match += 1
        # validate data type: OutgoingIntegrationMoEngagePolicy
        if not isinstance(v, OutgoingIntegrationMoEngagePolicy):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OutgoingIntegrationMoEngagePolicy`")
        else:
            match += 1
        # validate data type: OutgoingIntegrationIterablePolicy
        if not isinstance(v, OutgoingIntegrationIterablePolicy):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OutgoingIntegrationIterablePolicy`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in OutgoingIntegrationConfigurationPolicy with oneOf schemas: OutgoingIntegrationBrazePolicy, OutgoingIntegrationCleverTapPolicy, OutgoingIntegrationIterablePolicy, OutgoingIntegrationMoEngagePolicy. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in OutgoingIntegrationConfigurationPolicy with oneOf schemas: OutgoingIntegrationBrazePolicy, OutgoingIntegrationCleverTapPolicy, OutgoingIntegrationIterablePolicy, OutgoingIntegrationMoEngagePolicy. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into OutgoingIntegrationBrazePolicy
        try:
            instance.actual_instance = OutgoingIntegrationBrazePolicy.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OutgoingIntegrationCleverTapPolicy
        try:
            instance.actual_instance = OutgoingIntegrationCleverTapPolicy.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OutgoingIntegrationMoEngagePolicy
        try:
            instance.actual_instance = OutgoingIntegrationMoEngagePolicy.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OutgoingIntegrationIterablePolicy
        try:
            instance.actual_instance = OutgoingIntegrationIterablePolicy.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into OutgoingIntegrationConfigurationPolicy with oneOf schemas: OutgoingIntegrationBrazePolicy, OutgoingIntegrationCleverTapPolicy, OutgoingIntegrationIterablePolicy, OutgoingIntegrationMoEngagePolicy. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into OutgoingIntegrationConfigurationPolicy with oneOf schemas: OutgoingIntegrationBrazePolicy, OutgoingIntegrationCleverTapPolicy, OutgoingIntegrationIterablePolicy, OutgoingIntegrationMoEngagePolicy. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], OutgoingIntegrationBrazePolicy, OutgoingIntegrationCleverTapPolicy, OutgoingIntegrationIterablePolicy, OutgoingIntegrationMoEngagePolicy]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


