# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OutgoingIntegrationTemplateWithConfigurationDetails(BaseModel):
    """
    OutgoingIntegrationTemplateWithConfigurationDetails
    """ # noqa: E501
    id: StrictInt = Field(description="Unique ID for this entity.", json_schema_extra={"examples": [6]})
    integration_type: StrictInt = Field(description="Unique ID of outgoing integration type.", alias="integrationType", json_schema_extra={"examples": [2]})
    title: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="The title of the integration template.", json_schema_extra={"examples": ["Email coupon codes"]})
    description: Annotated[str, Field(min_length=1, strict=True, max_length=1000)] = Field(description="The description of the specific outgoing integration template.", json_schema_extra={"examples": ["This template sends a coupon code to the specified audience by email."]})
    payload: StrictStr = Field(description="The API payload (supports templating using parameters) for this integration template.", json_schema_extra={"examples": ["{\n\t\"message\": \"${message}\"\n}"]})
    method: StrictStr = Field(description="API method for this webhook.", json_schema_extra={"examples": ["POST"]})
    relative_url: StrictStr = Field(description="The relative URL corresponding to each integration template.", alias="relativeUrl", json_schema_extra={"examples": ["/campaigns/trigger/send"]})
    headers: List[Annotated[str, Field(strict=True)]] = Field(description="The list of HTTP headers for this integration template.", json_schema_extra={"examples": [["{\"Content-Type\": \"application/json\"}"]]})
    policy: Dict[str, Any] = Field(description="The outgoing integration policy specific to each integration type.")
    __properties: ClassVar[List[str]] = ["id", "integrationType", "title", "description", "payload", "method", "relativeUrl", "headers", "policy"]

    @field_validator('method')
    def method_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['POST', 'PUT', 'GET', 'DELETE', 'PATCH']):
            raise ValueError("must be one of enum values ('POST', 'PUT', 'GET', 'DELETE', 'PATCH')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OutgoingIntegrationTemplateWithConfigurationDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OutgoingIntegrationTemplateWithConfigurationDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "integrationType": obj.get("integrationType"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "payload": obj.get("payload"),
            "method": obj.get("method"),
            "relativeUrl": obj.get("relativeUrl"),
            "headers": obj.get("headers"),
            "policy": obj.get("policy")
        })
        return _obj


