# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class PriceDetail(BaseModel):
    """
    PriceDetail
    """ # noqa: E501
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The value of this price type.")
    adjustment_context_id: Optional[StrictStr] = Field(default=None, description="The context identifier of the selected price adjustment.", alias="adjustmentContextId")
    adjustment_reference_id: Optional[UUID] = Field(default=None, description="The reference identifier of the selected price adjustment for this SKU.", alias="adjustmentReferenceId")
    adjustment_effective_from: Optional[datetime] = Field(default=None, description="The date and time from which the price adjustment is effective.", alias="adjustmentEffectiveFrom")
    adjustment_effective_until: Optional[datetime] = Field(default=None, description="The date and time until which the price adjustment is effective.", alias="adjustmentEffectiveUntil")
    __properties: ClassVar[List[str]] = ["price", "adjustmentContextId", "adjustmentReferenceId", "adjustmentEffectiveFrom", "adjustmentEffectiveUntil"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PriceDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PriceDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "price": obj.get("price"),
            "adjustmentContextId": obj.get("adjustmentContextId"),
            "adjustmentReferenceId": obj.get("adjustmentReferenceId"),
            "adjustmentEffectiveFrom": obj.get("adjustmentEffectiveFrom"),
            "adjustmentEffectiveUntil": obj.get("adjustmentEffectiveUntil")
        })
        return _obj


