# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from talon_one.models.prismatic_event_payload_coupon_based_notifications_limits import PrismaticEventPayloadCouponBasedNotificationsLimits
from typing import Optional, Set
from typing_extensions import Self

class PrismaticEventPayloadCouponBasedNotifications(BaseModel):
    """
    PrismaticEventPayloadCouponBasedNotifications
    """ # noqa: E501
    id: StrictInt = Field(alias="Id")
    created: datetime = Field(alias="Created")
    campaign_id: StrictInt = Field(alias="CampaignId")
    value: StrictStr = Field(alias="Value")
    usage_limit: StrictInt = Field(alias="UsageLimit")
    discount_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="DiscountLimit")
    reservation_limit: Optional[StrictInt] = Field(default=None, alias="ReservationLimit")
    start_date: Optional[datetime] = Field(default=None, alias="StartDate")
    expiry_date: Optional[datetime] = Field(default=None, alias="ExpiryDate")
    usage_counter: StrictInt = Field(alias="UsageCounter")
    discount_counter: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="DiscountCounter")
    discount_remainder: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="DiscountRemainder")
    referral_id: Optional[StrictInt] = Field(default=None, alias="ReferralId")
    recipient_integration_id: Optional[StrictStr] = Field(default=None, alias="RecipientIntegrationId")
    import_id: Optional[StrictInt] = Field(default=None, alias="ImportId")
    batch_id: Optional[StrictStr] = Field(default=None, alias="BatchId")
    attributes: Optional[Dict[str, Any]] = Field(default=None, alias="Attributes")
    limits: Optional[List[PrismaticEventPayloadCouponBasedNotificationsLimits]] = Field(default=None, alias="Limits")
    published_at: datetime = Field(description="Timestamp when the event was published.", alias="PublishedAt")
    source_of_event: StrictStr = Field(alias="SourceOfEvent")
    employee_name: StrictStr = Field(alias="EmployeeName")
    __properties: ClassVar[List[str]] = ["Id", "Created", "CampaignId", "Value", "UsageLimit", "DiscountLimit", "ReservationLimit", "StartDate", "ExpiryDate", "UsageCounter", "DiscountCounter", "DiscountRemainder", "ReferralId", "RecipientIntegrationId", "ImportId", "BatchId", "Attributes", "Limits", "PublishedAt", "SourceOfEvent", "EmployeeName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PrismaticEventPayloadCouponBasedNotifications from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in limits (list)
        _items = []
        if self.limits:
            for _item_limits in self.limits:
                if _item_limits:
                    _items.append(_item_limits.to_dict())
            _dict['Limits'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PrismaticEventPayloadCouponBasedNotifications from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Id": obj.get("Id"),
            "Created": obj.get("Created"),
            "CampaignId": obj.get("CampaignId"),
            "Value": obj.get("Value"),
            "UsageLimit": obj.get("UsageLimit"),
            "DiscountLimit": obj.get("DiscountLimit"),
            "ReservationLimit": obj.get("ReservationLimit"),
            "StartDate": obj.get("StartDate"),
            "ExpiryDate": obj.get("ExpiryDate"),
            "UsageCounter": obj.get("UsageCounter"),
            "DiscountCounter": obj.get("DiscountCounter"),
            "DiscountRemainder": obj.get("DiscountRemainder"),
            "ReferralId": obj.get("ReferralId"),
            "RecipientIntegrationId": obj.get("RecipientIntegrationId"),
            "ImportId": obj.get("ImportId"),
            "BatchId": obj.get("BatchId"),
            "Attributes": obj.get("Attributes"),
            "Limits": [PrismaticEventPayloadCouponBasedNotificationsLimits.from_dict(_item) for _item in obj["Limits"]] if obj.get("Limits") is not None else None,
            "PublishedAt": obj.get("PublishedAt"),
            "SourceOfEvent": obj.get("SourceOfEvent"),
            "EmployeeName": obj.get("EmployeeName")
        })
        return _obj


