# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PromotionCheckAttributeBlock(BaseModel):
    """
    PromotionCheckAttributeBlock
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier for this block.", json_schema_extra={"examples": ["a1b2c3d4-e5f6-7890-abcd-ef1234567890"]})
    type: StrictStr = Field(description="Identifies the block variant and determines which additional properties are present in it.")
    tags: Optional[List[StrictStr]] = Field(default=None, description="Semantic labels attached to this block.")
    operator: StrictStr = Field(description="The comparison operator applied to the attribute.", json_schema_extra={"examples": ["greaterThan"]})
    attribute: Optional[Any]
    value: Optional[Any] = None
    min: Optional[Any] = None
    max: Optional[Any] = None
    start: Optional[Any] = None
    end: Optional[Any] = None
    start_inclusive: Optional[StrictBool] = Field(default=None, description="When `true`, the `start` value is included in the range for the `within` operator.", alias="startInclusive", json_schema_extra={"examples": [True]})
    end_inclusive: Optional[StrictBool] = Field(default=None, description="When `true`, the `end` value is included in the range for the `within` operator.", alias="endInclusive", json_schema_extra={"examples": [True]})
    timezone_insensitive: Optional[StrictBool] = Field(default=None, description="Indicates whether the `within` operator ignores time zones and compares the wall-clock time only. When `false`, time zones are taken into account.", alias="timezoneInsensitive", json_schema_extra={"examples": [False]})
    values: Optional[Any] = None
    count: Optional[Any] = None
    on_failure: Optional[List[PromotionBlock]] = Field(default=None, description="Promotion blocks evaluated when this block fails or returns false.", alias="onFailure")
    __properties: ClassVar[List[str]] = ["id", "type", "tags", "operator", "attribute", "value", "min", "max", "start", "end", "startInclusive", "endInclusive", "timezoneInsensitive", "values", "count", "onFailure"]

    @field_validator('operator')
    def operator_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['equals', 'not(equals)', 'lessThan', 'lessThanOrEqual', 'greaterThan', 'greaterThanOrEqual', 'between', 'contains', 'not(contains)', 'matchesRegexp', 'startsWith', 'endsWith', 'oneOf', 'not(oneOf)', 'inCollection', 'not(inCollection)', 'empty', 'not(empty)', 'exists', 'not(exists)', 'isTrue', 'isFalse', 'containsAtLeast', 'containsExactly', 'containsOneOf', 'containsNoneOf', 'containsAllOf', 'after', 'before', 'within', 'not(within)']):
            raise ValueError("must be one of enum values ('equals', 'not(equals)', 'lessThan', 'lessThanOrEqual', 'greaterThan', 'greaterThanOrEqual', 'between', 'contains', 'not(contains)', 'matchesRegexp', 'startsWith', 'endsWith', 'oneOf', 'not(oneOf)', 'inCollection', 'not(inCollection)', 'empty', 'not(empty)', 'exists', 'not(exists)', 'isTrue', 'isFalse', 'containsAtLeast', 'containsExactly', 'containsOneOf', 'containsNoneOf', 'containsAllOf', 'after', 'before', 'within', 'not(within)')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PromotionCheckAttributeBlock from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in on_failure (list)
        _items = []
        if self.on_failure:
            for _item_on_failure in self.on_failure:
                if _item_on_failure:
                    _items.append(_item_on_failure.to_dict())
            _dict['onFailure'] = _items
        # set to None if attribute (nullable) is None
        # and model_fields_set contains the field
        if self.attribute is None and "attribute" in self.model_fields_set:
            _dict['attribute'] = None

        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        # set to None if min (nullable) is None
        # and model_fields_set contains the field
        if self.min is None and "min" in self.model_fields_set:
            _dict['min'] = None

        # set to None if max (nullable) is None
        # and model_fields_set contains the field
        if self.max is None and "max" in self.model_fields_set:
            _dict['max'] = None

        # set to None if start (nullable) is None
        # and model_fields_set contains the field
        if self.start is None and "start" in self.model_fields_set:
            _dict['start'] = None

        # set to None if end (nullable) is None
        # and model_fields_set contains the field
        if self.end is None and "end" in self.model_fields_set:
            _dict['end'] = None

        # set to None if values (nullable) is None
        # and model_fields_set contains the field
        if self.values is None and "values" in self.model_fields_set:
            _dict['values'] = None

        # set to None if count (nullable) is None
        # and model_fields_set contains the field
        if self.count is None and "count" in self.model_fields_set:
            _dict['count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PromotionCheckAttributeBlock from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "tags": obj.get("tags"),
            "operator": obj.get("operator"),
            "attribute": obj.get("attribute"),
            "value": obj.get("value"),
            "min": obj.get("min"),
            "max": obj.get("max"),
            "start": obj.get("start"),
            "end": obj.get("end"),
            "startInclusive": obj.get("startInclusive"),
            "endInclusive": obj.get("endInclusive"),
            "timezoneInsensitive": obj.get("timezoneInsensitive"),
            "values": obj.get("values"),
            "count": obj.get("count"),
            "onFailure": [PromotionBlock.from_dict(_item) for _item in obj["onFailure"]] if obj.get("onFailure") is not None else None
        })
        return _obj

from talon_one.models.promotion_block import PromotionBlock
# TODO: Rewrite to not use raise_errors
PromotionCheckAttributeBlock.model_rebuild(raise_errors=False)

