# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from talon_one.models.code_generator_settings import CodeGeneratorSettings
from talon_one.models.limit_config import LimitConfig
from typing import Optional, Set
from typing_extensions import Self

class RevisionVersion(BaseModel):
    """
    RevisionVersion
    """ # noqa: E501
    id: StrictInt = Field(description="Unique ID for this entity. Not to be confused with the Integration ID, which is set by your integration layer and used in most endpoints.")
    name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="A user-facing name for this campaign.")
    start_time: Optional[datetime] = Field(default=None, description="Timestamp when the campaign will become active.", alias="startTime")
    end_time: Optional[datetime] = Field(default=None, description="Timestamp when the campaign will become inactive.", alias="endTime")
    attributes: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary properties associated with this campaign.")
    description: Optional[StrictStr] = Field(default=None, description="A detailed description of the campaign.")
    active_ruleset_id: Optional[StrictInt] = Field(default=None, description="The ID of the ruleset this campaign template will use.", alias="activeRulesetId")
    tags: Optional[Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=50)]], Field(max_length=50)]] = Field(default=None, description="A list of tags for the campaign template.")
    coupon_settings: Optional[CodeGeneratorSettings] = Field(default=None, alias="couponSettings")
    referral_settings: Optional[CodeGeneratorSettings] = Field(default=None, alias="referralSettings")
    limits: Optional[List[LimitConfig]] = Field(default=None, description="The set of limits that will operate for this campaign version.")
    features: Optional[List[StrictStr]] = Field(default=None, description="A list of features for the campaign template.")
    account_id: StrictInt = Field(alias="accountId")
    application_id: StrictInt = Field(alias="applicationId")
    campaign_id: StrictInt = Field(alias="campaignId")
    created: datetime
    created_by: StrictInt = Field(alias="createdBy")
    revision_id: StrictInt = Field(alias="revisionId")
    version: StrictInt
    __properties: ClassVar[List[str]] = ["id", "name", "startTime", "endTime", "attributes", "description", "activeRulesetId", "tags", "couponSettings", "referralSettings", "limits", "features", "accountId", "applicationId", "campaignId", "created", "createdBy", "revisionId", "version"]

    @field_validator('features')
    def features_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['coupons', 'referrals', 'loyalty', 'giveaways', 'strikethrough', 'achievements']):
                raise ValueError("each list item must be one of ('coupons', 'referrals', 'loyalty', 'giveaways', 'strikethrough', 'achievements')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RevisionVersion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coupon_settings
        if self.coupon_settings:
            _dict['couponSettings'] = self.coupon_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of referral_settings
        if self.referral_settings:
            _dict['referralSettings'] = self.referral_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in limits (list)
        _items = []
        if self.limits:
            for _item_limits in self.limits:
                if _item_limits:
                    _items.append(_item_limits.to_dict())
            _dict['limits'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RevisionVersion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "startTime": obj.get("startTime"),
            "endTime": obj.get("endTime"),
            "attributes": obj.get("attributes"),
            "description": obj.get("description"),
            "activeRulesetId": obj.get("activeRulesetId"),
            "tags": obj.get("tags"),
            "couponSettings": CodeGeneratorSettings.from_dict(obj["couponSettings"]) if obj.get("couponSettings") is not None else None,
            "referralSettings": CodeGeneratorSettings.from_dict(obj["referralSettings"]) if obj.get("referralSettings") is not None else None,
            "limits": [LimitConfig.from_dict(_item) for _item in obj["limits"]] if obj.get("limits") is not None else None,
            "features": obj.get("features"),
            "accountId": obj.get("accountId"),
            "applicationId": obj.get("applicationId"),
            "campaignId": obj.get("campaignId"),
            "created": obj.get("created"),
            "createdBy": obj.get("createdBy"),
            "revisionId": obj.get("revisionId"),
            "version": obj.get("version")
        })
        return _obj


