# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Risk(BaseModel):
    """
    A risk detected by the anomaly detection service for one Application group.
    """ # noqa: E501
    id: StrictInt = Field(description="The internal ID of this entity.", json_schema_extra={"examples": [6]})
    created: datetime = Field(description="The time this entity was created.", json_schema_extra={"examples": ["2020-06-10T09:05:27.993483Z"]})
    notification_id: StrictInt = Field(description="The ID of the risk notification rule that flagged this risk.", alias="notificationId", json_schema_extra={"examples": [3]})
    run_date: date = Field(description="The date of the ML pipeline run that detected this risk.", alias="runDate", json_schema_extra={"examples": ["2026-06-05"]})
    group_key: StrictStr = Field(description="The Application group this risk was detected in. Contains the Application ID, or `__GLOBAL__` for metrics that are not grouped by Application. ", alias="groupKey", json_schema_extra={"examples": ["7"]})
    application_id: Optional[StrictInt] = Field(default=None, description="The ID of the Application this risk belongs to. Absent for global metrics.", alias="applicationId", json_schema_extra={"examples": [7]})
    status: StrictStr = Field(description="The triage lifecycle status of this risk.", json_schema_extra={"examples": ["active"]})
    criticality: StrictStr = Field(description="The critical classification bucket of this risk.", json_schema_extra={"examples": ["critical"]})
    entity: StrictStr = Field(description="The entity type the risk was detected in.", json_schema_extra={"examples": ["customer_profile"]})
    activity: StrictStr = Field(description="The activity metric the risk was detected in.", json_schema_extra={"examples": ["discounted_amount"]})
    time_frame: StrictStr = Field(description="The rolling time window of the risk evaluation.", alias="timeFrame", json_schema_extra={"examples": ["1_week"]})
    reported_date: datetime = Field(description="The time the ML service reported this risk.", alias="reportedDate", json_schema_extra={"examples": ["2026-06-05T06:26:13.698884Z"]})
    affected_entity_count: StrictInt = Field(description="The total number of entities affected by this risk.", alias="affectedEntityCount", json_schema_extra={"examples": [4437]})
    description: Optional[StrictStr] = Field(default=None, description="Human-readable description of the detected anomaly.", json_schema_extra={"examples": ["Unusual discount usage detected for 4437 customer profiles."]})
    modified: datetime = Field(description="Timestamp of the most recent update.", json_schema_extra={"examples": ["2026-06-05T06:26:13.698884Z"]})
    __properties: ClassVar[List[str]] = ["id", "created", "notificationId", "runDate", "groupKey", "applicationId", "status", "criticality", "entity", "activity", "timeFrame", "reportedDate", "affectedEntityCount", "description", "modified"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'in_review', 'confirmed', 'discarded']):
            raise ValueError("must be one of enum values ('active', 'in_review', 'confirmed', 'discarded')")
        return value

    @field_validator('criticality')
    def criticality_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['critical', 'not_critical']):
            raise ValueError("must be one of enum values ('critical', 'not_critical')")
        return value

    @field_validator('entity')
    def entity_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['customer_profile', 'customer_session']):
            raise ValueError("must be one of enum values ('customer_profile', 'customer_session')")
        return value

    @field_validator('activity')
    def activity_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['loyalty_points_earned', 'discounted_amount', 'completed_orders', 'coupon_attempts']):
            raise ValueError("must be one of enum values ('loyalty_points_earned', 'discounted_amount', 'completed_orders', 'coupon_attempts')")
        return value

    @field_validator('time_frame')
    def time_frame_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['1_day', '1_week', '1_month']):
            raise ValueError("must be one of enum values ('1_day', '1_week', '1_month')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Risk from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Risk from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created": obj.get("created"),
            "notificationId": obj.get("notificationId"),
            "runDate": obj.get("runDate"),
            "groupKey": obj.get("groupKey"),
            "applicationId": obj.get("applicationId"),
            "status": obj.get("status"),
            "criticality": obj.get("criticality"),
            "entity": obj.get("entity"),
            "activity": obj.get("activity"),
            "timeFrame": obj.get("timeFrame"),
            "reportedDate": obj.get("reportedDate"),
            "affectedEntityCount": obj.get("affectedEntityCount"),
            "description": obj.get("description"),
            "modified": obj.get("modified")
        })
        return _obj


