# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RollbackAddedLoyaltyPointsEffectProps(BaseModel):
    """
    This effect is triggered in the following cases:  - A session was cancelled in which loyalty points have been added. - A session was partially returned and loyalty point were added by the returned items. See [returning items](https://docs.talon.one/docs/dev/tutorials/partially-return-a-session).  If you use the [Add loyalty points per item effect](https://docs.talon.one/docs/product/rules/effects/available-effects#reward-effects), use the `cartItemPosition` property to identify which items the loyalty points were rolled back for.  If you use **Add loyalty points per item** and if the session contains some cart items with _quantity > 1_, use the `cartItemSubPosition` property to identify the item unit in its line item.  If the loyalty program is [profile-based](https://docs.talon.one/docs/product/loyalty-programs/overview#loyalty-program-types), use the `recipientIntegrationId` property to identify the user for whom the loyalty points are rolled back. If the loyalty program is [card-based](https://docs.talon.one/docs/product/loyalty-programs/overview#loyalty-program-types), use the `cardIdentifier` property to identify the loyalty card where the points were originally added.
    """ # noqa: E501
    program_id: StrictInt = Field(description="The ID of the loyalty program where these points were rolled back.", alias="programId")
    sub_ledger_id: StrictStr = Field(description="The ID of the subledger within the loyalty program where these points were rolled back.", alias="subLedgerId")
    value: Union[StrictFloat, StrictInt] = Field(description="The amount of points that were rolled back.")
    recipient_integration_id: Annotated[str, Field(strict=True, max_length=1000)] = Field(description="The user for whom these points were rolled back.", alias="recipientIntegrationId", json_schema_extra={"examples": ["URNGV8294NV"]})
    transaction_uuid: StrictStr = Field(description="The identifier of this loyalty point transaction.", alias="transactionUUID")
    cart_item_position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="(_Add points per cart item_ only.) The index of the item in the `cartItem` object for which these points were rolled back.", alias="cartItemPosition")
    cart_item_sub_position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="(_Add points per cart item_ ) The index of the item unit in its line item.", alias="cartItemSubPosition")
    card_identifier: Optional[Annotated[str, Field(min_length=4, strict=True, max_length=108)]] = Field(default=None, description="The identifier of the card on which these points were originally added.", alias="cardIdentifier", json_schema_extra={"examples": ["summer-loyalty-card-0543"]})
    __properties: ClassVar[List[str]] = ["programId", "subLedgerId", "value", "recipientIntegrationId", "transactionUUID", "cartItemPosition", "cartItemSubPosition", "cardIdentifier"]

    @field_validator('card_identifier')
    def card_identifier_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9._%+@-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9._%+@-]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RollbackAddedLoyaltyPointsEffectProps from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RollbackAddedLoyaltyPointsEffectProps from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "programId": obj.get("programId"),
            "subLedgerId": obj.get("subLedgerId"),
            "value": obj.get("value"),
            "recipientIntegrationId": obj.get("recipientIntegrationId"),
            "transactionUUID": obj.get("transactionUUID"),
            "cartItemPosition": obj.get("cartItemPosition"),
            "cartItemSubPosition": obj.get("cartItemSubPosition"),
            "cardIdentifier": obj.get("cardIdentifier")
        })
        return _obj


