# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RollbackDeductedLoyaltyPointsEffectProps(BaseModel):
    """
    The properties specific to the \"rollbackDeductedLoyaltyPoints\" effect. This effect is triggered whenever a previously closed session is cancelled and a deductLoyaltyPoints effect was revoked.
    """ # noqa: E501
    program_id: StrictInt = Field(description="The ID of the loyalty program where these points were reimbursed.", alias="programId")
    sub_ledger_id: StrictStr = Field(description="The ID of the subledger within the loyalty program where these points were reimbursed.", alias="subLedgerId")
    value: Union[StrictFloat, StrictInt] = Field(description="The amount of reimbursed points that were added.")
    recipient_integration_id: Annotated[str, Field(strict=True, max_length=1000)] = Field(description="The user for whom these points were reimbursed.", alias="recipientIntegrationId")
    start_date: Optional[datetime] = Field(default=None, description="Date after which the reimbursed points will be valid.", alias="startDate")
    expiry_date: Optional[datetime] = Field(default=None, description="Date after which the reimbursed points will expire.", alias="expiryDate")
    transaction_uuid: StrictStr = Field(description="The identifier of 'addition' entries added to the ledger as the `deductLoyaltyPoints` effect is rolled back.", alias="transactionUUID")
    card_identifier: Optional[Annotated[str, Field(min_length=4, strict=True, max_length=108)]] = Field(default=None, description="The alphanumeric identifier of the loyalty card. ", alias="cardIdentifier")
    __properties: ClassVar[List[str]] = ["programId", "subLedgerId", "value", "recipientIntegrationId", "startDate", "expiryDate", "transactionUUID", "cardIdentifier"]

    @field_validator('card_identifier')
    def card_identifier_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Za-z0-9_-]*$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9_-]*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RollbackDeductedLoyaltyPointsEffectProps from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RollbackDeductedLoyaltyPointsEffectProps from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "programId": obj.get("programId"),
            "subLedgerId": obj.get("subLedgerId"),
            "value": obj.get("value"),
            "recipientIntegrationId": obj.get("recipientIntegrationId"),
            "startDate": obj.get("startDate"),
            "expiryDate": obj.get("expiryDate"),
            "transactionUUID": obj.get("transactionUUID"),
            "cardIdentifier": obj.get("cardIdentifier")
        })
        return _obj


