# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RuleFailureReason(BaseModel):
    """
    Details about why a rule failed.
    """ # noqa: E501
    campaign_id: StrictInt = Field(description="The ID of the campaign that contains the rule that failed.", alias="campaignID")
    campaign_name: StrictStr = Field(description="The name of the campaign that contains the rule that failed.", alias="campaignName")
    ruleset_id: StrictInt = Field(description="The ID of the ruleset that contains the rule that failed.", alias="rulesetID")
    coupon_id: Optional[StrictInt] = Field(default=None, description="The ID of the coupon that was being evaluated at the time of the rule failure.", alias="couponID")
    coupon_value: Optional[StrictStr] = Field(default=None, description="The code of the coupon that was being evaluated at the time of the rule failure.", alias="couponValue")
    referral_id: Optional[StrictInt] = Field(default=None, description="The ID of the referral that was being evaluated at the time of the rule failure.", alias="referralID")
    referral_value: Optional[StrictStr] = Field(default=None, description="The code of the referral that was being evaluated at the time of the rule failure.", alias="referralValue")
    rule_index: StrictInt = Field(description="The index of the rule that failed within the ruleset.", alias="ruleIndex")
    rule_name: StrictStr = Field(description="The name of the rule that failed within the ruleset.", alias="ruleName")
    condition_index: Optional[StrictInt] = Field(default=None, description="The index of the condition that failed.", alias="conditionIndex")
    effect_index: Optional[StrictInt] = Field(default=None, description="The index of the effect that failed.", alias="effectIndex")
    details: Optional[StrictStr] = Field(default=None, description="More details about the failure.")
    evaluation_group_id: Optional[StrictInt] = Field(default=None, description="The ID of the evaluation group. For more information, see [Managing campaign evaluation](https://docs.talon.one/docs/product/applications/managing-campaign-evaluation).", alias="evaluationGroupID")
    evaluation_group_mode: Optional[StrictStr] = Field(default=None, description="The evaluation mode of the evaluation group. For more information, see [Managing campaign evaluation](https://docs.talon.one/docs/product/applications/managing-campaign-", alias="evaluationGroupMode")
    __properties: ClassVar[List[str]] = ["campaignID", "campaignName", "rulesetID", "couponID", "couponValue", "referralID", "referralValue", "ruleIndex", "ruleName", "conditionIndex", "effectIndex", "details", "evaluationGroupID", "evaluationGroupMode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuleFailureReason from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuleFailureReason from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "campaignID": obj.get("campaignID"),
            "campaignName": obj.get("campaignName"),
            "rulesetID": obj.get("rulesetID"),
            "couponID": obj.get("couponID"),
            "couponValue": obj.get("couponValue"),
            "referralID": obj.get("referralID"),
            "referralValue": obj.get("referralValue"),
            "ruleIndex": obj.get("ruleIndex"),
            "ruleName": obj.get("ruleName"),
            "conditionIndex": obj.get("conditionIndex"),
            "effectIndex": obj.get("effectIndex"),
            "details": obj.get("details"),
            "evaluationGroupID": obj.get("evaluationGroupID"),
            "evaluationGroupMode": obj.get("evaluationGroupMode")
        })
        return _obj


