# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SetDiscountPerItemEffectProps(BaseModel):
    """
    This effect schema is returned when you use the **Discount individual items**, **Discount individual items pro rata**, or **Discount individual item in bundles** effect in a rule.  It indicates that a discount per item should be applied on the specific item specified in the effect.  The properties it contains depends on:  - Whether you used a pro rata effect or not. - Whether you used an effect with bundles or not. - Whether the partial discount feature is enabled.
    """ # noqa: E501
    name: StrictStr = Field(description="The description of this discount. `#number` is equal to the `position` property.")
    value: Union[StrictFloat, StrictInt] = Field(description="The monetary value of the effective discount applied to the item.")
    position: Union[StrictFloat, StrictInt] = Field(description="The index of the item in the `cartItem` object on which this discount should be applied.")
    sub_position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The index of the item unit in its line item.", alias="subPosition")
    desired_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="_(Partial discounts enabled only)_ The monetary value of the discount to be applied to the item without considering budget limitations.", alias="desiredValue")
    scope: Optional[StrictStr] = Field(default=None, description="What the discount applies to. Possible values:  - `price`: discount on the price of the item. - `additionalCosts`: discount on the [additional cost](https://docs.talon.one/docs/product/account/dev-tools/manage-additional-costs) of the item. - `itemTotal`: discount on the sum of price + additional cost of the item.")
    total_discount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="_(Pro rata discounts only)_ The monetary value of the total effective discount", alias="totalDiscount")
    desired_total_discount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="_(Pro rata discounts only)_ The monetary value of the total discount to be applied without considering budget limitations", alias="desiredTotalDiscount")
    bundle_index: Optional[StrictInt] = Field(default=None, description="_(Discounts with bundles only)_ The position of the specific item bundle in the list of bundles created from the same bundle definition.", alias="bundleIndex")
    bundle_name: Optional[StrictStr] = Field(default=None, description="_(Discounts with bundles only)_ The name of the bundle definition.", alias="bundleName")
    targeted_item_position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="_(Discounting individual item in bundles only)_ The index of the targeted bundle item on which the applied discount is based.", alias="targetedItemPosition")
    targeted_item_sub_position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="_(Discounting individual item in bundles only)_ The sub-position of the targeted bundle item on which the applied discount is based.", alias="targetedItemSubPosition")
    excluded_from_price_history: Optional[StrictBool] = Field(default=None, description="When set to `true`, the applied discount is excluded from the item's price history.", alias="excludedFromPriceHistory")
    __properties: ClassVar[List[str]] = ["name", "value", "position", "subPosition", "desiredValue", "scope", "totalDiscount", "desiredTotalDiscount", "bundleIndex", "bundleName", "targetedItemPosition", "targetedItemSubPosition", "excludedFromPriceHistory"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SetDiscountPerItemEffectProps from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SetDiscountPerItemEffectProps from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "value": obj.get("value"),
            "position": obj.get("position"),
            "subPosition": obj.get("subPosition"),
            "desiredValue": obj.get("desiredValue"),
            "scope": obj.get("scope"),
            "totalDiscount": obj.get("totalDiscount"),
            "desiredTotalDiscount": obj.get("desiredTotalDiscount"),
            "bundleIndex": obj.get("bundleIndex"),
            "bundleName": obj.get("bundleName"),
            "targetedItemPosition": obj.get("targetedItemPosition"),
            "targetedItemSubPosition": obj.get("targetedItemSubPosition"),
            "excludedFromPriceHistory": obj.get("excludedFromPriceHistory")
        })
        return _obj


