# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from talon_one.models.trigger_custom_effect_block1_custom_effect import TriggerCustomEffectBlock1CustomEffect
from talon_one.models.trigger_custom_effect_block1_target import TriggerCustomEffectBlock1Target
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TriggerCustomEffectBlock(BaseModel):
    """
    TriggerCustomEffectBlock
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier for this block.", json_schema_extra={"examples": ["a1b2c3d4-e5f6-7890-abcd-ef1234567890"]})
    type: StrictStr = Field(description="Identifies the block variant and determines which additional properties are present in it.")
    tags: Optional[List[StrictStr]] = Field(default=None, description="Semantic labels attached to this block.")
    custom_effect: TriggerCustomEffectBlock1CustomEffect = Field(alias="customEffect")
    params: Optional[Dict[str, Any]] = Field(default=None, description="The custom effect's parameters, in configured order. Each property name is the parameter's title, lowercased with spaces replaced by underscores (for example, `Order ID` becomes `order_id`); falls back to `param_0`, `param_1`, and so on if a title is blank or collides with another.", json_schema_extra={"examples": [{"template_id": "TPL-10293"}]})
    target: TriggerCustomEffectBlock1Target
    on_error: Optional[Dict[str, List[PromotionBlock]]] = Field(default=None, description="Named error handlers evaluated when a specific error occurs.", alias="onError")
    __properties: ClassVar[List[str]] = ["id", "type", "tags", "customEffect", "params", "target", "onError"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TriggerCustomEffectBlock from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of custom_effect
        if self.custom_effect:
            _dict['customEffect'] = self.custom_effect.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in on_error (dict of array)
        _field_dict_of_array = {}
        if self.on_error:
            for _key_on_error in self.on_error:
                if self.on_error[_key_on_error] is not None:
                    _field_dict_of_array[_key_on_error] = [
                        _item.to_dict() for _item in self.on_error[_key_on_error]
                    ]
            _dict['onError'] = _field_dict_of_array
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TriggerCustomEffectBlock from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "tags": obj.get("tags"),
            "customEffect": TriggerCustomEffectBlock1CustomEffect.from_dict(obj["customEffect"]) if obj.get("customEffect") is not None else None,
            "params": obj.get("params"),
            "target": TriggerCustomEffectBlock1Target.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "onError": {
                _k: [PromotionBlock.from_dict(_item) for _item in _v] if _v is not None else None
                for _k, _v in obj["onError"].items()
            }
            if obj.get("onError") is not None
            else None
        })
        return _obj

from talon_one.models.promotion_block import PromotionBlock
# TODO: Rewrite to not use raise_errors
TriggerCustomEffectBlock.model_rebuild(raise_errors=False)

